### ISSUE TITLE
Cannot get parameters for transforms?

### ISSUE THREAD

**Issue by klausmh** [dotnet/machinelearning#1015]
### System information

- **OS version/distro**: Win 10 / ML.NET 0.5.0
- **.NET Version (eg., dotnet --info)**: 4.6.2

### Issue

- **What did you do?**

Created an affine transform, e.g.,
```
NormalizeTransform.Create(environment, new NormalizeTransform.MeanVarArguments { Column = normalizeTransformColumns.ToArray(), UseCdf = true }, data);
```

- **What happened?**

The scale and offset of the actual transform created cannot be retrieved (or can only be retrieved via reflection).

- **What did you expect?**

A way to retrieve parameters of transforms.

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by Ivanidzo4ka** [comment]
Can you take a look on our new API?
https://github.com/dotnet/machinelearning/blob/master/docs/code/MlNetCookBook.md#how-do-i-train-a-regression-model
```
Prediction: mlContext.Regression.Trainers.Sdca(label: r.Target, features: r.FeatureVector.Normalize())));
```
this is example of how you normalize data.
In your case you need to use `r.FeatureVector.NormalizeByMeanVar` instead of ` r.FeatureVector.Normalize` because you want to use MeanVar normalizer.

In order to get access to scale and offset you need to do following:
define two Immutable arrays.
```
            ImmutableArray<float> scale;
            ImmutableArray<float> offset;
```
use onFit delegate inside normalizer:
```
    r.FeatureVector.NormalizeByMeanVar(onFit: (x, y) => { scale = x; offset = y; })
```

**Comment by klausmh** [comment]
No. I am using the dynamic API. This seems to be only available for the static API?

**Comment by Ivanidzo4ka** [comment]
See
https://github.com/dotnet/machinelearning/blob/617f0f6bc3b0bcbf8e0af86594a706406c274de0/test/Microsoft.ML.Functional.Tests/IntrospectiveTraining.cs#L244
