### ISSUE TITLE
 ML.Ensemble assembly is not part of any NuGet

### ISSUE THREAD

**Issue by ganik** [dotnet/machinelearning#1078]
ML.NET 0.6

ML.Ensemble is not put into any of ML.NET NuGets

**Comment by eerhardt** [comment]
@shauheen - this should be a pretty easy fix. I assume we want this in the `Microsoft.ML` nuget package.

**Comment by suhailsinghbains** [comment]
Hi, I am new to this and sending a PR right away.
Thanks

**Comment by suhailsinghbains** [comment]
Should I remove every instance of ML.Ensemble from the whole project(s) or just the ML.Core?
that would be very helpful.
Thanks

**Comment by eerhardt** [comment]
The fix here is to add `ML.Ensemble` to the `Microsoft.ML` nuget package. To do this, 

https://github.com/dotnet/machinelearning/blob/53cdb20358e7ae98cdaf6de198e35f48fbdac269/src/Microsoft.ML.Ensemble/Microsoft.ML.Ensemble.csproj#L5

Needs to change to `Microsoft.ML`.

The alternative is to actually create a `Microsoft.ML.Ensemble` project under https://github.com/dotnet/machinelearning/tree/master/pkg.

@TomFinley @Zruty0 - any opinion on which way to go here? Is the stuff in `ML.Ensemble` considered "core" and should be put into the `Microsoft.ML` package? Or should it go in its own separate package?

Since we haven't had a customer complain that we aren't shipping this, it doesn't feel like it is a "core" scenario, so having a separate package seems justified to me.

**Comment by suhailsinghbains** [comment]
Ohh thanks for giving me an insight, very interesting. I'll wait for the tagged people to reply and start with the bug right away :)

**Comment by suhailsinghbains** [comment]
I'll send a PR for the 1st solution given soon, as I really want to solve the bug :)
