### ISSUE TITLE
IMuliStreamSource to be a class

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1090]
I want to be able to call `textReader.Read("file.txt")`, instead of having to explicitly create a `MultiFileSource`. 

I think this can be achieved by turning the `IMultiStreamSource` into a base class.

**Comment by Ivanidzo4ka** [comment]
https://github.com/dotnet/machinelearning/issues/1041

Can we just change Read method and accept string or list of string and wrap them in MultiStreamSource internally?

**Comment by TomFinley** [comment]
> Can we just change Read method and accept string or list of string and wrap them in MultiStreamSource internally?

Let me see if I understand the proposal. There would be an informal convention that `IDataReaderEstimator<IMultiStreamSource, TReader>` and `IDataReader<IMultiStreamSource>` would also implement `IDataReaderEstimator<string, TReader>` and `IDataReader<string>`. Inside each we would be responsible for a uniform implementation. I'm not sure I like that very much, since it seems to invite considerable complexity and code duplication in ways that seem somewhat pointless, at least at first glance.

What I might prefer is that we have extension methods to `IDataReader<MSS>` and `IDataReaderEstimator<MSS,...>` to also have `Read(string)` and `Fit(string)`.

> I think this can be achieved by turning the `IMultiStreamSource` into a base class.

@Zruty0 , I believe you think this because you can't have implicit casts into an interface, but can into a class? This is true, but in order for a user to exploit this, they would have to somehow figure out or stumble upon the knowledge that `string` can be implicitly cast to an `IMultiStreamSource`, which will not be obvious. An extension method on top of `IDataReader<IMultiStreamSource>` and `IDataReaderEstimator<IMultiStreamSource, ...>` would be explicitly visible to a user... they hit `.` on a reader, they see a method `Read`, and one of the overloads (though an extension) accepts a `string, which is fairly obvious.

**However**, I do agree that `IMultiStreamSource` should probably be something based on an abstract class as opposed to an interface, though for different reasons.

**Comment by Zruty0** [comment]
Ok, so I am much more concerned with the `Read` methods than I am with interface design. 
Extension methods are fine with me for that purpose.

**Comment by shauheen** [comment]
@markusweimer is asking: "Also, can we make it accept a list of file names as well?"

**Comment by sfilipi** [comment]
resolved through PR #1281
