### ISSUE TITLE
Suggestion related to Working with Columns

### ISSUE THREAD

**Issue by ddobric** [dotnet/machinelearning#127]
Right now we use Column attribute to decorate how to read columns. Additionally we mark column with text "Label" to indicate that it is a label.

If label column is missing ore not correctly named we get: "InvalidOperationException: Column 'Label' not found"

Suggestion:
It might be better to use dedicated attributes like FeatureColumn and LabelColumn instead of freely written text. It is a statically typed and more .NET (C#) agnostic.

**Comment by sfilipi** [comment]
@ddobric your feedback is incorporated in the static api described in #474, #581 and the [cookbook](https://github.com/dotnet/machinelearning/commit/14c7a472579afa3ce98bad2e3495e4c0524471b9#diff-ecac29a5d9034d4eeb9cff7e6b439175).

Closing this since the discussion of the same topic in the other Issues is brader.
