### ISSUE TITLE
LocalEnvironment to stop being IDisposable

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1287]
The only reason we have `IHostEnvironment` as an `IDisposable` is because we clean up the temp files created using `CreateTempFile`. This functionality is not really very useful. We should remove the functionality, remove the `IDisposable` and fix all the `using` calls in the codebase (preferably to just `new MLContext`, if possible)

**Comment by TomFinley** [comment]
The implication is that anything that relies on it for temporary file creation and that requires must cease to do so. In order for us to do this, we must also remove temporary file creation from `IHostEnvironment`. (Also, regular file creation, though that is less urgent.) This I have found untangling this *relatively* easy to do, but there is one exception that is very troublesome because it explicitly relies on this behavior.

https://github.com/dotnet/machinelearning/blob/057c4b97bb4fab09b8f88db2300644660f46aa5d/src/Microsoft.ML.Data/EntryPoints/Cache.cs#L71-L73

That's bad, but I think there's a pretty easily solution. I think it is completely reasonable for someone asking for disk cache to provide a place *where* on the disk it should be stored. I think that will actually be an improvement -- certainly it is not an expectation that any "temporary" files will be many gigabytes or terabytes large (which is the only conceivable reason why anyone would use disk caching in the first place), so having some ability to configure *where* it is stored would I think be good. Or we provide access to the binary saver via entry-points and say that if someone wants that functionality they just have to do it themselves. This I think is fine, since entry-points were entry-points into ML.NET for *wrapping* code, not *user facing* code.

**Comment by eerhardt** [comment]
Yes, this is still relevant.

We still have these methods on `IHostEnvironment` that we need to remove:

https://github.com/dotnet/machinelearning/blob/0c62e30b4d9eabb60322b2a3e75bc90e20007889/src/Microsoft.ML.Core/Data/IHostEnvironment.cs#L55-L77

Even though it doesn't implement `IDisposable`, we can't have these methods on this interface.

**Comment by eerhardt** [comment]
Just an FYI - it looks like the only place in the product that is calling `Cache.CacheData` (which is the only place calling `CreateTempFile` pointed out by @TomFinley above) is coming from Entry-Points:

https://github.com/dotnet/machinelearning/blob/174de1a8dedb7bd72e1f43df6f07b9392c42c290/src/Microsoft.ML.Data/EntryPoints/InputBase.cs#L220-L224

This is good, because it means you can't get to this code from public APIs. And we can force the EntryPoints to call `Dispose` to clean up the temp files.
