### ISSUE TITLE
Binary fast tree doesn't return tree predictor in pigsty

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#1307]
https://github.com/dotnet/machinelearning/blob/a285f8d5db15cd8bf77f3c03763bce16642f902b/src/Microsoft.ML.FastTree/FastTreeStatic.cs#L93
It returns IPredictorWithFeatureWeights<float> which I found weird since I expect tree predictor from fast tree.
Regression and Multiclass returns FastTreeRegressionPredictor and FastTreeRankingPredictor which is right.

**Comment by Ivanidzo4ka** [comment]
@sfilipi  any chance you know why?

**Comment by sfilipi** [comment]
Because that's [what the trainer produces... ](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.FastTree/FastTreeClassification.cs#L169)

Similar for [LightGBM](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.LightGBM/LightGbmBinaryTrainer.cs#L135)

I think it is this way because of inheritance. Does it need to get re-worked?

**Comment by Ivanidzo4ka** [comment]
I don't see any reason to train Tree predictor and get weights object, but maybe I'm just silly. Let's hear our druid. 
@TomFinley can you share with us wisdom of centennial oaks?

**Comment by shauheen** [comment]
Poking the druid, @TomFinley

**Comment by wschin** [comment]
This was rediscovered in #2319. I will fix it.

**Comment by TomFinley** [comment]
I had missed that I was being poked. I have related a distinct but nonetheless related issue of #2378. @wschin brought this issue to my attention, I believe but am not certain that he will write there.
