### ISSUE TITLE
Printing training statistics by default discussion

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#1367]
Before the ML.Net Environment changes to Local environment, PR #923 during training of a pipeline, we would see output in the console. 

I am trying a long-ish to train model today; takes about 4 minutes, and I find the absence of any progress reporting unsettling. I am not sure whether things are working as expected, or working at all. 
I think this will be off-putting for the users.

**Comment by justinormont** [comment]
I very much like having the intermediate progress output. 

Specifically, this gives me:
* Percent done (or a way to guess)
* Indication of _any_ progress
* Knowledge of which component is taking time
* Warnings/errors insitu 

I would like us to go a bit further and have all trainable components output a more useful friendly (`ComponentX ##.#% complete`). This is only doable for components with known end points and not components which run until convergence. This also gets a bit nasty with threading.

**Comment by artidoro** [comment]
@Zruty0 since you authored the #923 PR, do you know if the change was intentional?

**Comment by Zruty0** [comment]
It was an intentional change to NOT write to console willy-nilly. 
Right now, ML.NET's `MLContext` doesn't write to console.

If you do `mlContext.Log += Console.WriteLine`, we will have the output back in the console, but in a non-colorized format that is more applicable for parsing than for human readability. 

I am not sure whether the colorized pretty console printing is something we want to have in the library at all.

**Comment by Zruty0** [comment]
@TomFinley do you have a comment?
