### ISSUE TITLE
Figure out a long term name for CpuMathNative

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/machinelearning#14]
_From @eerhardt on March 26th_

from
` - internal const string     NativePath = @"Microsoft.MachineLearning.CpuMathNative.dll"; `
to    
`+ internal const     string NativePath = "CpuMathNative";                  `                    

Glad this worked, and thanks for filing the CoreCLR issue. As far as I can tell   this should work on netcoreapp2.0 and desktop as well, but we should test   that since this codepath has undergone a few changes in 2.1. Also we may   consider adding something more specific to the name since we won't be able to rely on a fix for dotnet/coreclr#17150.

**Comment by danmosemsft** [comment]
@eerhardt is it still worth renaming this since it's going away long term? Perhaps we can close this

**Comment by eerhardt** [comment]
Since this issue was written, we've gotten more native assemblies in ML.NET:

* FactorizationMachineNative
* FastTreeNative
* LdaNative
* SymSgdNative

so really it isn't just about CpuMathNative.  It is about having unique native assembly names but we can't have "." in them because of the attached core CLR bug that was fixed in .NET Core 3.0 (but not in 2.1 or 2.2).

**Comment by danmosemsft** [comment]
@shauheen seems to me maybe these names are already reasonable

**Comment by abgoswam** [comment]
DRI RESPONSE: closing since names sound reasonable enough
