### ISSUE TITLE
How to access internals of transformer via dynamic pipeline?

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#1472]
#1015 
We quite easily can access internals of transform via OnFit delegate in static extensions.
But I don't see any easy way (one which doesn't include tons of casting) to get to internals if I use dynamic Api.

```
var est = new NormalizingEstimator(Env,new NormalizingEstimator.MinMaxColumn("float1"));
var transformer = est .Fit(validData);
```
I don't see any easy way to get offset and scale.
`(transformer.ColumnFunctions[0] as Microsoft.ML.Transforms.Normalizers.NormalizeTransform.AffineColumnFunction.Sng.ImplOne).Scale`

this is best I can come up with and I'm not sure it will work outside of my debug environment considering what pretty much everything is internal.

@TomFinley  @Zruty0  Do we care about dynamic pipelines?

**Comment by Zruty0** [comment]
@Ivanidzo4ka , it looks like you should swap 'dynamic' and 'static' in the above description

**Comment by Zruty0** [comment]
We want to expose the 'learned parameters' of trained transformers via the normal 'readonly properties' mechanism. This is already the case for things like SDCA predictor, FastTree etc. 

It is notably **not** the case for normalizers, but it's not by design: we want to expose the normalizer's learned parameters in someform or another, if we see how.
