### ISSUE TITLE
Simplify API: dataPipeline.Fit(data).Transform(data);

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#1522]
For the code on ["How do I look at the intermediate data?"](https://github.com/dotnet/machinelearning/blob/453eb57f0cd94d6412b1f8dee76c00c686e2e06e/docs/code/MlNetCookBook.md#how-do-i-look-at-the-intermediate-data) as explained in the CookBook, it looks weird to have to pass the same DataView object twice in the following code line:
(Scroll down a bit and you'll see)
```
// Fit our data pipeline and transform data with it.
var transformedData = dataPipeline.Fit(data).Transform(data);
```

That line of code initially looks like a ["Code smell"](https://en.wikipedia.org/wiki/Code_smell).. 

Since the DataView object is provided to the parent object (pipeline) through the `Fit(data)` method, could it be possible to get/use the DataView from the parent object without having to provide again the DataView object to the Transform(data) method? - Something like:

`var transformedData = pipeline.Fit(dataView).Transform();`

**Comment by Zruty0** [comment]
I don't think this is either feasible, or a good idea.

Essentially, we suggest here that every transformer (a 'model') retains a reference to the 'training data', so that the user can call a parameterless `Transform()` and get the transformed training data. 

The implications are:
- There will be no 'non-trainable' transformers. Even something as trivial as `CopyColumns("Foo", "Bar")` needs the 'training data' now.
- The save/load operation will stop being round-trippable. Either that, or the models will need to serialize their respective training data, which is an even worse idea.

In essence, the suggested change will bring us back to the `IDataTransform` idiom (which is simultaneously the data and the transformation), and we have learned a while ago that this is a source of many user errors and confusion.

**Comment by CESARDELATORRE** [comment]
Right, I understand then. 
Maybe splitting the line in two in the sample would make it easier to understand.
Instead of this: 
`var transformedData = dataPipeline.Fit(data).Transform(data);`

This:
```
var transformer = pipeline.Fit(dataView);
var transformedData = transformer.Transform(dataView);
```
Closing the issue, then. Thanks Pete! 👍
