### ISSUE TITLE
Build failed on Ubuntu 18.04

### ISSUE THREAD

**Issue by helloguo** [dotnet/machinelearning#1554]
Build failed on Ubuntu 18.04. The ML.NET was forked today 11/6/18. The error msg says tensorflow.redist is not able to be downloaded as shown below. Any guidance to solve it? Thank you.

![build-fail](https://user-images.githubusercontent.com/18431130/48096873-45c6c580-e1cd-11e8-9736-4ee6e355af0d.PNG)

**Comment by feiyun0112** [comment]
It caused by download timeout.

Google can not be accessed in my location, so i solve it follow these steps:

1. download the gz file using FQ
2. install & run nginx
3. copy the gz file to `/var/www/html`
4. change Microsoft.ML.TensorFlow.Redist.proj line 21 `Include="@(TensorFlowConfig->'http://localhost/libtensorflow-cpu-%(Identity)-x86_64-$(TensorFlowVersion)%(FileExtension)')" />`
5. build again

**Comment by helloguo** [comment]
Thank you.
