### ISSUE TITLE
Legacy API: Should we migrate its entry-points?

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#1565]
The plan is to deprecate then delete the legacy API. While most items in it are of questionable worth, the legacy API does contain some components that might be worth saving, and some we may have to save.

Consider this entry-point definition, in the legacy project.

https://github.com/dotnet/machinelearning/blob/7b2461cfdad150047dbbcbc163290a32e9f4d829/src/Microsoft.ML.Legacy/Runtime/EntryPoints/ModelOperations.cs#L81

As it is an entry-point, it was [duly published in NimbusML as we see here](https://github.com/Microsoft/NimbusML/blob/e1004720ec0c252ba87f02c190c33739d9c00f20/src/python/nimbusml/internal/entrypoints/models_ovamodelcombiner.py), and this internal entry-point definition actually [wound up being used here](https://github.com/Microsoft/NimbusML/blob/e1004720ec0c252ba87f02c190c33739d9c00f20/src/python/nimbusml/model_selection/cv.py#L474).

There are a couple questions we might want to ask. The legacy pipeline API was entry-point based, so anything that was part of a pipeline had to be an entry-point (I think). So were these entry-points defined in legacy *specifically* intended to be useful beyond legacy?

If we want to keep this entry-point, and others like it, we should have a migration plan somewhere, since legacy is to be deleted.

**Comment by sfilipi** [comment]
@asthana86 had plans to use the entry points. @asthana86 is that still the case?

**Comment by Zruty0** [comment]
@ganik , I suggest we make the necessary update to NimbusML to not rely on legacy namespace, and migrate out whatever entry points are needed for that

**Comment by shmoradims** [comment]
> @Zruty0 agreed. I ll check what entrypoints need to be migrated for NimbusML to work

@ganik could you please add the NimbusML issue here?

**Comment by sfilipi** [comment]
Assigning to @ganik based on the discussion.

**Comment by montebhoover** [comment]
From @yaeldekel 's findings:

Entrypoints required by NimbusML that need to be migrated out of ML.NET's ML.Legacy namespace:
- CVSplit, TrainTestSplit
- DataViewReference 
- FeatureCombiner
- ImportTextData
- ModelOperations.CombineModels
- ModelOperations.CombineTransformModels
- **OneVersusAllMacro** *
- **TrainTestMacro** *
- **CrossValidationMacro** *

Components that are not entrypoints but still require migration out of ML.Legacy:
- GraphRunner
- ExecuteGraphCommand
- JsonManifestUtils

Entrypoints that are *not* needed:
- CrossValidationBinaryMacro
- TrainTestBinaryMacro

*These three entrypoints will take more work than the rest because we need to modify their implementation to rely on non-deprecated components.  Yael has demonstrated it is possible to do this in ~half a day for each.

**Comment by glebuk** [comment]
@montebhoover Please assert that it is complete and then close.

**Comment by yaeldekel** [comment]
The issue was resolved in PR #1859.
