### ISSUE TITLE
Make non-essential members of Core and Data assembly internal

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1602]
#1519 made it possible to have members that are not public, but still accessible to other ML.NET assemblies. We now plan to use it to reduce the public surface of ML.NET assemblies substantially.

Namely, let's 'hide' the non-user-facing public members of `Microsoft.ML.Core` assembly

**Comment by TomFinley** [comment]
In the next few days before we "finalize" the v1.0 RC API surface, we might conceivably hide one or two more things in these assemblies, but the usefulness of "catch-all" issues like this are less useful than they were back in the days when we were hiding hundreds or even thousands of items in our public surface with each PR. For that reason it is probably appropriate to close this issue at this time, since:

1. the core work it was meant to do has been almost entirely done,

2. even if it wasn't the opportunity for grand sweeping changes to the API in terms of public surface restriction are limited in the next few days,

3. and whatever little remains or can be done should have more specific issues.
