### ISSUE TITLE
SCDA Summary Not Sorted

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#1652]
The `Summary()` for `SDCA` does not sort the output by the feature index. This makes it difficult to read. For reference, `OLS` does sort by the feature index and is easy to read.

Version: ML.NET 0.7 Release

Example `Summary()` output:
```
Linear Regression Predictor non-zero weights

(Bias)  -0.4338956
15      0.8659377
14      0.6250594
0       0.5953168
7       -0.5625336
6       -0.5331995
8       -0.5284117
5       -0.450398
9       -0.430093
13      0.3840194
1       0.3470894
4       -0.3077467
10      -0.2826627
12      0.1388556
3       -0.1202137
2       0.103458
11      -0.09171117
```

**Comment by TomFinley** [comment]
Hi @rogancarr , just to answer, this is sorted. You'll note that the feature coefficients are in decreasing order of magnitude. This is important and desirable -- in a model with perhaps millions of features (e.g., something dealing with natural language), knowing what words are, in some rude measure, "most important," is good information to describe first, *especially* since this is a summary and meant to be human interpretable. Indeed this feature was added deliberately by user request in the long distant past. (Years ago before open sourcing.) I would not welcome reverting the change to the situation we had prior to this.

**Comment by rogancarr** [comment]
Hi @TomFinley, thanks for the great explanation! I see your point here. How do you feel about overloading `Summary()` to take optional parameters? Or do you think it's best in this case for me to extract the parameters and pretty-print them myself?

**Comment by rogancarr** [comment]
I think pretty-printing is the way to go. Closing issue.
