### ISSUE TITLE
Will there be ML.NET support for ARM applications?

### ISSUE THREAD

**Issue by tauheedul** [dotnet/machinelearning#1662]
Build 0.7 introduced support for x86 applications.
Will ARM support also be included? 
Examples of usages are Always Connected Windows 10/Linux laptops running ARM processors

.NET Core supports ARM so the route to enable it should be possible

**Comment by TomFinley** [comment]
Hi @tauheedul , the plan last I heard was that we would offer ARM support (we need this for other reasons) but not as part of the targeted scenarios for v1.0. So eventually, but because we have something of a deadline I think it was scoped out. @asthana86 or @shauheen would know better than I about these plans though, and would have a more up to date understanding I think, than just a poor lowly dev like me. 😄 

There was one thing I was curious about though, there are two things we might want to use ML.NET for -- *training* machine learning models, and *predicting* using those already trained models. Would it suffice for whatever you had in mind if *predicting* worked on ARM, but training had to happen on an actual x86/x64? Or would training on ARM also be a scenario?

The reason I like to know these things is that, while we have native code dependencies for training (which is what makes running on ARM hard) since those are operations that heavily benefit from native code, *predicting* benefits less in most situations, and involves far less complex operations and mathematics. So doing prediction/scoring only would be far easier to bring to ARM somewhat quickly. But of course I'd like to understand whether that would even be beneficial to people.

**Comment by CESARDELATORRE** [comment]
@TomFinley - I'd support the second choice as the first step. For most scenarios in IoT and Mobile devices (based on ARM) just scoring/running a model is mostly needed, not needed to train a model on those small devices, usually.

@tauheedul - What's your feedback about it?

**Comment by tauheedul** [comment]
Hi @TomFinley @CESARDELATORRE . Thank you for the background information it is insightful.

I understand ARM processors don't have the kind of performance we get standard x64 processors,  what makes it ideal is they can generally last a lot longer in terms of battery life, so could deliver similar results (although a little slower)

If there are technical constraints that don't align with the planned road map, may I suggest the following...

At the very minimum ML.NET running on ARM should be able to perform Prediction operations as this is a quick win from an end user perspective. The user will not be concerned where the model was trained. It would show case ML.NET capabilities and attract further interest from the development community.

In the interim developers should be able train their models externally on the cloud or on a standard x86/x64 computer and target the output in their ML.NET ARM supported application 

In the future Training capabilities would be advantageous because modern ARM processors are making considerable gains and there are processors being developed that optimised for AI tasks.

**Comment by shmoradims** [comment]
@CESARDELATORRE @GalOshri @shauheen could you please discuss if we want to put "Scoring on ARM" on the roadmap?

**Comment by CESARDELATORRE** [comment]
I think it is very important especially/initially for scoring a model on ARM devices.

Just for scoring might be a smaller effort from our side that’s trying to have support for ARM for the whole ML.NET.

We need ARM for scoring models on IoT devices and for mobile devices running Xamarin apps on iOS or Android. All those workloads are important for .NET.

But training on ARM might not be so important, for now..

Cesar



________________________________
