### ISSUE TITLE
Float v.s float

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#1669]
In ML.NET codebase, one can see two different names for 32-bit float type. Recent PR uses `float` while [old places](https://github.com/dotnet/machinelearning/blob/e0906608ca0d37ad0c10ba647e83b45990afde43/src/Microsoft.ML.Sweeper/ISweeper.cs#L5) have `Float`. It'd be nice to have only one of the two styles.

**Comment by Ivanidzo4ka** [comment]
@wschin we are trying to get rid of `Float` in our code, and if you look into estimators PRs we almost always delete that `using Float = System.Single;` line and use `float` instead

**Comment by TomFinley** [comment]
Just some history, in the long vanished past we used to have two builds, a "double" and a "single" build. (This was in the days before `IDataView` where pipelines could accommodate either.) But, when we removed the compiler switch, it was beneficial to keep the declaration around: by doing so you only had a couple thousand lines changed, instead of tens of thousands of lines changed.

We've been opportunistically removing `Float` though, though in a very very piecemeal fashion. Doing it all at once though -- well, it might be a good idea, but that would be one heck of a PR to manage conflicts on. 😛

**Comment by Zruty0** [comment]
Yes, just recently I saw someone mass-renaming `Single` to `float`, and ending up with `Ldafloatbox` somewhere in comments :)

**Comment by glebuk** [comment]
Seems to be fixed already

**Comment by Ivanidzo4ka** [comment]
Not exactly finished.
https://github.com/dotnet/machinelearning/blob/a570da14a41f2870eb8f61d84496a58422398253/src/Microsoft.ML.StandardLearners/Optimizer/LineSearch.cs#L8
We have still plenty of places where we have `using Float = System.Single;` pattern.

In many places we clean it up via different unrelated PRs, but some code haven't been touch since we merge it from internal repo.

**Comment by sfilipi** [comment]
The action item on this PR is to remove

`using Float = System.Single` from all the files, and through the codebase, replace `Float`, with `float`.
