### ISSUE TITLE
Add a Filter for text-based columns

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#1763]
Afaik, the new filter APIs can target just numeric-based columns, but not text-based columns.
As of v0.8 we have: 
1) 
```
//FilterByColumn()

IDataView trainingDataView = mlContext.Data.FilterByColumn(baseTrainingDataView, "FareAmount", lowerBound: 1, upperBound: 150);
```

This is a very convenient filter, but for NUMERIC values. I’m currently using this for the sample code-snippet

2)
`FilterByKeyColumnFraction()`
Good for hashed values.

But if we want to filter by text-based columns, let's say I want to remove the rows where a text based column has no value (this might be doable when transforming to numeric values, then missing value is NaN and it will get filtered, but you need an additional not straightforward step) or to **remove specific rows when categorical values are equal to "some text"**, I think we cannot do that, yet.

**Comment by TomFinley** [comment]
This is fine, but I wonder if we can go even a step further. Data pipelines must be serializable, and prior to ML.NET being open sourced filters were part of data pipelines. Pursuant to #933, it is our position that filters should *not* be part of data pipelines any longer, hence why we see the old functionality of filters not being exposed as `IEstimator`/`ITransformer`, but instead just straight functions on `IDataView`, e.g.:

https://github.com/dotnet/machinelearning/blob/533e18647a77c31f8149ccf2618ccb2e354f8e62/src/Microsoft.ML.Data/DataLoadSave/DataOperations.cs#L57

The implication means that there is no longer any requirement for things to be serializable, which means we could actually probably simplify a lot of code by deleting practically all of the existing filters, and just replace them with some sort of `bool` evaluating delegate akin to a LINQ `.Where`. (We can't serialize delegates, but since we no longer care about that, that's fine.)

This means this code here:

https://github.com/dotnet/machinelearning/blob/533e18647a77c31f8149ccf2618ccb2e354f8e62/test/Microsoft.ML.Tests/RangeFilterTests.cs#L30

Could potentially just be:

```csharp
var data1 = ML.Data.KeepWhere(data, "Floats", (float v) => v < 2.8);
```

Your specific example (assuming that this is in some text column called `MyAwesomeText`), might be something akin to:

```csharp
var data1 = ML.Data.KeepWhere(data, "MyAwesomeText", (ReadOnlyMemory<char> v) => v == v.Length > 0);
```


Whether we want to have these existing methods as a convenience, or add the convenience you suggest, I don't really know.
