### ISSUE TITLE
MatrixFactorization cannot be found in the MLContext catalog

### ISSUE THREAD

**Issue by GalOshri** [dotnet/machinelearning#1770]
`MatrixFactorization` cannot be found in the MLContext catalog. MLContext.Recommendation is currently empty. 

This is with the 0.8.0-preview-27128-6 Microsoft.ML and Microsoft.ML.MatrixFactorization NuGets.

**Comment by sfilipi** [comment]
MatrixFactorization is not part of the  Microsoft.ML core nuget; and there are no Recommendation trainers on the core Microsoft.ML. As a consequence the RecommendationContext is an extension to the MLContext, and it lives in the Microsoft.ML.MatrixFactorization package. Since it is an extension, it needs to be a method; and therefore the correct way to use it, is:

```

var pipeline = mlContext.Recommendation().Trainers.MatrixFactorization(userColumnName, itemColumnName, labelColumnName,
                advancedSettings: s =>
                {
                    s.NumIterations = 3;
                    s.NumThreads = 1; // To eliminate randomness, # of threads must be 1.
                    s.K = 7;
                });
```
This behavior is documented in the [MatrixFactorization API, through the sample](https://github.com/dotnet/machinelearning/blob/481c37774afdbc6f8b1eab9c9f894c83f3ac984d/docs/samples/Microsoft.ML.Samples/Dynamic/MatrixFactorization.cs). 
Let me know if you have ideas about how to emphasize it further.

**Comment by GalOshri** [comment]
Got it, thanks! It might be a bit confusing that components that were added through other NuGets are accessed differently in `MLContext`. 

I know we had a discussion about making components discoverable in `MLContext` even if their NuGet isn't there (this idea was dismissed due to feasibility). Is there something we can do to at least ensure that once the right NuGets are added, the components are accessed in the same way? How would it look if I am accessing a trainer that comes from a separate NuGet but is in Regression (which does have other trainers in the core NuGet)?

**Comment by sfilipi** [comment]
Trainers from other packages will show in the respective context's Trainers list as soon as you add the package, if they are on the Microsoft.ML.Trainers namespace. If they are on other namespaces, you'd need to add the namespace.

**Comment by sfilipi** [comment]
Closing, since there is not actions to take.
