### ISSUE TITLE
Logging and Tracing in ML.NET

### ISSUE THREAD

**Issue by asthana86** [dotnet/machinelearning#1799]
In EntityFramework there exists a context log property which allows for logging SQL generated by dbcontext.

For MLContext is there a similar log property which allows for logging some of the diags currently printed to Console when using various transforms or learners? Additionally is there a way to control log location and verbosity? 

**_E.g.: When using Matrix Factorization:_** 
Sample: https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/MatrixFactorization_MovieRecommendation/MovieRecommendation/Program.cs

=============== Training the model ===============
iter   tr_rmse          obj
   0    0.0002   4.8456e+02
   1    0.0002   7.8940e+02
   2    0.0002   1.1160e+03
   3    0.0002   1.2787e+03
   4    0.0002   1.6045e+03
   5    0.0002   2.0909e+03
   6    0.0002   2.5788e+03
   7    0.0002   2.9040e+03
   8    0.0002   3.2300e+03
   9    0.0002   3.2758e+03
  10    0.0001   2.8742e+03
  11    0.0001   2.5185e+03
  12    0.0000   2.0396e+03
  13    0.0000   1.9213e+03
  14    0.0000   1.6839e+03
  15    0.0000   1.3291e+03
  16    0.0000   1.2107e+03
  17    0.0000   9.7367e+02
  18    0.0000   9.7325e+02
  19    0.0000   9.7242e+02
real tr_rmse = 0.0000

EF provides the following to users:

**Output directly to console:**
using (var context = new YourDbContext()) 
{ 
    context.Database.Log = Console.Write; 
     // rest of you code goes here... 
}

**_Log output to the trace window_**
using (var context = new YourDbContext()) 
{ 
    context.Database.Log = message => Trace.Write(message);
    // rest of you code goes here
}

**_Already have a logging framework in place_**
using Common.Logging;

public class SomeClass
{
    private static readonly ILog log = LogManager.GetCurrentClassLogger();

    public void SomeMethod()
    {
        context.Database.Log = message => log.Debug(message);
    }
}

Thanks.

**Comment by Zruty0** [comment]
1. `MLContext` object has the exact same `Log` delegate that can be used to capture ML.NET output. It is by default going nowhere.
2. The console output you showed in the issue comes directly from the `libmf` library. I am not sure whether we should try to intercept it and log through the same mechanism. If yes, it would warrant another issue.

**Comment by TomFinley** [comment]
Yeah re. `libmf`, we see [things like this](https://github.com/cjlin1/libmf/blob/53a91e7e8c88463e97acfbbafb7134a6030860b3/mf-train.cpp#L310) sprinkled throughout the codebase, but not too many -- maybe it would be a simple matter to have some sort of logging callback (the callback can write to `cout` by default, but otherwise it could be something passed in via pinvoke.)

Certainly @wschin would know best.

**Comment by wschin** [comment]
LIBMF prints out training progress to stdout by default. You can make it silent by specifying [this](https://github.com/dotnet/machinelearning/blob/481c37774afdbc6f8b1eab9c9f894c83f3ac984d/src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs#L160).

**Comment by TomFinley** [comment]
Cool thanks @wschin , but what do you think about having an option to pipe it somewhere else? The logs are valuable, but, console may not be the best place for them, or even accessible in some situations.

**Comment by codemzs** [comment]
As Pete mentioned, MLContext object has the exact same Log delegate that can be used to capture ML.NET output. It is by default going nowhere.
