### ISSUE TITLE
FastTree cannot solve a simple toy problem when using feature arrays

### ISSUE THREAD

**Issue by leblancdavid** [dotnet/machinelearning#1839]
I'm having a hard time understanding the API for doing basic machine learning. In our application, our feature vectors come in as basic arrays of floating point values. I create a simple toy problem to try to understand how the API works (using the samples as a guide) which uses the `FastTree` binary classifier. The training data is just 2 vectors <0, 0>:0, <1, 1>:1, which should be easily be able to fit a model to. However, when I run the evaluation I get 50% accuracy. Here is my sample code:

```
 class Program
    {
        public class FeatureData
        {
            [ColumnName("Label")]
            public bool Label { get; set; }

            [ColumnName("Features")]
            public float[] Features { get; set; }
        }

        static void Main(string[] args)
        {
            MLContext mlContext = new MLContext(seed: 0);

            var featuresTrainingData = new List<FeatureData>()
            {
                new FeatureData() { Features = new float[]{0.0f, 0.0f}, Label = false},
                new FeatureData() { Features = new float[]{1.0f, 1.0f}, Label = true}
            };

            var schemaDef = SchemaDefinition.Create(typeof(FeatureData));
            schemaDef["Features"].ColumnType = new VectorType(NumberType.R4, 2);

            var dataView = mlContext.CreateDataView(featuresTrainingData, schemaDef);

            //Train the model
            var pipeline = mlContext.BinaryClassification.Trainers.FastTree(featureColumn:"Features", labelColumn:"Label");
            var model = pipeline.Fit(dataView);

            //Evaluate
            var predictions = model.Transform(dataView);
            var metrics = mlContext.BinaryClassification.Evaluate(predictions, "Label");

            Console.WriteLine();
            Console.WriteLine("Model quality metrics evaluation");
            Console.WriteLine("--------------------------------");
            Console.WriteLine($"Accuracy: {metrics.Accuracy:P2}");
            Console.WriteLine($"Auc: {metrics.Auc:P2}");
            Console.WriteLine($"F1Score: {metrics.F1Score:P2}");
            Console.WriteLine("=============== End of model evaluation ===============");

        }
    }
```

What am I doing wrong here?

Thank you!

**Comment by Ivanidzo4ka** [comment]
Every algorithm have some knobs which let you tune it to get different models. This knobs have some default values, which we have to specify to cover most usual cases. Case where you have two data points is not are common one.

We have parameter minDatapointsInLeaves which specify how many data points you need to have in order to create leaf in tree.
By default that value is 10. And in case if you train on million examples it somewhat make sense, you don't want to have leaves for every case. So everything that has less than 10 datapoints wouldn't be considered as good candidate for a leaf.

Right now, we just build empty tree with no leaves, and this is why you get coin flip metrics.
If you change minDatapointsInLeaves  to 1, you will get proper tree which would give you 100% accuracy :)

**Comment by leblancdavid** [comment]
Boy I feel dumb now! That makes perfect sense thank you!
