### ISSUE TITLE
ColumnAttribute and TextLoader.Column and TextLoader.Arguments has header property

### ISSUE THREAD

**Issue by JRAlexander** [dotnet/machinelearning#1854]
From @PeterPann23:

"To me, this seems to all address the same problem on several different steps of designing the data, perhaps make ordinal an integer and not a string and define the data kind all on-top of the class and have the text loader override it when needed if needed. Most likely one would create a model class as in MVC that consumes a given "view" on the world. Perhaps my MVC experience has made me bias but this in my opinion overly complicated as is."

Fixes https://github.com/dotnet/docs/issues/9470

Opened an issue for this  as it's product feedback, and not a docs issue.

**Comment by wschin** [comment]
They are used for different purposes.
- ColumnAttribute: append extra information to C# class's fields so that ML.NET can convert them to ML.NET type
- TextLoader.Column: Specifies type information for text in file as a C#. Potentially this can be replaced by `Schema.Column`.
- TextLoader.Arguments: Sometime, the text file loaded may contain useful information such as column names. We use some of its flags to indicate this situation.
One solution is to provide a better documentation to describe their design goals.

**Comment by Zruty0** [comment]
`TextLoader.Column` can not be replaced with `Schema.Column`, because it holds the knowledge of where to look for the values in the text file.

However, we can (and should) re-work the `ColumnAttribute`: it should be clear that it is exclusively used for `TextLoader`, and doesn't share responsibilities with `ColumnName`, `VectorType` etc. The `ordinal` field is also a mistake, I think: we should make it into integer, and another version for a (min, max) pair, for vector columns.

**Comment by wschin** [comment]
`TextLoader.Column` and `Schema.Column` share some common attributes, so I was thinking of doing
```csharp
class TextLoader.Column
{
    Schema.Column column;
    // Extra fields to describe other information needed to locate this column in the loaded text file
}
```
I guess the major barrier will be re-implementing `TryParse` and `UnParse` for `Schema.Column`.
