### ISSUE TITLE
lib_lightgbm.dll is not getting loaded while running benchmarks on .NetFramework

### ISSUE THREAD

**Issue by Anipik** [dotnet/machinelearning#1945]
when we try to run this https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Benchmarks/Numeric/Ranking.cs#L50
and 
https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Benchmarks/Text/MultiClassClassification.cs#L47

on .netFramework, the benchmark is not able to load the lib_lightgbm.dll
```
Unexpected exception: Unable to load DLL 'lib_lightgbm': The specified module could not be found. (Exception from HRESULT: 0x8007007E), 'System.DllNotFoundException'
```

The benchmarks run properly on .NetCore

cc @danmosemsft @eerhardt @adamsitnik

**Comment by danmosemsft** [comment]
@TomFinley who is the owner of the lightgbm package who can look at this?

**Comment by codemzs** [comment]
Are you getting this error on other non windows platform? Based on very quick search seems like windows upgrade error. This dll comes from a nuget that is published by @guolinke

**Comment by Anipik** [comment]
I am getting this error in windows platform. I have not checked it for non-windows platform

**Comment by eerhardt** [comment]
@Anipik - can you try adding `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` to your .csproj? By default, .NET Framework apps run as 32-bit applications, and LightGBM doesn't support the x86 architecture. It only supports `win-x64`.

**Comment by Anipik** [comment]
@eerhardt I tried running it by specifying 64 bit  bit its still not able to find the lighgbm dll

**Comment by artemiusgreat** [comment]
TL.TR - another way to fix this issue is to install Microsoft Visual C++ Redistributable x64 
https://support.microsoft.com/en-ae/help/2977003/the-latest-supported-visual-c-downloads 

This is how it happened. 

1. Local computer works fine - Windows Pro x64 
2. OVH VPS server works fine - Windows Server 2016 x64 
3. Vultr VPS doesn't load LightGbm DLL - Windows Pro x64 

Tried various combinations of publishing, including Self-Contained deployment with configuration targeting Any CPU, x86, x64, but it didn't run on server #3. Only comparing list of installed programs I noticed that the only missing part on server #3 is MS Visual C++ Redistributable x64. I think I have this update on local computer because I have VS 2019 installed, server #2 is a Server Edition, so probably has this update by default, but server #3 was a custom installation of Windows Pro and it was missing it.
