### ISSUE TITLE
ArgumentAttribute is inaccessible due to its protection level from NimbusML

### ISSUE THREAD

**Issue by ganik** [dotnet/machinelearning#1958]
ML.Runtime.CommandLine.ArgumentAttribute is inaccessible anymore from NimbusML. 
Please advise how to proceed

thx

**Comment by TomFinley** [comment]
Code like this will not be part of our public surface area for v1, and in the case of `ArgumentAttribute` specifically, possibly not ever.

The most obvious way to solve the problem of this or any internal component that we don't want to publish as part of our stable API, is that we *instead* publish an marked unstable Nuget with Microsoft.ML (not the Microsoft.ML nuget), which exposes this component through that, and Nimbus ML or any similar code consume that instead. (It would of course have to be a wrapped version in the case of this class, but my understanding here is that you shouldn't be using `ArgumentAttribute` anyway, since in principle NimbusML should be working through the entry-point layer *anyway*.) My feedback on appropriate strategy will almost certainly be the same for all future requests.

If you wanted more specific advice feel free to describe what your problem is.

**Comment by TomFinley** [comment]
Hi @shmoradims sorry just saw this.

Yes, and I see you solved it by making everything public. However in an ideal world, it would be best if it did not do things this way, since as argued above I would say that the current code is perhaps not in the best state. However, I agree that fixing it is not a priority.
