### ISSUE TITLE
MetaMulticlassTrainer throws an exception when used in an estimator chain

### ISSUE THREAD

**Issue by daholste** [dotnet/machinelearning#1969]
### Issue

Setup code:
```
            // load data from disk
            var textLoader = new TextLoader(mlContext, new TextLoader.Arguments()
                {
                    Separator = ",",
                    HasHeader = true,
                    Column = new[]
                        {
                            new TextLoader.Column("Label", DataKind.R4, 0),
                            new TextLoader.Column("Features", DataKind.R4, 1, 784),
                        }
                });
```

Code that succeeds:
```
            var apTrainer = mlContext.BinaryClassification.Trainers.AveragedPerceptron();
            var trainer = mlContext.MulticlassClassification.Trainers.OneVersusAll(apTrainer);
            var model1 = trainer.Fit(testData);
```

Code for a dummy estimator chain that fails:
```
            IEstimator<ITransformer> pipeline = new EstimatorChain<ITransformer>();
            pipeline = pipeline.Append(trainer);
            var model2 = pipeline.Fit(trainData);
```

This fails b/c of 
```
LabelColumn = new SchemaShape.Column(labelColumn, SchemaShape.Column.VectorKind.Scalar, NumberType.U4, true);
```
in the MetaMulticlassTrainer class, which expects label column to be U4, not R4.

If I try to fix by changing the data type of Label column to U4, the code that used to succeed fails with the exception:
```
System.ArgumentOutOfRangeException: 'Training label column 'Label' type is not valid for multi-class: U4. Type must be R4 or R8.'
```
in TrainerUtils.CheckMultiClassLabel

**Comment by yaeldekel** [comment]
Hi @daholste , thank you for reporting this issue.
All the multi-class trainers should be able to handle both R4/R8 labels, and key type labels, which is a type used for representing class IDs.

The underlying values of a key type are of type U4, however, this type is not identical to the numeric U4 type, which is the type you get by changing the TextLoader column definition to DataKind.U4.

So there are two issues here: 
1. When you change the data type of the Label column to U4, the correct behavior is to fail, however the exception message is a bit misleading, since it should say that the expected types are key, R4 or R8.
2. With the original definition of the Label column as type R4, the trainer should succeed both when run independently, and inside an estimator chain. 

As a workaround until the second issue is fixed, you can add a ValueToKeyMappingEstimator (applied to the Label column) to your estimator chain right before the OVA estimator. This will convert the R4 Label column to a key type.

**Comment by daholste** [comment]
Any chance you would be able to prioritize this fix to ship in your next release?

**Comment by codemzs** [comment]
this seems to have been fixed already. @daholste if this is still an issue please reopen.
