### ISSUE TITLE
Feature Contribution Calculation Top/Bottom arguments are confusing

### ISSUE THREAD

**Issue by glebuk** [dotnet/machinelearning#2016]
### Issue
The current API for Feature Contribution are confusing.  They have the following parameters:
` FeatureContributionCalculation(... int top = 10, int bottom = 10..);`
those arg names are confusing.  From naming it is unclear if bottom means max negative or min abs() contribution.  
Let's rename them params to `topPositive and topNegative`

**Comment by Zruty0** [comment]
Would it be also confusing if the 'top negative' values were, in fact, positive? :)

Also, `topNegative` is itself not super clear: Think of a 'very high' negative number.

**Comment by rogancarr** [comment]
I agree with both sentiments, however, the one clear piece of feedback that we've gotten since porting `FCC` into `ML.NET` is that the names `top` and `bottom` are confusing. People tend to think that these are the "Most important" and "Least Important", respectively.

I'd prefer to rename them to something that conveys that they are the "largest-magnitude positive contributions" and "largest-magnitude negative contributions".
