### ISSUE TITLE
TextFeaturizingEstimator shouldn't use Argument class as main way of setting itself.

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2026]
https://github.com/dotnet/machinelearning/blob/5c00980abeae594161d0b9ee748d7d0b959962b5/src/Microsoft.ML.Transforms/Text/TextFeaturizingEstimator.cs#L141

Currently if I want to play with Word extractor and Char extractor I need to do that via 
https://github.com/dotnet/machinelearning/blob/5c00980abeae594161d0b9ee748d7d0b959962b5/src/Microsoft.ML.Transforms/Text/TextFeaturizingEstimator.cs#L497

which stops me from hiding IDataTransform interface.
We should have proper way to set it up via Setting object.

Related to https://github.com/dotnet/machinelearning/issues/1995

**Comment by TomFinley** [comment]
Yes, we should. Though, that `Create` mostly exists for dependency injection via component factories, entry-points, and whatnot. So that can totally be `private`. We also can keep the associated fields on the settings object internal, so we can add a way to configure them via estimators (as described in the comments) elsewhere, I think? What do you think? Good, bad?

**Comment by artidoro** [comment]
@Ivanidzo4ka after #2394, it seems that this issue has been resolved. If so I will close it.
