### ISSUE TITLE
K-means clustering cannot currently be used in experiments

### ISSUE THREAD

**Issue by GalOshri** [dotnet/machinelearning#205]
[K-means clustering](https://github.com/dotnet/machinelearning/tree/86f5ee663611f6c97ddb87be1150601018d74b4b/src/Microsoft.ML.KMeansClustering) is already available as a learner in ML.NET, but it is not exposed in the APIs and cannot be used in `LearningPipeline`. 

The entry point needs to be added to the C# APIs (along with other necessary components like the clustering evaluator).

**Comment by codemzs** [comment]
The entry point is already in the API and so is the evaluator. @yaeldekel has a PR out that references kmeans dll in test project do that code gen picks it up. The issue here is, I think, clusterer scorer is returning an empty IDataView from the limited debugging that I did last week but I could be wrong.

**Comment by Ivanidzo4ka** [comment]
It works, and we have example for that. So I'm closing this issue.
