### ISSUE TITLE
Removal of IHostEnvironment.ConcurrencyFactor and replace with ... ?

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#2051]
Consider this property

https://github.com/dotnet/machinelearning/blob/e2f7075782764c9dab8f0a04013aaf8b9921d984/src/Microsoft.ML.Core/Data/IHostEnvironment.cs#L43

set for example via this `conc` parameter here:

https://github.com/dotnet/machinelearning/blob/e2f7075782764c9dab8f0a04013aaf8b9921d984/src/Microsoft.ML.Data/MLContext.cs#L76

That we should have some sort of indication hinting of degree of desired parallelism might have seemed useful at one point, but the practical reality has more closely resembled this: components where parallelism matters for performance or results invariably wind up having their own independent settings *anyway*, to such a degree even that the `IHostEnvironment.ConcurrencyFactory` property is for the most part totally ignored -- e.g., people set `conc = 1` thinking this will give them deterministic results, but of course things like SDCA and LR have separate multithreading behavior, which under default settings will not give deterministic results unless it is set.

As an integer property, and as originally intended, this property is, i'd claim, a failure, since everywhere it *could* matter we wind up inevitably ignoring and overriding its behavior anyway, and where we don't it's only because that is a situation where such control doesn't really matter.

We ought at least to remove this, I think. This must be done prior to v1.

Whether post v1 we want to replace it with *anything* is another matter. Clearly at least for *test* purposes we want to have something to ensure consistent deterministic results, but is this really a user concern? (Definitely in other ML frameworks it is not a guarantee at all, so the idea of providing it and making it some sort of global configuration option seems questionable.)

/cc @stephentoub

**Comment by justinormont** [comment]
Why not slowly move the components to listen to this value instead of removing it?

I haven't used this for the want of perfectly deterministic results (in fact on the commandline I often set `seed=%RANDOM%`). Though assuming I am thinking of the right thing, I use it merely for controlling the number of cores & related memory usage. This helps when you're running multiple ML jobs in parallel and prefer each job doesn't take the full resources of the machine (eg. sweeping). 

Historically, the commandline has a nice comment to explain the slightly ineffective nature of `n=` parameter:
https://github.com/dotnet/machinelearning/blob/312f9e4c71953bee701ea2a63be3cb4d2d276d20/src/Microsoft.ML.Data/Commands/DataCommand.cs#L49-L54

There was another parameter `useThreads=` at the command-line (for some components, like CV) which also controlled parallelism; some like CV have both parameters. I'm unsure why the duplication or how they act differently.

It seems having a singular place for a user to set this would be valuable instead of having to know each component.

**Comment by justinormont** [comment]
NimbusML is looking to also expose similar functionality to the user user in this PR: 
https://github.com/Microsoft/NimbusML/pull/86/

Since NimbusML talks mostly though EntryPoints (and not the Estimator API), they should be unaffected though that depends if only the Estimator `MLContext` `conc` parameter is removed, or if the concept in general is removed from ML.NET.

cc: @zyw400

**Comment by TomFinley** [comment]
> Why not slowly move the components to listen to this value instead of removing it?

Because that's what we did about three or four years ago, immediately found out it was a bad idea in most cases, and over the intervening years found out it was a bad idea or at best irrelevant in nearly all cases, to the point where its applicability is now limited. This as described in the original text of this issue.

The CV example you give is a fine one. Let's imagine a user set the value to, say, 4. What does that mean? Does that mean they're fine with 4 trainings being run concurrently, with each trainer using 4 threads, the pipelines being run concurrently in cursorsets of size 4, and that was somehow the "right" value? Of course not -- that would be silly. Rather, what *usually* makes sense is that if you have a multithreaded trainer (e.g., FastTree) you give *that* as many threads as you have cores, but limit your CV concurrency to 1. Or, in the case where you have a trainer that benefits less (or not at all) from multithreading, you do parallel training of CV... or maybe there are concerns around the amount you can cache in which case you wanted to do it, etc. etc.

So, just to be clear, having a discussion about whether this is "useful" is unlikely to be a productive discussion. We know the answer to that from direct, practical, real experience spanning years (and which probably should have in retrospect been obvious with just a small amount of thought). The issue is more to track its inevitable removal. But if the discussion point is, "hey, let's leave it as it is since it's just fine," that's not really the lesson here.

**Comment by artidoro** [comment]
I agree that the current way of presenting `ConcurrencyFactor` is not very helpful and can lead to confusion. I think we should do as the issue suggests and remove the property from `IHostEnvironment` and implementing classes.

I do however think that in future, it would be useful to think about an alternative for making the entire pipeline deterministic. I think it should be a boolean flag in `MLContext`. This would be very helpful for debugging and testing.

In the meantime I am working on removing the property from `IHostEnvironment`.
