### ISSUE TITLE
Add static APIs to a new nuget package

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#2072]
In #1930 we introduced new static assemblies. Yeah! But then we forgot to add the new assemblies to any nuget package. Whoops. Which means they're effectively unshipped.

The ultimate solution should be that there are separate nugets for the static API. However, until that happens and we decide what shape those nugets would take, for the sake of the v0.9 we should maintain the status quo, which was that the new projects introduced in #1930 are shipped with their old assemblies.

/cc @eerhardt @shauheen

**Comment by TomFinley** [comment]
Actually, no we can't do that, because #1930 put *all* the static extensions into a single assembly, no matter what, so you can't use *any* of the static API without doing everything. This is quite altogether wrong, but complicates the story. We would need to ship a nuget temporarily, which is too bitter of a pill. So maybe we just don't ship static API for v0.9. I don't see a way to include it under the current circumstances.

**Comment by eerhardt** [comment]
@TomFinley - IMO it doesn't make sense to do the work to split the static API into a separate assembly, but then keep that same assembly in the core `Microsoft.ML` NuGet package.

Can we just create a new NuGet package named `Microsoft.ML.StaticPipe` (the same name as the assembly) instead? It isn't that much work (see below). Also, if we decide to change the static pipe packages later - it wouldn't affect anyone who uses the core `Microsoft.ML` nuget. Whereas, if we leave it in `Microsoft.ML`, changing it later could affect any of our customers, since they all use that package.

1. Create a new folder `Microsoft.ML.StaticPipe` under https://github.com/dotnet/machinelearning/tree/master/pkg
2. Create 2 files basically copied from something like https://github.com/dotnet/machinelearning/tree/master/pkg/Microsoft.ML.Onnx
    1. `Microsoft.ML.StaticPipe\Microsoft.ML.StaticPipe.nupkg`
    2. `Microsoft.ML.StaticPipe\Microsoft.ML.StaticPipe.symbols.nupkg`
3. Edit the `Microsoft.ML.StaticPipe.nupkg` file as necessary.
4. Add `<IncludeInPackage>Microsoft.ML.StaticPipe</IncludeInPackage>` to https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.StaticPipe/Microsoft.ML.StaticPipe.csproj

**Comment by TomFinley** [comment]
Hmmm, all right Eric, let's do that.
