### ISSUE TITLE
Loading of same model for tensorflow throw exception

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2156]
just run in two different threads:
`var loadModelSchema = TensorFlowUtils.GetModelSchema(mlContext, modelLocation);`
it will throw exception.

**Comment by zeahmed** [comment]
I will create a test and disable it to show that its a known issue. I will report it as bug in [TensorFlow](https://github.com/tensorflow/tensorflow) repo.

**Comment by zeahmed** [comment]
OK, I found out the root cause of the issue. There are `NoOp` operators in TF models. When querying the model for the their output datatype, the API gives different values each time as shown in table below.

The `TensorFlowUtils.GetModelSchema` method filters all datatypes that are not supported in ML.Net.
https://github.com/dotnet/machinelearning/blob/cabf55b543129e8962ba716e8e22c72ac08773e3/src/Microsoft.ML.TensorFlow/TensorFlow/TensorflowUtils.cs#L144

However, when querying (several times) output datatype for `NoOP` operator, it sometimes gives valid value such as `Float` as shown in table below. Upon calling `GetTensorShape` on `NoOP` operator crashes tensorflow runtime. It seems like this is the major cause of occasional failure of TensorFlow tests.


| No. | Op Name | OpType | DataType |
|-----|------------|----------|-----------|
| 1 |gradients/hinge_loss/value_grad/tuple/group_deps | NoOp | 1010855257 |
| 2 |gradients/hinge_loss/value_grad/tuple/group_deps | NoOp | Unknown |
| 3 |gradients/hinge_loss/value_grad/tuple/group_deps | NoOp | Float |

The solution is to specifically check for `NoOp` operator in the code and do not `GetTensorShape` method in this case.

**Comment by Ivanidzo4ka** [comment]
Thank you for investigation. Did we communicate this issue to tensor flow team? Or it's a expected behavior?

**Comment by zeahmed** [comment]
I will communicate. This is not expected I believe. I will have to write code directly using the C-API instead of using TensorflowSharp.

**Comment by zeahmed** [comment]
I think there is no need to report this as API design looks good i.e.
First call `TF_OperationNumOutputs(TF_Operation *oper)`  if return value is greater than `0` then call `TF_OperationOutputType(TF_Output output)`.

If `TF_OperationOutputType(TF_Output output)` is called for nodes that have zero outputs then its value is not deterministic.

This is exactly what has been implemented in PR #2173.
