### ISSUE TITLE
Lockdown Microsoft.ML.Onnx public surface

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#2273]
We ought to internalize as much of that assembly to those things we want to be public, and finalize its public API. This may be completed already; the public surface area I hope should just be the extension methods to export.

**Comment by Ivanidzo4ka** [comment]
Actually question to @glebuk  and @shauheen.  Not related to lockdown, but I can't find better place.

https://github.com/dotnet/machinelearning/issues/2463 issue like this shows how unready model to onnx converter is. Do we have any commitment regarding Onnx converter in 1.0? Can we make this nuget "experimental"? Can we hide it completely?

**Comment by Ivanidzo4ka** [comment]
One more thing, can we rename Project and Nuget (if we want them to be public) to OnnxConverter or ConverterToOnnx? Just Onnx is confusing.

**Comment by codemzs** [comment]
@TomFinley My observation in this library is that all(400+) but two public API is coming from auto-generated C# to Protobuff OnnxML.cs file. There are things in this file that we can make internal and then there are things we cannot since they extend standard public interfaces. Then there is the question if we should modify an auto-generated file. Thoughts?

**Comment by codemzs** [comment]
After speaking to @TomFinley and others it was decided we change the public API for ONNX converter to write onnx model to a stream instead of returning ModelProto object. This will allow us to internalize everything in OnnxML.cs.
