### ISSUE TITLE
Make entrypoints inside Microsoft.ML.Transforms project internal

### ISSUE THREAD

**Issue by shmoradims** [dotnet/machinelearning#2288]
We have 20+ entrypoints classes inside Microsoft.ML.Transforms like [this](https://github.com/dotnet/machinelearning/blob/a570da14a41f2870eb8f61d84496a58422398253/src/Microsoft.ML.Transforms/NAHandling.cs#L14) one. I think they should be made internal because the end-user would use the MLContext extensions instead, not these entrypoints. Also, the entrypoints documentation doesn't get rendered properly because the TlcModule.EntryPoint annotation is not understood by docs.microsoft.com (example: #1725)

Thoughts?

/cc @TomFinley @sfilipi @eerhardt

**Comment by TomFinley** [comment]
Thank you for taking the initiative on this @shmoradims !

This I agree with... indeed I just stumbled upon this issue, I do much of the hiding of entrypoints in #2300. (Where I also make it so that non-public methods can still be visible in the entry-point catalog, since that was not the case previously. Specifically, the commit in that PR labeled, "Internalize common outputs of entry-points and deal with resulting fallout.")

But I surely did not get everything, since I was not trying to solve this issue broadly, but merely those entry-points that publish very specific types that we do not want part of our public API surface. A more thorough review where we review *every* method decorated with `TlcModule.EntryPoint`, and make sure that it is in an `internal` class, or else if the class must be public for other reasons (e.g., some trainers publish their entry-points as a static method on the class itself, which is fine) then the method itself should be `internal`.

Nonetheless, possibly my approach in #2300 may prove useful as a guide for how someone could hypothetically continue that work, since I agree we must do it in a more comprehensive way. Probably after my PR goes in though, since otherwise we'd be stepping on each other's toes. 😄 

I will make this part of Project 13, since it deals with getting the public API in good shape.

**Comment by shmoradims** [comment]
Thanks @TomFinley @eerhardt for you input. I'll have a PR for it after Tom merges #2300.

**Comment by TomFinley** [comment]
@shmoradims it is now merged, thank you.
