### ISSUE TITLE
Prediction function always returns the same value for regression models.

### ISSUE THREAD

**Issue by Dylan-Osborne** [dotnet/machinelearning#2397]
### System information

- **OS version/distro**: Windows 10 64-bit
- **.NET Version (eg., dotnet --info)**: .NET Core 2.1

### Issue

- **What did you do?**
I created a program that is meant to predict the likelihood of a device being on at a given time.
- **What happened?**
The prediction function always returns the same value e.g. 0 or 1.
If the regression trainer is changed, the value that is returned by the prediction function changes to a different value. The value is always the same for each different trainer (e.g. Regression.Trainers.FastTree may always return 0 and another trainer will always return 1).
- **What did you expect?**
I expected the prediction function for to return different values representing the probability of the device being on.

**Comment by Ivanidzo4ka** [comment]
```
   //Create the pipeline and add the "Device_Active" field from InputData as the "Label"
                var pipeline = mlContext.Transforms.CopyColumns("Device_Active", "Label")
                    //Hash Date_Time
                    .Append(mlContext.Transforms.Categorical.OneHotEncoding("Date_Time"))
                    //Add Features, Date_Time in this case.
                    .Append(mlContext.Transforms.Concatenate("Features", "Date_Time"))
                    //Add a relevent trainer to the end of the pipeline.
                    .Append(mlContext.Regression.Trainers.FastTree());
```
I expect what prediction function works fine. It's just pipeline and model itself doesn't make much sense for me. So you have file with two fields. one is DateTime and one is float label. You apply onehotencoding to datetime -> this force pipeline to go through your data and create list of all unique values. After that we create array with size of all unique values, and fill it with zero, and put 1 into position of current value in unique values list.

That gives you some feature vector, but it doesn't have any dimensionality in it. It just vector of categories. Any regression learner probably just learns distribution of  your labels and predict most encountered one. Also if you predict on data you haven't use for training, one hot encoding will produce array of all zeros for such case (since we never meet that value in training data, we don't know where to map it) so you basically fit array of empty features to model, so it produce same result all the time.

Try to break your data into more reasonable feature set. [https://datascience.stackexchange.com/questions/2368/machine-learning-features-engineering-from-date-time-data](can be a good example) But in general I doubt you get good model out of one data stamp. 
Also is your case really regression or you just try to do binary classification, or it's anomaly detection? Because if later, you probably should try anomaly detection models instead of regression.
