### ISSUE TITLE
Dependency Error when using Ordinary Least Squares Regressor

### ISSUE THREAD

**Issue by jwood803** [dotnet/machinelearning#241]
### System information

```
Product Information:
 Version:            2.1.201
 Commit SHA-1 hash:  7932dc6179

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.201\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```

### Issue
- **What did you do?**
Created a simple ML.NET Console project with the following code:
    ```
    var pipeline = new LearningPipeline();

    var splitter = new TrainTestDatasetSplitter() { Fraction = 0.7f };

    pipeline.Add(new TextLoader<SalaryData>("SalaryData.csv", useHeader: true, separator: ","));
    pipeline.Add(new ColumnConcatenator("Features", "YearsExperience"));
    pipeline.Add(new OrdinaryLeastSquaresRegressor());

    pipeline.Train<SalaryData, SalaryPrediction>();
    ```

- **What happened?**
When calling `Train`, I'm getting the error `The MKL library (Microsoft.ML.MklImports.dll) or one of its dependencies is missing.` After some searching, I couldn't find where I can get a reference to it to include in the project.

- **What did you expect?**
Expected no errors, or a way to include the missing dependency.

If anything else is needed, just let me know. Thanks!

**Comment by Ivanidzo4ka** [comment]
https://github.com/dotnet/machinelearning/blob/5d368b801fac6dfa8f0200d777192f038004d514/src/Microsoft.ML.StandardLearners/Standard/OlsLinearRegression.cs#L360

This is dependency on MKL library which we use internally, but currently it's unclear how to consume it because of legal and infrastructure issues.

Current options are:
1) find way to add MKL as dependency
2) rewrite LAPACKE_dpptrf LAPACKE_dpptrs LAPACKE_dpptri in CpuMathNative
3) disable learner (on entry point level or just remove it from repo)

@GalOshri  @glebuk @shauheen
