### ISSUE TITLE
BoostrapSample not in Data catalog

### ISSUE THREAD

**Issue by nsulikowski** [dotnet/machinelearning#2430]
mlcontext.Data.BoostrapSample does not exists (from your samples)

**Comment by Ivanidzo4ka** [comment]
We do release once in a month. We choose to make all changes in our master, and once in a month we create release branch and produce official Nugets out of it. Which leads to situation in which we made breaking changes in our API (and in version 0.* we make them a lot), and our actual API in master branch and in release nuget are completely different.

You observe exactly such case. You have two options:

- Use samples from this repo: https://github.com/dotnet/machinelearning-samples They got updated with each release and not influenced by our development.

- Use daily Nugets, they contain latest bits from master, and we make sure our samples in this repository can be compiled. Instruction how to use Daily Nuget https://github.com/dotnet/machinelearning#installation is on the button of that section.

Starting from 1.0 release I expect situation to change.

**Comment by TomFinley** [comment]
Just to provide more specific information. In this specific case, the specific PR was #2387 by @rogancarr, which was merged a *bit* under eight hours before you filed this issue -- which is to say, it is not going to be in our v0.10 which was based on `master` as of a week ago.

> Starting from 1.0 release I expect situation to change.

I wouldn't say that. What will happen post v1 though is, we won't make breaking changes to the API (which is why we're in this mad rush right now). So stuff that's there will remain there, with (roughly) the same behavior. But *not* adding new things to the project is definitely not a goal of v1. 😄 That would mean the project is dead. The situation where there's something in master that didn't make it to release is the norm in most active projects, including I hope this one.

**Comment by rogancarr** [comment]
@nsulikowski Glad you find this feature useful! It will be in the release nugets in v0.11 on March 5th. Until then, you can find them in the dailies, as @Ivanidzo4ka has pointed out.

Also, stay tuned for all the rest of our `IDataView` => `IDataView` operations: `Cache`, `Shuffle`, `FilterByColumns` (and relatives), `FilterByMissingValues`, 'Skip`, `Take`, etc. These will all be in the dailies in the next 48 hours or so.
