### ISSUE TITLE
NimbusML's dot_export_pipeline for c#

### ISSUE THREAD

**Issue by nsulikowski** [dotnet/machinelearning#2433]
How can I access the list of estimators inside a pipeline?
I can see it as _estimators in the "Non-Public" area of the Locals window when I debug.
I'm trying to display the pipeline graphically (from c#) similar to the way NimbusML does

from nimbusml.utils.exports import dot_export_pipeline
dot_vis = dot_export_pipeline(pipeline, stream)
print(dot_vis)

I'm stuck at how to navigate the pipeline.

**Comment by Ivanidzo4ka** [comment]
Any `EstimatorChain` is `IEnumerable<IEstimator>` so you can iterate over them.
I'm a bit struggling to understand what exactly you mean (probably because I have limited experience with Nimbus). Can you provide code snippet of what you doing and what you is your expected result?

**Comment by nsulikowski** [comment]
are you sure?
i pressed f12 to see the definition and i dont see ienumerable...

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by Ivanidzo4ka** [comment]
My bad I was thinking about TransformerChain which is `IEnumarable<ITransformer>` and I expect it to be same for EstimatorChain.

@TomFinley  any chance you aware why @Zruty0  implemented TransformerChain as IEnumerable but didn't do that for EstimatorChain? Does it sound like API flaw for you?

**Comment by TomFinley** [comment]
Maybe, except, I can see a practical reason why one might want to iterate over `ITransformer`, I don't see a reason why one would want to iterate over `IEstimator`. 

Much of the work on this predates us abandoning our old mechanism of `IDataTransform` in favor of the new API #581 -- which uses much of the same code, just very different interfaces. So NimbusML does not use estimators at all at any level I believe -- it can't, since it works via entry-points, and entry-points no nothing about estimators/transformers yet.

There's also a question I have about this. In our world, models are transformers... that is, they are the *result* of fitting an estimator, you don't get estimators out of them. (E.g., `IEstimator` produces `ITransformer`, but you'll note `ITransformer` does not produce `IEstimator`.)

I am also not a Nimbus expert, but what that function looks like is it takes a model and attempts to do a "code export" of the model... e.g., if you have a linear model, it might write out some easily cut/pastable code that performs that evaluation. It seems to be working via our `ICanSaveAsCode` interface, which has nothing to do with estimators. So I am fairly certain this doesn't do what we think it does.

But someone actually on Nimbus project might be able to provide better answers than this.

**Comment by Zruty0** [comment]
Hey, someone summoned me! :)

Actually, I think it was my omission: I should've made the estimator chain an enumerable. 
The other thing that I think did not realize its potential is the fact that the estimator and transformer chains are generic on the last estimator/transformer. I think just `class EstimatorChain: IEstimator<ITransformer>` would work just fine.

In documentation examples I struggle to remember a single case where we substantially utilized `LastTransformer` / `LastEstimator`.

**Comment by harishsk** [comment]
@nsulikowski Please reopen the issue if your question has not been answered.
