### ISSUE TITLE
Question about import strategy

### ISSUE THREAD

**Issue by dotChris90** [dotnet/machinelearning#244]
Hello, 

in many posts, chats and issues I can read that there will be many importer / data loader come. 
My question now are the following : 

- will every loader / importer implement the same interface?
- will there be a small documentation explain this interface so we other have a chance to bring more importer to ML.NET?
- can the importer / data loader be used outside the pipe objects? so maybe in ACCORD.NET or other libraries? 

I really hope to get a better understanding for the import process. 
If they all implement the same interface - I will close issue https://github.com/dotnet/machinelearning/issues/138. At this time I did not see the interfaces like IDataView, ISaveData, ILoadData (I forgot the true names but I saw interfaces which gave me the thinking - okay thats a general interface I was looking for). 

thanks for your time. And I hope ML.NET will become giant and popular framework - it was the biggest suprise  to me this year after Blazor. :D

**Comment by TomFinley** [comment]
Hi @dotChris90 ! Sorry somehow I think this got missed.

For the first question: Every loader implements `IDataLoader`. A loader is expected to be instantiated over streams. (Usually originating from a file, more rarely from Azure blobs, and still more rarely still from some other source.) A loader might be considered a type of "importer" I suppose, but imported sources of data needn't be a loader. (For example, a SQL table or view would *not* be a loader, but it could be phrased as an `IDataView`.) Right now in this new API, the only loader accessible is the text loader, but we're working on figuring out how to provide more.

For the second question: We should migrate the documentation including the tutorials on how to write components (including loaders), it is true. I however would probably prioritize transforms over loaders, at least, assuming that people outside Microsoft resemble people inside Microsoft, where interest in writing an `IDataTransform` is rather higher, for some reason. However this migration is somewhat difficult -- much of our existing documentation including this is not situated in the new world of the APIs we see in `Microsoft.ML/.Data/.Transforms/`.etc. Anything like that especially relating to infrastructure will take some time, since the new API is not covered in those documents *at all*, and I'd want to re-emphasize certain concepts.

For the third question: You are talking I guess about building a pipeline in ML.NET, then feeding it into Accord.NET. I am unfamiliar with Accord.NET's architecture, but I will say historically when we have attempted to interface with other toolkits doing similar "stuff" (by which I mean building pipelines leading ultimately in some cases to some predictive model) our ability to mix cleanly in their world has depended mostly on that other toolkit having an abstraction for how they consumed data; in C#, we'd say some interface or abstract class. Then we just make an implementation of whatever that is to wrap our little `IDataView`s, pass it into them, and call it a day. If there is no abstraction, that means we've have to materialize whatever structure they are using, to interface with them. This can be more or less painful depending on *what* exactly type of structure they natively read to ingest data.

Let me know if I misunderstood your questions, or provided unhelpful answers.

**Comment by dotChris90** [comment]
@TomFinley better later and in detail then early and short. :)

To answer 1 ) okay thats totally fine to me. I will close issue https://github.com/dotnet/machinelearning/issues/138 because it fits to my ideas "general access". I simple ask because last year I was redesign the loader of a Daimler simulation department. Was quite horrible. They do not implement any interface and so every loader had its own methods, properties etc. You can guess the rest. After some month all implemented same interface and we had cleaner code. 
So all is fine with you answer. ;)

To answer 2 ) I understand your priority and it is totally fine for me. I just was asking because this reason : in Germany the car industry using mostly the MDF4 data format. And unfortunately this data format is totally unimportant in general use. So because its unimportance I was thinking to write such importer by myself ;) 

To answer 3 ) Your words are correct. Honestly spoken I was not thinking so in detail. I simple was thinking a very easy scenario. You have a data loader / importer and simple want to get the array (e.g. double[]) from this importer. If you can get this I think many operations already can be done in ACCORD.NET. 

Thank you a lot for your answers and wish you a good week. I close this issues. :)
