### ISSUE TITLE
Any reason for inconsistency in params for TextLoader?

### ISSUE THREAD

**Issue by srsaggam** [dotnet/machinelearning#2472]
1) This Method :
https://github.com/dotnet/machinelearning/blob/834e4715afa070f5e5c3628693682943b3f0bd6d/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs#L55

2) and this one : 
https://github.com/dotnet/machinelearning/blob/834e4715afa070f5e5c3628693682943b3f0bd6d/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs#L22

Looks like the first one has params like : 
```
char separatorChar = '\t', bool allowQuotedStrings = true, bool supportSparse = true, bool trimWhitespace = false
```

Where as the second one doesn't have those. In order to use those params there is another method overload : 
```
CreateTextLoader(this DataOperationsCatalog catalog, TextLoader.Arguments args, IMultiStreamSource dataSample = null);
```

This takes Arguments class and particularly one param is interesting in this Arguments:
```
char [] Separators
```
 Any reason this is char[] and not char like in other overloads? and why inconsistency in params for the methods 1) and 2).

**Comment by srsaggam** [comment]
@daholste @justinormont

**Comment by TomFinley** [comment]
@rogancarr and @sfilipi, should be made consistent.

**Comment by abgoswam** [comment]
@TomFinley . Could you kindly clarify what you mean by should be made consistent ?

To me it seems reasonable that the  "simple" APIs  (1 and 2 above)  take a `char` to indicate a single separator character. 

If a user wants to specify multiple  separator characters they can use  the "advanced" API which takes in the `Options` 

https://github.com/dotnet/machinelearning/blob/eecf2727123e062f80d259ac66b68cf01c4b7078/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs#L39-L41

cc @wschin

**Comment by TomFinley** [comment]
Yes @abgoswam I agree, the convenience methods should continue to take `char`. The advanced options should still take `char[]` I think, since it is sometimes important.

Of particular interest to me was the lack of these:

```csharp
bool allowQuotedStrings = TextLoader.DefaultArguments.AllowQuoting,
bool supportSparse = TextLoader.DefaultArguments.AllowSparse,
bool trimWhitespace = TextLoader.DefaultArguments.TrimWhitespace)
```

It is not clear to me that the overloads should differ in *this* respect. Also why does one have the possibility of handling a file handle (which enables it to read feature names into the schema) and the other does not?

So these two overloads are inconsistent leading to loss of capability in one or the other, and I think this should be made consistent.

**Comment by rogancarr** [comment]
Also, see #2512: We only support a limited set of characters for saving a text file, so perhaps we should move away from an explicit `char` and use an `enum` of allowed characters instead.
