### ISSUE TITLE
How about a Preview for Metadata?

### ISSUE THREAD

**Issue by nsulikowski** [dotnet/machinelearning#2484]
something like this?
`DataDebuggerPreview Preview(this Metadata metadata, int maxRows = 100)`

**Comment by rogancarr** [comment]
@nsulikowski Can you give a little more detail about what you're looking for?

We currently have `IDataView.Preview(int nRows)` to preview the first N rows in a dataset. In the debugger, you can also inspect the `IDataView` objects to see their schema and metadata.

**Comment by nsulikowski** [comment]
Preview is great for debugging, but I also find myself using it outside debugging, to inspect data quickly.
It'd be nice to have the same quick access for Metadata. I know I can use the raw api to do it myself, but it takes quite a bit of code due to the getter methods. Makes sense?

**Comment by rogancarr** [comment]
I see what you're saying now.

@eerhardt @TomFinley Related to `IDataView` API discussion yesterday. What do you think about this?

@nsulikowski Can you give a concrete example of use? It would help to guide the discussion.

**Comment by TomFinley** [comment]
I believe metadata for schema displays well in the debugger on `DataViewSchema` objects? If it does not, then that should be added, certainly.

Regarding a more general "previewer" I am less certain. We ourselves have directly applied this API and the code behind it internally in multiple products, and in each we have the problem of how to display "previews" of the data (including metadata), and we write up different solutions each time because what is appropriate in that instance is strongly application and scenario dependent. I have absolutely no idea what preview would be found useful under these circumstances. Formatted how? Human readable? Machine readable?

It also strikes me as being basically a special case of the classical problem of why making structured `ToString` is one of the most pernicious blunders an API can make, if their goal is to have an API without breaking changes.

So, I think we should approach this the same way most libraries do. (Indeed, even the .NET libraries. See how useful the result of `List<T>.ToString()` is. 😉 This is not accidental.) We generally don't write client code for our library (except targeted scenarios directly related to developing with that library, by which I mean obviously our debugger display helpers), but we write our API in such a way that people can write client code.

**Comment by nsulikowski** [comment]
I guess I didn't realized that metadata doesn't have a specific format. Preview might not necessarily make sense. Thanks for the clarification

**Comment by rogancarr** [comment]
Thanks for starting the conversation @nsulikowski ! It's always good to think through these things, especially as we get ready for the 1.0 of these APIs. I'll mark as closed, but feel free to re-open if you have any more thoughts on this.
