### ISSUE TITLE
Support ColumnAttribute on properties and not just fields

### ISSUE THREAD

**Issue by kevmal** [dotnet/machinelearning#254]
It looks like it's been considered:

https://github.com/dotnet/machinelearning/blob/ea07be87a5300e0e4d50563cfb14e963f3dee286/src/Microsoft.ML.Api/SchemaDefinition.cs#L318-L319

I just wanted to get the issue started as it's probably the best solution to #180.

**Comment by zeahmed** [comment]
It could be a good feature to support custom transformation on some feature while using CollectionDataSource e.g. applying log on some numeric column(s).

**Comment by isaacabraham** [comment]
Please can you also support not just properties but also non-default constructors? This is important to get a coherent F# story going.

**Comment by dsyme** [comment]
I searched for uses of "GetFields" and here's what I see:

Relevant:
* The primary use in [SchemaDefinition.cs](https://github.com/dotnet/machinelearning/blob/5e08fa1ea7bfb54f28ed0815cb6413e0068e6dd1/src/Microsoft.ML.Api/SchemaDefinition.cs#L322) that is the immediate cause of the F# problem
* A secondary use related to cursor channels in [SchemaDefinition.cs](https://github.com/dotnet/machinelearning/blob/5e08fa1ea7bfb54f28ed0815cb6413e0068e6dd1/src/Microsoft.ML.Api/SchemaDefinition.cs#L156)
* A possibly-relevant use in [TextLoader](https://github.com/dotnet/machinelearning/blob/5e08fa1ea7bfb54f28ed0815cb6413e0068e6dd1/src/Microsoft.ML/Data/TextLoader.cs#L74) 

Not relevant:
* Uses in [sweep](https://github.com/dotnet/machinelearning/blob/12e629882694dac319168afbbac47f83fb62101f/src/Microsoft.ML.PipelineInference/RecipeInference.cs#L469) and [LightLGBM](https://github.com/dotnet/machinelearning/blob/5e08fa1ea7bfb54f28ed0815cb6413e0068e6dd1/src/Microsoft.ML.LightGBM/LightGbmArguments.cs#L59) parameters 
* Uses in [command argument](https://github.com/dotnet/machinelearning/blob/5e08fa1ea7bfb54f28ed0815cb6413e0068e6dd1/src/Microsoft.ML.Core/CommandLine/CmdParser.cs#L609) and [EntryPointUtils.cs](https://github.com/dotnet/machinelearning/blob/5e08fa1ea7bfb54f28ed0815cb6413e0068e6dd1/src/Microsoft.ML.Core/EntryPoints/EntryPointUtils.cs#L54) which are not relevant to this issue
* A bunch of uses in tests

**Comment by dsyme** [comment]
@eerhardt I've taken a look at what it might take to fix this, could you take a look and check the general direction of travel please? 

Here's the prototype: https://github.com/dsyme/machinelearning/compare/fs1...dsyme:fs2?expand=1

Basically this would allow the use of [ColumnNameAttribute and friends](https://github.com/dsyme/machinelearning/compare/fs1...dsyme:fs2?expand=1#diff-46f68725db753df8e54db621da51265cR17) on both public fields (as today) and public properties that have getters/setters.

The branch linked above allows an F# record definition to be successfully used, e.g. [this test](https://github.com/dsyme/machinelearning/compare/fs1...dsyme:fs2?expand=1#diff-fe2d4189320f83b77c7f4f5dca8bb5d8R132) now passes in that branch.  It would also allow C# classes that just use attributed public get/set properties to be used.

It would be a change in spec because existing C# classes that use public fields _plus_ some additional get/set properties may now have their get/set properties considered part of the schema, when they weren't before.  I suppose this may mean the user has to add some NoColumn attributes on to these properties.  

We could adjust the spec to be "if there are non-zero public fields, then use public fields.  Otherwise, see if there are public get/set properties"

I believe this would address @terrajobst's concerns about the use of public fields, at least in the core schema model.  THere are other uses of GetFields() and field-reflection in the component model/catalog parameterization system which I haven't attempted to address.

**Comment by eerhardt** [comment]
Taking a look now.  /cc @Ivanidzo4ka as well, since he was investigating allowing properties too.

**Comment by Zruty0** [comment]
Now that #616 is in, I think this one should be closed. 

I discovered one inconvenient side effect though: we are requiring both the getter and the setter to be present and public for the properties. It adds confusion to the cases like in #595 , where you can use properties to act like 'calculated columns', without a clear way to provide a setter. 

I'll open a new issue for this.
