### ISSUE TITLE
Training multiple random forests on common data set

### ISSUE THREAD

**Issue by mjmckp** [dotnet/machinelearning#256]
I am attempting to train random forests on a fixed 6GB data set of features, with `N` different labels, using `M` different random forest parameter settings.  Overwhelmingly, the time taken to do this appears to be the disk transpose operation, which occurs `N * M` times, when ideally it should only be done once (as the feature set is common to all models).

To rectify this, is there any way to either:
- train multiple random forests in the same pipeline, or,
- share the transposed data object between multiple training pipelines?

**Comment by codemzs** [comment]
@mjmckp This is actually a good question and something we are investigating if transposed object can be shared amongst multiple runs but one question.

**Comment by TomFinley** [comment]
We might consider exposing [TransposeSaver](https://github.com/dotnet/machinelearning/blob/c023727b76970ab913ec1ce38276508835c17bcf/src/Microsoft.ML.Data/DataLoadSave/Transpose/TransposeSaver.cs) and [TransposeLoader](https://github.com/dotnet/machinelearning/blob/c023727b76970ab913ec1ce38276508835c17bcf/src/Microsoft.ML.Data/DataLoadSave/Transpose/TransposeLoader.cs), since that's one way we internally try to solve this. But I'm not sure that we've exposed the idea of *any* saver in the public API yet. That method *can* be more effective for larger datasets.

(It could of course be called directly -- but that might be subideal. It would be good to have facilities for saving in the public API.)

**Comment by mjmckp** [comment]
I tried using TransposeSaver/Loader, thanks @TomFinley.  However the setup for fast forest training is still very slow.  The method `ExamplesToFastTreeBins.FindBinsAndReturnDataset` seems to spend an inordinate amount of time in both `CalculateBins` and `CreateSingletonFlock` when using the `DiskImpl` implementation of `DataConverter`.

**Comment by mjmckp** [comment]
I profiled training of a `FastTreeRegressor` with `DiskTranspose=true`, using 1,000,000 input rows and 200 real-valued feature columns.

The setup takes 3 times as long as the training:
![image](https://user-images.githubusercontent.com/7776787/41448271-06f0729e-709d-11e8-8319-5a0993e640fb.png)

For `ConvertData` about half of that is spent in each of `CalculateBins` and `CreateSingletonFlock`:
![image](https://user-images.githubusercontent.com/7776787/41448313-47f93ca8-709d-11e8-95f8-cc4030dccb45.png)

![image](https://user-images.githubusercontent.com/7776787/41448383-a09b7e8e-709d-11e8-8102-794e5d74e3c7.png)

Are there any ways to speed this up?   The CPU utilization during the `ConvertData` stage is very low, as all this is done single threaded, would it make sense to do this in parallel across the number of features?

**Comment by mjmckp** [comment]
I have switched to using the LightGBM wrappers, which are orders of magnitude faster both at the data preparation stage and the training stage.

I would recommend that anyone with large data set to avoid using the managed ML.Net implementations.  The data preparation stage does multiple passes over the data and isn't well parallelised.  The training stage is ok, but can't match LightGBM on a GPU.
