### ISSUE TITLE
Docs: LoadColumn attribute mentions the column name, but no means to provide it

### ISSUE THREAD

**Issue by pkulikov** [dotnet/machinelearning#2593]
The [LoadColumnAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.loadcolumnattribute?view=ml-dotnet) class description claims:
https://github.com/dotnet/machinelearning/blob/cf7e3d992b4b770a7345174673107c47e8bf4d13/src/Microsoft.ML.Data/DataLoadSave/Text/LoadColumnAttribute.cs#L10-L15

However, there are no means to provide the name of a column. Available three constructors only allow to specify the source indices.

That looks to be a copy-paste error from the [ColumnAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.columnattribute?view=ml-dotnet) documentation.

As I see from the usage of the `LoadColumn` attribute:

https://github.com/dotnet/machinelearning/blob/cf7e3d992b4b770a7345174673107c47e8bf4d13/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs#L1336-L1345

the `LoadColumn` attribute is used to define only the source indices of a column, while the name is defined either by the `ColumnName` attribute or the property name.

**Comment by Ivanidzo4ka** [comment]
This need to be cleaned up.
First `ColumnAttribute` need to be deleted. It's pointless at current moment.
Second documentation for `LoadColumnAttribute` and `ColumnNameAttribute` need to be update.

Part of me want's to have option to provide Name in `LoadColumnAttribute`, but that would bring confusion what to do if you have two attributes on top of field/property `LoadColumn` and `ColumnName`. It's unclear which one should have more priority. 
In same time  we can't get rid of `ColumnName` because you can use it to decorate your custom class and it's useful.

**Comment by Ivanidzo4ka** [comment]
If you want to chime in regarding wording for this attributes feel free to join https://github.com/dotnet/machinelearning/pull/2638
