### ISSUE TITLE
Ranking / Ranker API inconsistency

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2634]
In the API, we have references to "Ranking" and "Ranker". One (of many) examples is that `mlContext.Ranking.Evaluate` returns a `RankerMetrics` object. This leads to an inconsistency across the API surface.

**Comment by Ivanidzo4ka** [comment]
Just to make it clear. Which one do we prefer?

**Comment by TomFinley** [comment]
> Just to make it clear. Which one do we prefer?

The task is `BinaryClassification`, `MulticlassClassification`, `Regression`, `Clustering`, `Ranking`. The metrics are correspondingly named `BinaryClassificationMetrics`, etc. The rank*er* is the thing that does the rank*ing*, so that is fine, but the metrics should be related to the task. It should be `RankingMetrics`.

**Comment by TomFinley** [comment]
High level comment is this, I think renaming the evaluators and metrics is correct, but I would not have renamed the signature.
