### ISSUE TITLE
ReadFromTextFile cannot load data as KeyType

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2642]
`CreateTextLoader` can read in data as KeyTypes, but `ReadFromTextFile` cannot.

`CreateTextLoader` works like this:
```cs
new TextLoader.Column(matrixColumnIndexColumnName, DataKind.U4, new [] { new TextLoader.Range(1) }, new KeyCount(20)),
```

Now, there is a `KeyType(Count = 20)` attributes that you can put on a class property, but this only seems to be used by scoring. I'd like to be able to use that, or something like that, to read in data directly as KeyType.

**Comment by rogancarr** [comment]
This isn't quite a bug, and it's definitely not necessary for v1.0, but it's a clear mismatch in the API, and the `KeyType` attribute led me astray for quite a bit, so if it's not a v1.0 fix, I'd recommend we target this for v1.1.

**Comment by eerhardt** [comment]
@codemzs - This was the issue that @nicolehaugen79 ran into. I think this would be a good "first time contributor" type of issue.

**Comment by Pomoinytskyi** [comment]
Hi all. I'd like to fix this issue.
Is it still actual. 
I cannot find any references for ReadFromTextFile in master branch.
In what branch it should be fixed?

**Comment by eerhardt** [comment]
@Pomoinytskyi - Yes this is still a valid issue. `ReadFromTextFile` was renamed to `LoadFromTextFile`. See

https://github.com/dotnet/machinelearning/blob/a072b5e720409ba593c94b9e76e3daa05662f6ac/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs#L148-L154

Basically, the issue here is that you can't load KeyType data from a file when you use the `CreateTextLoader` and `LoadFromTextFile` overloads that take a Type to define the column information.

This method:

https://github.com/dotnet/machinelearning/blob/a072b5e720409ba593c94b9e76e3daa05662f6ac/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs#L1444-L1451

Should be respecting the `KeyTypeAttribute`.

Check out the referenced duplicate issue - https://github.com/dotnet/machinelearning/issues/3811 as well for more information.

**Comment by aslotte** [comment]
@eerhardt I'm planning on opening a PR for your review for this issue this weekend. Would much appreciate your guidance if I'm on the right track as this would be my first issue. Thanks!
