### ISSUE TITLE
SamplesUtils is not searchable on doc site and makes ML.NET learning curve sharp

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#2794]
We use `SamplesUtils` project in many examples. However, its functions and classes cannot be found in ML.NET's official doc site. This is not ideal because once a user has a question regarding `SamplesUtils` when learning our API examples, they will be blocked until they clones ML.NET or finds the right nuget package. This makes the learning curve of ML.NET very sharp. Also, please do not expect users have Visual Studio installed, so finding the right solution can be even more painful.

**Comment by rogancarr** [comment]
@CESARDELATORRE @JRAlexander 

I think we need clarification on how we should be formatting docs samples in this project, and what the relationship between the documentation samples and the samples.

Questions:
1. Should the samples included in the API docs be stand-alone, full length programs?
2. Should the samples included in the API docs be searchable on the docs site and live in their own section?

Related to #2726

**Comment by shmoradims** [comment]
I checked with Wei-Sheng and the APIs are searchable in [API search](https://docs.microsoft.com/en-us/dotnet/api/?view=ml-dotnet).

@rogancarr let's discuss your questions above in #2726.

Also note that this issue was **not** about the sample code being searchable, but `SamplesUtils` namespace and it's utility classes being searchable. Sample code is not part of ML.NET API, so it's **not** searchable through [API search](https://docs.microsoft.com/en-us/dotnet/api/?view=ml-dotnet).
