### ISSUE TITLE
Exception in CreditCard Fraud Detection sample while migrating to v0.11

### ISSUE THREAD

**Issue by prathyusha12345** [dotnet/machinelearning#2821]
### Issue

- While migrating CreditCard Fraud Detection sample I am getting the below exception while trying to save train/test data

```
                //(trainData, testData) = classification.TrainTestSplit(data, testFraction: 0.2, stratificationColumn: "Label");
                TrainTestData trainTestData = classification.TrainTestSplit(data, testFraction: 0.2);
                trainData = trainTestData.TrainSet;
                testData = trainTestData.TestSet;

                // save test split
                using (var fileStream = File.Create(Path.Combine(_outputPath, "testData.csv")))
                {
                    mlContext.Data.SaveAsText(testData, fileStream, separatorChar:',', headerRow:true, schema: true);
                }
```

![image](https://user-images.githubusercontent.com/22335043/53674701-96fb3900-3c44-11e9-9509-399e4ec226c9.png)

**Comment by Ivanidzo4ka** [comment]
please change your textloader options to allowQuote

**Comment by CESARDELATORRE** [comment]
It was related to the fact that the DataSet Label file had the Boolean values in quotes, such as:
- "1" (Instead of 1)
- "0"  (Instead of 0)

This is a side-effect/issue of turning off quoting by default in ML.NET: 
https://github.com/dotnet/machinelearning/pull/2630

I modified the original dataset so there are no quotes in the file, plus I refactored the sample so it is simpler. 
I successfully migrated that sample to v0.11, so I'm closing this issue.
