### ISSUE TITLE
Scrubbing time series related transformers

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2834]
Sub task of #2827
IidChangePointEstimator
IidSpikeEstimator
SsaChangePointEstimator
SsaSpikeEstimator

**Comment by eerhardt** [comment]
Time Series isn't a "stable" API for v1.0 according to https://github.com/dotnet/machinelearning/issues/2279#issuecomment-467614084.  Which means this shouldn't be in "Project 13".

**Comment by codemzs** [comment]
@eerhardt What is the definition of stable API?

**Comment by eerhardt** [comment]
That issue is calling out: "Which packages ship as version `1.0.0` when `Microsoft.ML` ships `1.0.0`"?

Since TimeSeries isn't in that list, it won't be shipping `1.0.0` when the rest of the stable packages are shipped.

In general, the definition of a stable API is one that won't accept API breaking changes going forward.

**Comment by Ivanidzo4ka** [comment]
Can we at least change names of extension methods to something more bearable than

https://github.com/dotnet/machinelearning/blob/5746ec9eeb5aac9dcd3c4355ccce46d17ee46cdf/src/Microsoft.ML.TimeSeries/ExtensionsCatalog.cs#L23

**Comment by eerhardt** [comment]
> Can we at least change names of extension methods to something more bearable than

(Totally my opinion): Yes, we can do that. AFTER all the other APIs that are stable for `v1.0.0` are bearable for long-term consumption.

**Comment by wschin** [comment]
We decided to release time series package as it (in terms of the class names), so this issue can be closed.
