### ISSUE TITLE
Different behavior for TokenizeChar and TokenizeWords

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2864]
TokenizeChar produce vector of keys.
TokenizeWords produce vector of strings.
I have to add MapValueToKey to TokenizeWords in order to apply ProduceNgrams to it.

**Comment by TomFinley** [comment]
This is intentional and as designed. The set of possible *characters* (in the sense of possible values of `char`) is finite and well defined. This allows tokenization of characters to forego being a trained transform, if we like, and skip the necessary step of building dictionaries or hashing, or whatever, which remains a requirement of words. The set of possible words is not well defined.

**Comment by TomFinley** [comment]
Hi @Ivanidzo4ka, if this is good enough, should we close?
