### ISSUE TITLE
Can't find CollectionDataSource class 

### ISSUE THREAD

**Issue by eyadek** [dotnet/machinelearning#3014]
### System information

- **OS Windows**
- **.NET Version 4.7.2**: 

### Issue

Hi, I'm using ML.NET 0.11 in an ASP.Net MVC 5 Web App. the .Net version is 4.7.2 and I can use the CollectionDataSource to load data from list to the pipeline. How can I use it?

**Comment by singlis** [comment]
Hi @eyadek, 

CollectionDataSource is an extension that we provided around the 0.2 version of ml.net. This has since been removed and replaced with LoadFromEnumerable:
https://github.com/dotnet/machinelearning/blob/f03c49d8045b0cc85bff104488610a21936a5195/src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs#L77

An example of this can be found here:
https://github.com/dotnet/machinelearning/blob/f03c49d8045b0cc85bff104488610a21936a5195/test/Microsoft.ML.Tests/Transformers/CopyColumnEstimatorTests.cs#L40-L42

**Comment by sfilipi** [comment]
You can also check out the example in [docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.dataoperationscatalog.loadfromenumerable?view=ml-dotnet#Microsoft_ML_DataOperationsCatalog_LoadFromEnumerable__1_System_Collections_Generic_IEnumerable___0__Microsoft_ML_Data_SchemaDefinition_)

**Comment by ganik** [comment]
i consider this answered since there are no follow ups from the author
