### ISSUE TITLE
Getting exception when trying to evaulate in sample -PCA based Anomaly Detection

### ISSUE THREAD

**Issue by prathyusha12345** [dotnet/machinelearning#3038]
### Issue

I am trying to create a new sample based on PCA based Anomaly Detection i.e CreditRisk Detection. i am using the **German Credit Risk** data as dataset from [here](https://archive.ics.uci.edu/ml/datasets/Statlog+(German+Credit+Data)). It contains label values as 1 and 2 with 1-positive and 2-negative.

I am trying to train the model on train data by dropping label column as PCA based anomaly detection trains on unsupervised data. When I am trying to evaluate I am getting the **error** as below

![image](https://user-images.githubusercontent.com/22335043/54717972-addfcd80-4b16-11e9-8222-0efccdfe8252.png)

### Source code / logs

the source code is available at the PR [https://github.com/dotnet/machinelearning-samples/pull/321](url)

**Comment by prathyusha12345** [comment]
@shmoradims @wschin could you please check the above issue and let me know any modifications.

**Comment by singlis** [comment]
Thanks @prathyusha12345 
The exception is happening in Evaluate -- not in Fit. Also Training does not need labels but prediction does expect labels. Because you are adding the drop column to your pipeline, this is affecting the test data as well and dropping the Label column when its transformed.

Try dropping the label column on the train data only. I did this by creating a model to drop the data and transformed the train data before passing to the pipeline (there maybe an easier way):
```
           var trainTestData = mlContext.AnomalyDetection.TrainTestSplit(dataView, 0.2);
            var trainData = trainTestData.TrainSet;
            var dropPipeline = mlContext.Transforms.DropColumns("Label");
            var dropModel = dropPipeline.Fit(trainData);
            trainData = dropModel.Transform(trainData);
```

After doing this, I am now seeing a second exception with Evaluate that I am looking into:

> AUC is not defined when there is no negative class in the data

**Comment by singlis** [comment]
Hi @prathyusha12345, 

Couple of things:
1) Dropping the Label column is not needed as this random PCA ignores this column anyway:
https://github.com/dotnet/machinelearning/blob/b241bcdf0c6071f6a2e2d4c9b382d6167f0f97c6/src/Microsoft.ML.PCA/PCACatalog.cs#L58

2) Once the DropColumn is removed, you will get a different error regarding that there are no negative samples for the AUC when Evaluate is called. This is because the label data is a floating point with the values 1 and 2 and Evaluate is expecting the values to be 0 or 1 (non-zero). Because there are no 0 values, there are no negative values to compare. 

In order to support this, I used a value mapping to convert 1->0 and 2-> 1:
```
            var keyList = new List<float>() {1.0F, 2.0F};
            var valueList = new List<float>() { 0.0F, 1.0F};
```
Then used this in the value mapping:
```
        IEstimator<ITransformer> dataProcessingPipeline = mlContext.Transforms.Concatenate("NumFeatures", nameof(CustomerCreditData.numOfMonths),
                                nameof(CustomerCreditData.CreditAmount), nameof(CustomerCreditData.InstallmentRate), nameof(CustomerCreditData.ResidentSince),
                                nameof(CustomerCreditData.age), nameof(CustomerCreditData.NumberOfExistingCredits), nameof(CustomerCreditData.NumberOfLiablePeople))
                .Append(mlContext.Transforms.Conversion.ValueMap(keyList, valueList, new[] {new ColumnOptions("LabelValue", "Label")}))
...
```

Then for Evaluate, I use the LabelValue column as the "Label" column:
```
var metrics = mlContext.AnomalyDetection.Evaluate(transformedData, "LabelValue");
```

**Comment by prathyusha12345** [comment]
How do we identify anomalies? which values we need to consider predicted label or score? if we consider score then what is the threshold value to consider a record as anomaly?

**Comment by singlis** [comment]
Hi @prathyusha12345, you should be able to use the PredictedLabel as an indicator on whether it is an anomaly or not. By the way, I believe PredictedLabel is true when it is not an anomaly.

**Comment by singlis** [comment]
@prathyusha12345  - I am closing this issue. Feel free to reopen if needed.
