### ISSUE TITLE
IPredictor inaccessible in 0.11

### ISSUE THREAD

**Issue by ericjohannsen** [dotnet/machinelearning#3139]
### System information

- Windows 10
- .NET Core 2.2.104

### Issue

- Updated ML.Net 0.10 to 0.11 using NuGet
- CS0122	'IPredictor' is inaccessible due to its protection level
- The rationale behind the change to be documented and new strategies to be highlighted.

### Source code / logs

Please see https://stackoverflow.com/q/55344383/141172

**Comment by yaeldekel** [comment]
Hi @ericjohannsen , thanks for your interest in ML.NET.
`IPredictor` is an internal interface that is not intended to be part of the public API. However, you can change this:
```
chain.OfType<IPredictionTransformer<IPredictor>>()
```
to this:
```
chain.OfType<IPredictionTransformer<object>>() 
```
since the generic type on `IPredictionTransformer` is an 'out' type with the constraint `where TModel : class`. 

I also want to mention that `TransformerChain<ITransformer>` has a `LastTransformer` property that returns an `ITransformer`, and in most cases the `IPredictionTransformer` is the last element in the chain, so instead of using `OfType` you can try something like this:
```
var predictor = trainedModel.LastTransformer as IPredictionTransformer<object>;
```
I think in most scenarios this would work, if the model does indeed contain an `IPredictionTransformer`.

Note also that in the upcoming 0.12 version, the API to load the model will also change, you can see the new API here: https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/Model/ModelOperationsCatalog.cs#L138

**Comment by ericjohannsen** [comment]
I developed this approach because my last transformer wasn’t the IPredictionTransformer. I’ll give this solution a try when at a computer.

Is the new 0.12 API expected to change again before 1.0?

**Comment by sfilipi** [comment]
@ericjohannsen the API should not change again before 1.0.

**Comment by wschin** [comment]
Looks like this issue had been resolved.
