### ISSUE TITLE
Release notes for 0.2 are not linked from the .sln, but those for 0.1 are

### ISSUE THREAD

**Issue by markusweimer** [dotnet/machinelearning#322]
When browsing the `docs` folder via Visual Studio, there are release notes for ML.NET 0.1 listed. However, the release notes for 0.2 are missing. They are, in fact, in the file system.

We should have a consistent scheme here: Either the files are always added to the solution file, or never.

**Comment by markusweimer** [comment]
@GalOshri WDYT? Which way should we go?

**Comment by markusweimer** [comment]
Actually, we have that issue for many of our `.md` files.

**Comment by GalOshri** [comment]
I don't have a strong preference. I'd imagine it would be useful to include documentation that explains code concepts in the solution, but that doesn't apply to release notes. If we want to be completely consistent, we can keep everything in the solution. Thoughts?

**Comment by TomFinley** [comment]
@GalOshri and @markusweimer... assuming we care about having the `.md` files accessible in VS (I personally have never found that useful, but maybe other people do), if we had a project that did not produce any build artifact called "Documentation" or somesuch, that might be a better alternative to keeping things in solution items. That project could easily be set up to just track the `docs` directory just as all existing "code" projects track their directories. Then we wouldn't have to keep a separate list in something as awkward to deal with in an `.sln` file.

(@markusweimer , should I take this issue to mean you are an enthusiastic VS user?)

**Comment by Nepomuceno** [comment]
I would argue that this files are not actually part of the solution since they are not part of the build so they should not be included as part of the solution. But I understand the argument of keeping them as reference. But since the code has plenty of reference and I don't imagine that someone that it is going to look for extra references will be doing that by reading `.md` files on VS Removing them to keep the solution clean would be a better idea.
