### ISSUE TITLE
Samples templates could be improved and use TrainTestSplit

### ISSUE THREAD

**Issue by artidoro** [dotnet/machinelearning#3360]
Our samples templates for trainers usually call the `GenerateDataPoints` method twice, once to generate the test data and once to generate the training data. Furthermore, the two calls are not symmetrical.

See here the template for binary classification trainers:
https://github.com/dotnet/machinelearning/blob/5538ccfcd8b0ad89146cf428dcfae6f25b179703/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/BinaryClassification.ttinclude#L21-L25
and
https://github.com/dotnet/machinelearning/blob/5538ccfcd8b0ad89146cf428dcfae6f25b179703/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/BinaryClassification.ttinclude#L49-L50

It would be more educationally useful to replace this with a single call to the data generation method and combine it with a call to `TrainTestSplit`.

See @rogancarr's motivating comment: https://github.com/dotnet/machinelearning/pull/3338#discussion_r275909222

**Comment by shmoradims** [comment]
The rationale behind not using TrainTestSplit was the overall API reference guideline of using as few other APIs as possible, to show the usage of a given API being documented. 

I agree that TrainTestSplit is an educational pattern. But the current pattern is equally valid. It's as if the user already has a separate training and test sets and is loading them separately.

Given that using TrainTestSplit will change the training/test data of all the samples and thus will change all the expected outputs in the comments, this change is costly at this point. Since the current approach is equally valid, I suggest not making this change, just because of the non-trivial cost.

**Comment by artidoro** [comment]
Closing given @shmoradims comments.
