### ISSUE TITLE
Incorrect link in ComputeLogisticRegressionStandardDeviation class documentation

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#3479]
It recommends using the implementation in Microsoft.ML.Mkl.Components, but it links to the page of the abstract class `ComputeLogisticRegressionStandardDeviation`.

**Comment by najeeb-kazmi** [comment]
Microsoft.ML.Mkl.Components depends on Microsoft.ML.StandardTrainers. In order to link to the Mkl.Components implementation, we would have to add a reference to Microsoft.ML.Mkl.Components in Microsoft.ML.StandardTrainers. Visual Studio does not allow this as this would create a circular dependency.

Any suggestions?

**Comment by yaeldekel** [comment]
Hmmm, I'm not sure. Maybe using 'xref' would work?
@natke , do you know?

**Comment by natke** [comment]
Can you add a link to the doc page with the broken link please @yaeldekel ?

**Comment by yaeldekel** [comment]
Here it is: https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.computelogisticregressionstandarddeviation?view=ml-dotnet&branch=master
It's not so much broken, as it is pointing to itself, and I think it should be pointing to an implementation of the abstract class that's in a different assembly.
