### ISSUE TITLE
TextLoader CreateFrom useHeader usage is confusing

### ISSUE THREAD

**Issue by jfcarr** [dotnet/machinelearning#354]
Example:

`pipeline.Add(new TextLoader(_datapath).CreateFrom<SampleModel>(useHeader: true, separator: ','));`

The usage of the useHeader argument is not intuitive, based on the name.  The name "useHeader" implies that a value of **true** will cause the header line to be included when loading the model.  In reality, setting useHeader to **true** causes the header line to be skipped.  Perhaps something like "excludeHeader", or "ignoreHeader", instead?  Or, if you'd prefer something that simply indicates the presence of a header line, versus an action to be taken, maybe "containsHeader"?

Using ML version 0.2.0 in a .NET Core 2 console app.

**Comment by pkulikov** [comment]
@jfcarr based on the [method docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.textloader.createfrom?view=ml-dotnet#Microsoft_ML_Data_TextLoader_CreateFrom__1_System_Boolean_System_Char_System_Boolean_System_Boolean_System_Boolean_), `containsHeader` looks to be the most appropriate name.

**Comment by jwood803** [comment]
Not sure if this helps, but Spark uses an option of `header: true` when reading CSV files. Would that be too ambiguous in this case?

**Comment by TomFinley** [comment]
I agree `useHeader` is not a great name. The verb "use" suggests that the header is there no matter whether we are "using" it or not, which of course is not the case. We "use" the first line of the file in both cases -- just in the one case it is used as the first row of data (`useHeader: false`), and in the second case (`useHeader: true`) it is used to infer things like feature names.

I like @jwood803 's suggestion of merely `header` as Spark does best. I'm not sure it is actually ambiguous. I'd have to think any reasonable person, when facing the `bool` option `header` to a text parser, would realize that the user is telling us whether the input file has a header or not. (I can't think of any other reasonable interpretation, but perhaps I'm just showing my lack of imagination.)

If others disagree and the feeling is that this is not specific enough, the actual underlying structure being set by the constructor as seen here, is called `HasHeader`, as seen here:

https://github.com/dotnet/machinelearning/blob/9cf7460f123fb90440dba824caa4ddfeaf478cf0/src/Microsoft.ML/Data/TextLoader.cs#L120

For that reason I personally have a slight preference for `hasHeader`, as a second option after `header`.

While we are at it we might also want to clean up some of these other names that diverged from the underlying structure for seemingly no particular reason (in particular I don't think `supportSparse` is terribly helpful since I don't think "support" is the right verb), and also do a grammar pass on these docs. (E.g., on this parameter, "Does the file contains header?")

**Comment by jfcarr** [comment]
For what it's worth, I'm a fan of "hasHeader".  Its usage is intuitive, and this constructor:

`Arguments.HasHeader = hasHeader;`

...is pleasing to me.  :-)

**Comment by jwood803** [comment]
@TomFinley I can (attempt to) make updates for this if there are no objections. Or should there be more discussion on this before proceeding?

**Comment by codemzs** [comment]
No longer applicable as we now have the new API.
