### ISSUE TITLE
ML.Net tutorial inside Win32 RunFullTrust process gives inconsistent results

### ISSUE THREAD

**Issue by PaulaScholz** [dotnet/machinelearning#3702]
### System information
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17763 Build 17763

- **OS version/distro**:
- **.NET Version (eg., dotnet --info)**: 
:\Users\v-pauls>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.202\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

### Issue

- **What did you do?**
I created a Win32 "FullTrustProcess" version of the Iris tutorial, callable from a UWP app.
- **What happened?**
The app made no predictions under ML.Net 0.11.  When updated to ML.Net 1.0, the app does provide predictions, but these are only "Correct" some of the time, in other words, they only match the tutorial output sometimes.

Additionally, ML.Net 1.0 seems to throw EETypeLoad exception on loading AppContract.DLL.  Don't know if its your code or a dependency.

- **What did you expect?**
Consistent results.

### Source code / logs

A complete sample project, screenshots, debug output, and a explanatory REAME.md may be found at my GitHub repository at https://github.com/PaulaScholz/MLDotNetUWP

**Comment by PaulaScholz** [comment]
Note that while the Cluster predictions in the three examples are always different, the Distance values are more or less the same, but always reported in different order.

**Comment by CESARDELATORRE** [comment]
In order to get deterministic results with different trainings, the MLContext has to have the same seed.

Other than that, it is perfectly normal in machine learning that different trainings using the same algorithm and data might sometimes get different results.

Here you can read about the "seed" in generic machine learning (not just ML.NET):
https://www.quora.com/What-does-the-seed-value-actually-mean-in-machine-learning-algorithm

Still, this issue could be a different thing, but just in case, try the following:
 
You currently you have this code:

`private static MLContext mlContext = new MLContext();`

Can you try this line instead?:

`private static MLContext mlContext = new MLContext(seed:1);`

The seed could be any number you'd like for different deterministic results.

Also, once your sample is finished, please we'd love to point to it from our COMMUNITY SAMPLES page here, can you confirm we can do it? :) : 
https://github.com/dotnet/machinelearning-samples/blob/master/docs/COMMUNITY-SAMPLES.md

Thanks for your feedback! 👍

**Comment by PaulaScholz** [comment]
The sample is finished, published, and on the COMMUNITY SAMPLES page.
