### ISSUE TITLE
Custom gain argument for ranking: double[] in trainer, string in evaluator

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#3708]
The argument was recently changed to double[] in the ranking trainers, but is still a string in the ranking evaluator. We should be consistent.

**Comment by mstfbl** [comment]
In LightGBMRankingTrainer.cs, the custom gains argument is an int[] !! 

https://github.com/dotnet/machinelearning/blob/c703cfed0d876e833d1b9838d6371a64ad1184c1/src/Microsoft.ML.LightGbm/LightGbmRankingTrainer.cs#L127-L133

Now we have three different class types here. Seeing that all of the custom gain arrays recorded in the codebase consist of numerals without decimals, it makes sense to make these custom gain arguments of type int[]. What do you think @yaeldekel ?

**Comment by harishsk** [comment]
It seems like we have two options:
* Leave it inconsistent and fix in v2 when we can potentially accept breaking changes OR
* Add a new variable CustomGainsDouble and mark CustomGains as obsolete so that we discourage its use but still keep it usable in the current version. This approach makes the types consistent but makes the names inconsistent.

How about we create a new label called "api breaking change" and close the issue so that we can revisit such issues when we discuss a v2?

**Comment by harishsk** [comment]
@eerhardt / @yaeldekel Can you please share your thoughts on the above?

**Comment by mstfbl** [comment]
Thank you @harishsk for your suggestions. I will be closing this issue with the "API breaking change" label as one of the issues that can be addressed in Version 2.0 of ML.NET where we can accept API breaking changes.
