### ISSUE TITLE
libomp 8.0.0 version has dependencies that do no exist on macOS build machines

### ISSUE THREAD

**Issue by codemzs** [dotnet/machinelearning#3722]
It seems brew installing latest libomp has dependencies that do not exist on build machines. Investigate what those dependencies are by taking a trace and install them.

Related to #3694

**Comment by najeeb-kazmi** [comment]
We have taken a dependency on libomp version 7.0.0 rather than installing the latest version.
`brew install libomp` will install the latest version, which we do not want as it means testing and possibly updating ML.NET to be compatible with the latest version whenever a new version is released.

In homebrew, it is possible to install a specific version `brew install libomp@7.0.0` only if a "tap" is maintained for that formula for the specific version. Since this "tap" is not maintained, the way to install the specific version is to point to the specific commit in the homebrew repository corresponding to the correct version. This is what we have in our CI builds.
```
brew update && brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/f5b1ac99a7fba27c19cee0bc4f036775c889b359/Formula/libomp.rb && brew link libomp --force
```
