### ISSUE TITLE
Model summary to show tree details for FastTree

### ISSUE THREAD

**Issue by ganik** [dotnet/machinelearning#3755]
Currently model summary doesnt show trees and split points for FastTree models.
FastTree model needs to implement ICanGetSummaryAsIDataView that would dump this info.

**Comment by yaeldekel** [comment]
Hi @ganik ,
FastTree models implement `ICanGetSummaryAsIRow`, so it doesn't need to implement `ICanGetSummaryAsIDataView`. Either way, both these interfaces are internal and are not intended to be used programatically to get information about the model.
For getting information about the model, `FastTree` models have a public `TrainedTreeEnsemble` property, that returns an object that contains information about the tree ensemble: 
```
        public double Bias { get; }
        public IReadOnlyList<T> Trees { get; }
        public IReadOnlyList<double> TreeWeights { get; }
```
where `T` derives from `RegressionTreeBase` and contains information about a single tree.

**Comment by codemzs** [comment]
@ganik Can you please comment? if this needs to be fixed can you please confirm this can go in before 1.1 release next week?

**Comment by artidoro** [comment]
This issue pertains to Nimbus ML. In order to pass the model parameters to Nimbus ML the model parameters class has to implement `ICanGetSummaryAsIRow` or `ICanGetSummaryAsIDataView`.

`FastTree`  implements `ICanGetSummaryAsIRow` as Yael points out. However, it does not expose all the tree structure, it only exposes the gains.

We should implement `ICanGetSummaryAsIDataView` to pass all the information in TrainedTreeEnsemble to Nimbus (including the tree structure).

**Comment by artidoro** [comment]
My suggestion is to construct an `IDataView` where each tree in the ensemble is represented in its own row. Since Wei-Sheng did a lot of work to reduce down the list of public fields defining the trees, they should all be include in the `IDataView`, with each column corresponding to a different field.
