### ISSUE TITLE
How to get LightGBM multiclass calibrated

### ISSUE THREAD

**Issue by rauhs** [dotnet/machinelearning#3765]
Version: 1.0

After training the a multi class LightGBM predictor it seems the Platt calibrator on each model has the fixed parameter of 0, and -0.5:

https://github.com/dotnet/machinelearning/blob/3798bf8b73a2ce83a526326e05639d54a331fbdd/src/Microsoft.ML.LightGbm/LightGbmMulticlassTrainer.cs#L185-L191

Is that on purpose? How can I get a calibrated predictor?

**Comment by wschin** [comment]
This is a bug. We should follow [this computation](https://github.com/microsoft/LightGBM/blob/fc789e044a9bb2559c413905569677ec3e2ad07e/src/objective/binary_objective.hpp#L168) to consume [this parameter](https://github.com/dotnet/machinelearning/blob/3798bf8b73a2ce83a526326e05639d54a331fbdd/src/Microsoft.ML.LightGbm/LightGbmMulticlassTrainer.cs#L90) instead of using `-0.5`.

**Comment by wangyems** [comment]
Closing this issue because it has been fixed some point in the past.
