### ISSUE TITLE
An Exception about using CustomMappingFactory

### ISSUE THREAD

**Issue by seabluescn** [dotnet/machinelearning#3775]
Hello there,
I am learning about CustomMappingFactory, I found the following code: 
machinelearning/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/CustomMappingSaveAndLoad.cs
This code runs normally, but if I create a new MLContext before loading the model (line 36), as follows: 

mlContext = new MLContext();
var loadedTransform = mlContext.Model.Load("customTransform.zip", out var inputSchema);

Then the system will report an error: 
InvalidOperationException: Unable to locate an extension for the contract 'IsUnderThirty'. Ensure you have called ComponentCatalog.RegisterAssembly with the Assembly that contains a class decorated with a 'Microsoft.ML.Transforms.CustomMappingFactoryAttributeAttribute'.

I think creating a new MLContext before loading the model should be a necessary operation. Is this a bug?

**Comment by yaeldekel** [comment]
Hi @seabluescn, thank you for your interest in ML.NET.
It is true that in most scenarios you would need a new `MLContext` when loading a model. In order to be able to find the mapping when the `CustomMappingTransformer` is loaded, you need to register the assembly where it is defined with the attribute mentioned in your error message. Have you tried adding [line 32](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/CustomMappingSaveAndLoad.cs#L32) in the sample to your code?

```
            mlContext.ComponentCatalog.RegisterAssembly(typeof(IsUnderThirtyCustomAction).Assembly);
```
Please let me know if this works, and if so we can close this issue.

**Comment by seabluescn** [comment]
Hello @yaeldekel ,thank you for your reply. I have already registered this assembly. The code will throw an exception when saving the model if I don't registered it. Then, it can be saved, but the same MLContext object must be used when loading the model file. We can't create a new MLContext object to load the model file.
I have written a project, please help me to take a look.
https://github.com/seabluescn/Study_ML.NET/tree/master/MulticlassClassification_Mnist
Thank you!

**Comment by seabluescn** [comment]
This is my Main Function:
        static void Main(string[] args)
        {
            MLContext mlContext = new MLContext(seed: 1);          
            TrainAndSaveModel(mlContext);
            TestSomePredictions(mlContext);           
            Console.ReadKey();
        }
I want to create a new MLContext object inside the TrainAndSaveModel and TestSomePredictions method.

**Comment by antoniovs1029** [comment]
As @yaeldekel has pointed out, you need to register the assembly in the `MLContext` you are using to load the model, it doesn't matter if it's a different MLContext from the one you used when saving the model.

So, to show it, I've modified your main function as follows and it's worked just fine:
```
static void Main(string[] args)
{
    MLContext mlContext = new MLContext();
          
    TrainAndSaveModel(mlContext);

    MLContext mlContext2 = new MLContext();
    mlContext2.ComponentCatalog.RegisterAssembly(typeof(DebugConversion).Assembly);

    TestSomePredictions(mlContext2);
}
```

Alternatively, you could also make a new MLContext inside your test function, and use it, as long as you also register the assembly:

```
        private static void TestSomePredictions()
        {
            var mlContext = new MLContext();
            mlContext.ComponentCatalog.RegisterAssembly(typeof(DebugConversion).Assembly); 
```

I will close this issue, since it's been some months since it was opened, and it seems that the questions has been answered. Please, @seabluescn , if you still find there's a problem, feel free to reopen this issue and leave a comment about it. Thanks.

**Comment by ArrowRaider** [comment]
You have to put the register code on the loading side too?  That is terrible.  How are we supposed to do that when using a PredictionEnginePool?

services.AddPredictionEnginePool<Input, Output>().FromFile("whatever.zip", false);
