### ISSUE TITLE
Equivalent of SVM.SVC of slkearn

### ISSUE THREAD

**Issue by writetokavitha** [dotnet/machinelearning#3845]
We use the following from sklearn for training our model for multi-class text classification
What would be the equivalent in ML.Net ?

clfsvm = Pipeline([('vect', CountVectorizer(tokenizer=tokenize, lowercase=True, stop_words=stop_words, ngram_range=(2,2))),
                          ('tfidf', TfidfTransformer(use_idf = False)),
                             ('clf', SVC(kernel = 'linear', probability = True)),])
clfsvm.fit(df_train, df_label)

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html

**Comment by yaeldekel** [comment]
Hi @writetokavitha,
The equivalent of `CountVectorizer` in ML.NET is the `ProduceWordBags` transformer, [here](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Transforms/Text/TextCatalog.cs#L352) or [here](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Transforms/Text/TextCatalog.cs#L381).

The `SVC` estimator looks like a wrapper around the libsvm package which ML.NET currently does not have. But since you are using a linear kernel, you can use any of ML.NET's linear estimators instead.

**Comment by antoniovs1029** [comment]
Hi, @writetokavitha . It seems your question has already been answered. I will then close this issue. Please feel free to reopen it in case you still have further questions.
