### ISSUE TITLE
Question: Feature weights (importance) for LightGBM

### ISSUE THREAD

**Issue by jonataspc** [dotnet/machinelearning#3847]
The documentation https://github.com/dotnet/machinelearning/blob/master/docs/code/MlNetCookBook.md#i-want-to-look-at-my-models-coefficients shows a way to get the feature importance, but when I try to use the code samples I got an error in the "LastTransformer" saying it was not found in the TTransformer class. 

I looked at the samples but I could not find a code example. I am using LightGBM.   
The issue https://github.com/dotnet/machinelearning/issues/576 is related but the replies did not helped as well.

Any hints?

**Comment by yaeldekel** [comment]
Hi @jonataspc, could you share the code, and the version of ML.NET that gave you an error?
When I tried the code in the cookbook you shared above, and changed the last component in the pipeline to be:
```
mlContext.BinaryClassification.Trainers.LightGbm()
```
instead of `SdcaCalibrated` I was able to write the next line without any errors:
```
var modelParameters = trainedModel.LastTransformer.Model;
```
The type of `modelParameters` was `CalibratedModelParametersBase<LightGbmBinaryModelParameters, PlattCalibrator>`.

**Comment by jonataspc** [comment]
Hi @yaeldekel, thank you for the reply.
The code is available on https://github.com/jonataspc/CobrancaML
Basically it was generated by the machine learning wizard (based on the https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/BinaryClassification_SentimentAnalysis sample) and I've simplified it a little bit.  

I got the `LastTransformer` working, but I now have a problem in the `Model` reference... 
Maybe I need a new assembly reference? 
Thank you.

**Comment by yaeldekel** [comment]
Hi @jonataspc, I am assuming that you already have the LightGBM binaries installed, since you are able to train without any problems, so I don't think it is an assembly reference issue. What is the error that you get about `Model`?
The model produced by the multi class LightGBM trainer is a One-vs-All model containing a tree ensemble for every class to classify it vs. the rest of the classes, could this be the reason for the error you are seeing? Are you trying to cast the model into a certain type?

**Comment by jonataspc** [comment]
Hello @yaeldekel ,

The error is that `Model` is not found in `LastTransformer`:
var modelParameters = mlModel.LastTransformer.Model;

Error description:
_"'TransformerChain<KeyToValueMappingTransformer>' does not contain a definition for 'Model' and no accessible extension method 'Model' accepting a first argument of type 'TransformerChain<KeyToValueMappingTransformer>' could be found (are you missing a using directive or an assembly reference?)	"_

I think it may be related to how the pipeline is built... Still trying to get the features' weights.

**Comment by jonataspc** [comment]
Solved. I changed the classifier to binary (instead of multiclass) classification.
