### ISSUE TITLE
Multi class LR behaves differently on .NetCore 3.0

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#3856]
Four tests are failing on the .NetCore 3.0 builds:
`EnsemblesMultiAveragerTest`
`EnsemblesMultiClassBootstrapSelectorTest`
`EnsemblesMultiVotingCombinerTest`
`EnsemblesMultiStackCombinerTest`

The difference in the baselines is something like this:
`L1 regularization selected 13 of 15 weights.` vs.
`L1 regularization selected 11 of 15 weights.`

**Comment by frank-dong-ms** [comment]
Investigating now, caused by different version of CPUMath gives slightly different result

**Comment by frank-dong-ms** [comment]
The difference comes from CPUMath using different instruction set:
  1. net framework and net core 2.1 uses CpuMathUtils.netstandard that uses SSE instruction set;
   2. net core 3.1 uses CpuMathUtils.netcoreapp that uses AVX, SSE or direct floating point calculation depending on hardward avaibility.
AVX and SSE generates slightly different result due to nature of floating point math.
Use below issue to track: https://github.com/dotnet/machinelearning/issues/5044

**Comment by frank-dong-ms** [comment]
created separate baseline for netcore app 31
