### ISSUE TITLE
Multiclass LightGBM bug

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#3878]
LightGBM trainer has two non-readonly fields called `_numClass` and `_tlcNumClass`. The second one is used to determine the number of predictors in the OVA predictor. However, the value of `_tlcNumClass` is only updated once, so if `Fit` is called again on the same estimator, it might give the wrong number of classes.

**Comment by antoniovs1029** [comment]
I've just taken a quick look to this. To do it, I modified the [Multiclass LightGbm sample](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LightGbm.cs), and added code so to Fit again the pipeline with a dataview that has labels 1-4 (whereas the original dataview used for fitting the pipeline the first time, used labels 1-3). As a result, when fitting again the pipeline _tlcNumClass was still set to be "3" (instead of 4), and when printing the metrics, only 3 labels where taken into account, ignoring the last one.

I believe this is the issue @yaeldekel is describing, right?

If this is the issue, wouldn't this be solved by simply moving the initialization of _tlcNumClass out of [this if statement,](https://github.com/dotnet/machinelearning/blob/d306ac8d66a8e4e9f82d3897d1d52cb5d93acab7/src/Microsoft.ML.LightGbm/LightGbmMulticlassTrainer.cs#L221) so that it would always be initialized when fitting the pipeline?

**Comment by justinormont** [comment]
What does calling `Fit()` twice do? 

If it's not LightGBM's [task=refit](https://github.com/Microsoft/LightGBM/issues/1473#issuecomment-399618342), can we expose it?

This may serve the needs of AutoML, which is looking for streamable trees. This would let us fit the tree structure on ~10 to 100GB of data, then stream the whole dataset (TBs) to refit the leaf node values. There's a similar option by using TreeFeat + linear model.
/cc @daholste

**Comment by yaeldekel** [comment]
The estimators are intended to be stateless, so calling `Fit()` twice should produce exactly the same result as defining two estimators and calling `Fit()` once on each of them (except, perhaps, for any randomness used during training).
Regarding LightGBM refit, is it capable of doing something that cannot be done using TreeFeat + linear model? If the answer is yes, could you open a new issue for it?
