### ISSUE TITLE
Guidance on simple binaryclassification

### ISSUE THREAD

**Issue by famschopman** [dotnet/machinelearning#3897]
Trying to get a very simple binary classification to work. And while I feel I am just touching on the ABC's I am running into various issues. This shouldn't be rocket science.

The issue I get is "Schema mismatch for feature column 'Features': expected Vector<Single>, got Vector<String>
Parameter name: inputSchema"

To make sure the classification would work I made sure the Label column that I want to eventually predict is a boolean type. (I couldn't find clear docs on why the label column was needed but I assumed the training requires a single potential target for predictions which is the label, and if you want to predict other properties you need to train a model specifically for that property).

I also made sure I transformed the string property first. 

```csharp
        public class Employee
        {
            [LoadColumn(0)]
            public float Age { get; set; }
            [LoadColumn(1), ColumnName("Label")]
            public bool Attrition { get; set; }
            [LoadColumn(2)]
            public string BusinessTravel { get; set; }
            [LoadColumn(3)]
            public float DailyRate { get; set; }
        }

        public ActionResult Turnover()
        {
            MLContext mlContext = new MLContext();

            var _appPath = AppDomain.CurrentDomain.BaseDirectory;
            var _dataPath = Path.Combine(_appPath, "Datasets", "attrition_small_dataset.csv");
            IDataView dataView = mlContext.Data.LoadFromTextFile<Employee2>(_dataPath, separatorChar: ',', hasHeader: true);

            var categoricalEstimator = mlContext.Transforms.Categorical.OneHotEncoding("BusinessTravel");
            IDataView transformedData = categoricalEstimator.Fit(dataView).Transform(dataView);
            
            string[] featureColumnNames =
                dataView.Schema
                    .Select(column => column.Name)
                    .Where(columnName => columnName != "Label").ToArray();

            IEstimator<ITransformer> dataPrepEstimator = mlContext.Transforms.Concatenate("Features", featureColumnNames);
            IDataView preprocessedTrainData = dataPrepEstimator.Fit(dataView).Transform(dataView);

            var sdcaEstimator = mlContext.BinaryClassification.Trainers.SdcaLogisticRegression();
            var sdcaModel = sdcaEstimator.Fit(preprocessedTrainData);

            return View("Turnover");
        }
```

**Comment by wschin** [comment]
Could you please find which line threw that error?

**Comment by najeeb-kazmi** [comment]
@famschopman you are seeing this because you are fitting `dataPrepEstimator` on `dataView`, which has the schema of the original data, specifically "BusinessTravel" is still a string. So you are trying to concatenate "Age" (float), "BusinessTravel" (string), and "DailyRate" (float) into one column "Features". 

You should instead fit this on `transformedData`, where "BusinessTravel" has been correctly featurized with the `OneHotEncoding` transform.

Also, it would be a good idea to get `featureColumnNames` from `transformedData` rather than `dataView`. Not that it would make a difference here. It's just good practice just in case you had renamed a column in an earlier transformation (so the next transformation would not have that feature name).

**Comment by najeeb-kazmi** [comment]
@famschopman I'm closing this issue. Please feel free to reopen if you are still getting this error.
