### ISSUE TITLE
Missing or incorrect dependencies in generated code

### ISSUE THREAD

**Issue by taffmak** [dotnet/machinelearning#3964]
### System information

- **OS version/distro**:
- **.NET Version (eg., dotnet --info)**: 

### Issue

- **What did you do?**
Added machine learning to a .net core console project.
Followed the training to generate a model and added the projects to my solution.
(Note: when I created the solution I opted for solution and project in same folder)
- **What happened?**
Many Build Errors:
2>MLConsoleL1ML.ConsoleApp\ModelBuilder.cs(11,17,11,19): error CS0234: The type or namespace name 'ML' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

- **What did you expect?**
1. Generated code to build.
2. Generated code to work.

- **What I tried to resolve it**
Installed nuget package Microsoft.ML

- **Then what happened?**
Even more errors:
2>MLConsoleL1ML.Model\obj\Debug\netcoreapp2.1\MLConsoleL1ML.Model.AssemblyInfo.cs(14,12,14,54): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute

in addition to the previous errors

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by LeRobert** [comment]
In addition to these errors, I am getting the following one, due to unhandled regional format differences:

Error	CS0747	Invalid initializer member declarator	MLApp2, MLApp2ML.ConsoleApp	C:\...\MLApp2ML.ConsoleApp\ModelBuilder.cs	59	Active

From ModelBuilder.cs, line 59:

var trainer = mlContext.BinaryClassification.Trainers.SgdCalibrated(new SgdCalibratedTrainer.Options() { L2Regularization = 1E-05f, ConvergenceTolerance = 0, **01f**, NumberOfIterations = 10, Shuffle = true, LabelColumnName = "Sentiment", FeatureColumnName = "Features" });

My regional format is Slovenian (Slovenia). We are using the comma as the decimal separator.

**Comment by mstfbl** [comment]
Hey @taffmak , can you share the problematic code you have here?

**Comment by taffmak** [comment]
Sorry, that was something I did 6 months ago playing around. Haven't touched it since!

**Comment by harishsk** [comment]
In that case, I will close the issue for now. Please feel free to reopen it with more details in case you to return to the problem.
