### ISSUE TITLE
Use Vector<Byte> as Features

### ISSUE THREAD

**Issue by NektoDron** [dotnet/machinelearning#3969]
Can I use bytes in the Futures vector for binary classification?

I tried to make scheme like this
```
            var scheme = SchemaDefinition.Create(typeof(PredictionData));
            scheme["Preview"].ColumnType = BooleanDataViewType.Instance;
            scheme["Preview"].ColumnName = "Label";
            scheme["Probability"].ColumnType = NumberDataViewType.Single;
            scheme["Features"].ColumnType = new VectorDataViewType(NumberDataViewType.Byte, size);
```

But after calling trainingPipeline.Fit I get an exception
`System.ArgumentOutOfRangeException: 'Schema mismatch for feature column 'Features': expected Vector<Single>, got Vector<Byte>`

If I use Single, it will take 4 times more memory for the data.

**Comment by wschin** [comment]
You cannot use `Byte` unless your feature values are categorical such as "Good", "Fine", and "Bad". In most cases, ML.NET doe not load the whole data set into your memory but process it in a streaming manner. Maybe we don't need to worry this too much?

**Comment by NektoDron** [comment]
I must first calculate the data and store it in memory as a float. Or can I store them as bytes to transform them into float?

**Comment by wschin** [comment]
You need to save them as float because ML.NET doesn't directly support byte-to-float conversion. 

If you really want to write your own caster, ML.NET has a custom transform where you basically can do everything C# can do. [Here](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/CustomMappingWithInMemoryCustomType.cs) is an example.
