### ISSUE TITLE
Consider adding machinelearning-samples ConsoleHelper funcitonality 

### ISSUE THREAD

**Issue by colbylwilliams** [dotnet/machinelearning#4042]
Several of the samples in the [machinelearning-samples](https://github.com/dotnet/machinelearning-samples) repo make extensive use of a shared [ConsoleHelper](https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/common/ConsoleHelper.cs) to visualize the data or metrics.  Consider exposing the functionality provided by the ConsoleHelper class inside ML.NET itself.  For example, expose as static methods on the corresponding metrics objects returned by Evaluate, as well as IDataView and Preview.

**Comment by harishsk** [comment]
The samples have already aggregated their console functions into the shared ConsoleHelper.cs class. I am not sure there is much value in integrating this into the framework because the format the samples repo has chosen for its sample output may not be suitable for the users of the framework. 
If however you are looking for generic ways to dump C# objects to the console you can look at extracting string representations of the object by serializing them into JSON or YAML and printing that string to the console.
