### ISSUE TITLE
What type is the input model file

### ISSUE THREAD

**Issue by nfnpmc** [dotnet/machinelearning#4063]
The model input file is
Microsoft.ML.SamplesUtils.DatasetUtils.DownloadTensorFlowSentimentModel().
Is this a zip, a graph , or what? 
Does it contain pretrained weights?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3459698d-76c3-c04b-de13-edafd11d8859
* Version Independent ID: 0aa1e091-1935-850b-af62-c1f14a7bc6fc
* Content: [TensorflowCatalog.LoadTensorFlowModel(ModelOperationsCatalog, String) Method (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.tensorflowcatalog.loadtensorflowmodel?view=ml-dotnet#Microsoft_ML_TensorflowCatalog_LoadTensorFlowModel_Microsoft_ML_ModelOperationsCatalog_System_String_)
* Content Source: [dotnet/xml/Microsoft.ML/TensorflowCatalog.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/TensorflowCatalog.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by najeeb-kazmi** [comment]
@nfnpmc the [downloaded model](https://github.com/dotnet/machinelearning-testdata/tree/master/Microsoft.ML.TensorFlow.TestModels/sentiment_model) is in the [`SavedModel`](https://www.tensorflow.org/guide/saved_model) format. There is a `saved_model.pb` file, and a `variables` folder containing the pre-trained weights.

**Comment by hjoshuaj** [comment]
@najeeb-kazmi The model looks like it is in the `SavedModel` format, but I am having a hard time recreating it from TensorFlow.  Here is my [inquiry](https://stackoverflow.com/questions/64794378/correct-pb-file-to-move-tensorflow-model-into-ml-net) on StackOverflow.  Basically if I save a model from TensorFlow in the `SavedModel` format, it looks really weird (sometimes having only one node) and will not pull into ML.NET correctly since the input and output nodes are used.  Do you have a suggestion?
