### ISSUE TITLE
Conversion.TryParse parses floats and doubles with empty/whitespace values as 0 instead of NaN

### ISSUE THREAD

**Issue by Dmitry-A** [dotnet/machinelearning#4132]
This is done for historical reasons since there are clients that depend on this behavior, so it's not a bug.  Nevertheless, if we don't control the input dataset format this would produce signal loss since empty/whitespace values are now indistinguishable from value "0".  We can fix that in AutoML by inserting a transform that addresses the issue but a much better fix would be to change the loader behavior.

**Comment by justinormont** [comment]
I agree. The dataset has missing values and the missing values are best represented as `NA` values. 

As you mention, this is currently a loss of signal. When the missing value is important, we will not be able to tell `0` from `NA`, which causes a drop in accuracy. 

The user can fill the `NA` values with the standard `NAHandle` / `NAIndicator` transforms.

If we want this as non-breaking change, we could add a TextLoader flag `impute=true` which by default keeps the current behavior. Then on the next release we can default to `false`.

**Comment by codemzs** [comment]
We use "?" to represent missing values in Text Loader.

**Comment by justinormont** [comment]
Correct. The user can use "?" to represent missing values, but the majority of datasets represent missing values with either blank values `1,,2` (note the double ,, w/ a missing value between), or sometimes white space `1, ,2`.

**Comment by mathias-brandewinder** [comment]
I assume this issue refers to `LoadFromTextFile` silently converting missing/blank values in a CSV file to `0`. It really doesn't seem like a good default choice, I was very surprised to observe that behavior, and only caught it by chance.

Besides modifying the source data, replacing `,,` with `,?,` at the source, is there a clean way to address that issue and read `,,` as `NaN`?

**Comment by antoniovs1029** [comment]
Hi, @mathias-brandewinder sorry for the late response. As of now, I don't think there's any way to fix this except by adding a `?` into the missing values in your dataset.

On the other hand, I wonder if this behavior is done so that this matches the behavior of missing values on sparse datasets, where missing values are assumed to be 0 (the default).

In any case, I think that changing this behavior for Conversions.TryParse() wouldn't change the behavior of sparse datasets, so it might be safe to do this... although I wonder where else could Conversions.TryParse() from TX to R4/R8 be used aside from the TextLoader 😕 

So yeah, perhaps adding an imputer option to the TextLoader, as suggested by @justinormont might be the best solution.

**Comment by antoniovs1029** [comment]
For the record, there's this piece of internal documentation which is relevant to this issue, but that (as I'll show in the experiment below) I think it's mistaken, and it doesn't refer to current ML.NET behavior.

The MAML docstring says the following for the AllowQuoting option in TextLoader, and having empty values (notice the part of empty values isn't mentioned in the public docs for this option):

https://github.com/dotnet/machinelearning/blob/85f8eaa8d52611fb4323036a5e16bc96c55cc3c5/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs#L434-L441

If I load the following CSV with AllowQuoting = true
```
id,description,num1,num2
0,"this is a description",0.12,0.34
,"this has an empty Id", 1.111, 11.1111
2,"this has an empty num1",,2.222
3,"this has an empty quoted num1","",3.333
4,"this has an empty num2",4.4444,
5,"this has an empty quoted num2",5.5555,""
6,"this has an empty num2, without the last separator",6.666
```

num1 from row 2 and row 3 actually gets loaded as 0 instead of NaN (which is what I would have expected from the docstring which says that consecutive separators (i.e. unquoted empty field) gets loaded as missing instead of empty.
