### ISSUE TITLE
MinDocsPerLeaf always zero for Microsoft.ML.Runtime.FastTree.DataConverter.DiskImpl

### ISSUE THREAD

**Issue by mjmckp** [dotnet/machinelearning#414]
Of the two implementations of `Microsoft.ML.Runtime.FastTree.DataConverter`, the `minDocsPerLeaf` argument is used by `MemImpl`, but not `DiskImpl`, where this argument to `CalculateBins` is hardwired to zero:
https://github.com/dotnet/machinelearning/blob/ecc6857410f56cdc67c666de4e08844df3a1e288/src/Microsoft.ML.FastTree/FastTree.cs#L1435

Is this intentional? Shouldn't the two implementations give the same result?

**Comment by TomFinley** [comment]
There are two results we might care about in this context: returns the same internal representation of a dataset (which is what we're talking about here), vs. gives the same model. So long as we achieve the latter (up to the influence of numerical imprecision), I don't care terribly much about the former, since it doesn't represent anything anyone will see anyway. It might be nice if they for-sure gave the same dataset, but I'm not sure that it's required. 

There are in fact two ways in which the memory implementation has information that the disk based preparaed does not have: the first being, it cannot be configured to have flocks (because originally the disk based procedure did not support flocks at all), and the second it doesn't get this min-docs-per-leaf value.

The internal representation of a dataset is to transmute a dataset into a per-feature structure, where the features are discretized (e.g., if you had a feature with values `{-1.2, -1.1, -0.9, -0.5, -0.2, 0, 0.1, 0.4, 0.5}`, and you discretized into 3 bins, it *might* choose to map the values into `{0, 0, 1, 1, 2, 2}`, with the bins covering the ranges `-inf, -0.1`, then `-0.1, 0.25`, then `0.25, inf`). The effect of this discretization is that the split points can only happen at those split boundaries.

A fair amount of optimization can be done here, two of which are relevant for this discussion:

1. Under certain conditions, it is possible to store and calculate *multiple* features, in a *single* pass (what I called the "feature flocks" trick, which I should probably write up). The result is computationally equivalent to storing the individual features, but is much faster.

2. When discretizing, if in the start or tail of a discretization you have bins that are fewer than the min-docs-per-leaf, there is absolutely no point in storing those bins, since you could never choose them anyway. So: if you had 2 docs in bin 0, and 3 in bin 1, but your min-docs-per-leaf was 6, one may as well collapse bins 0, 1, and 2 together *anyway*, since you could never choose the 0-1 or 1-2 bin transtiion as the split point.

Both of these have some effect on runtime, but do not effect the actual result of training. So why not write the optimization for disk -- mostly because, from what I've seen very few people actually use the disk based algorithm. So given limited time, I didn't consider the disk based scenario enough to optimize, given other competing priorities.

I'm not even entirely confident that the disk-based algorithm doesn't differ in other ways.

**Comment by codemzs** [comment]
LightGBM was actually derived from FastTree. Also FastTree may be slower but there are some case studies where it has higher accuracy.
