### ISSUE TITLE
Should use dll location instead of app domain in ResNet18/50/128 packages

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning#4173]
We find out that in  `Resnet18Extension.cs`, It uses `AppDomain.CurrentDomain` to get the DLL location, which could causes some unexpected behavior in Vsix packaging. (in Vsix AppDomain.CurrentDomain returns VS executables, which is `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE`, so it won't be able to find the right onnx file). It's better to use `GetAssembly.Loaction` to get the DLL location. You can see the following PR to see the suggest fix

#4174

**Comment by eerhardt** [comment]
We used to use `Assembly.Location` but that was changed in #2411.  See the history of that file for all the changes that have gone into it.

You can easily call the overload that takes a `modelDir` inside a VSIX to point to the correct place where you are installing the onnx file. You won't need to change ML.NET in order to do that:

https://github.com/dotnet/machinelearning/blob/b0048716190b754eb994db310aaf46feddf2efca/src/Microsoft.ML.DnnImageFeaturizer.ResNet18/ResNet18Extension.cs#L31-L37
