### ISSUE TITLE
Ignored columns appear in InputModel from CodeGenerator

### ISSUE THREAD

**Issue by tbombach** [dotnet/machinelearning#4224]
### System information

- **OS version/distro**: Any
- **.NET Version (eg., dotnet --info)**:  Any

### Issue
When the user specifies ignored columns for CodeGenerator, they should not appear in the InputModel (or PredictProgram output). If the user uses the generated code to train the model again, they will have a different input set and generated model than the first training session.

**Comment by tbombach** [comment]
PR: https://github.com/dotnet/machinelearning/pull/4220

**Comment by frank-dong-ms** [comment]
--summary of non-github discussion--

I'd recommend leaving the generation of the unused (Ignore) column in place. I think what you're purposing is "ignore the entire existence of the column" vs. the current "just don't use it for featurization".

Generally columns are ignored by the AutoML heuristics. These, while generally good, are imperfect. This leads to AutoML ignoring columns which could be useful.

Removing the column from the input class makes the column no longer appear in the IDataView, which means users won't be able to easily add back the missing column.

When the user explicitly ignores a column, it's often done due to the column leaking the label. When ignoring a column from the CLI, after CodeGen, the user can handle this column without leaking.
