### ISSUE TITLE
ScoreTensorFlowModel fails with null reference exception

### ISSUE THREAD

**Issue by meesoft** [dotnet/machinelearning#4288]
### System information

- Win10 64bit
- .net 4.6.1
- Microsoft.ML.TensorFlow 1.3.1

### Issue

- **What did you do?**
Used LoadTensorFlowModel and ScoreTensorFlowModel on a pretrained model
- **What happened?**
ScoreTensorFlowModel fails with null reference exception
- **What did you expect?**
pipeline object

### Source code / logs
```
var estimator = mlContext.Model.LoadTensorFlowModel("saved_model.pb");
Console.WriteLine("Inputs: " + string.Join(";", estimator.GetInputSchema().Select(c => c.Name)));
var pipeline = estimator.ScoreTensorFlowModel(
    new[] { "denoised" },
    new[] { "is_training", "noisy" }, addBatchDimensionInput: true);
```

[saved_model.zip](https://github.com/dotnet/machinelearning/files/3687784/saved_model.zip)

**Comment by harishsk** [comment]
@meesoft  Sorry for the delayed response. I tried your sample code and model on the latest release of ML.NET v1.5 and have not been able to reproduce the issue. I saw a different file sharing exception while the resources were being cleaned up, but that can be easily fixed by adding an estimator.Dispose() at the end of your code.

If this is still an issue for you, can you please reopen the issue with a more complete code sample and call stack?
