### ISSUE TITLE
why binning is importance in binary classification?

### ISSUE THREAD

**Issue by nighotatul** [dotnet/machinelearning#4303]
@eerhardt - when i have studied binning is one of the method to represent numeric data into the group of data.as per studied which numeric column have unique value that data taken into binning as consider.
if this true then unique value is more then that numeric column does not consider as binning process.
consider heart attack prediction(for data:https://towardsdatascience.com/heart-disease-prediction-73468d630cfc)
in that we calculate binning for age but we cannot calculate for Resting Blood Pressure
how we calculate number bins in numeric column and which numeric column has been consider for binning process?

**Comment by eerhardt** [comment]
I don't know the answer. Maybe someone on @dotnet/mlnet-core might?

You can also try searching the internet, or possibly asking a question on stackoverflow.

**Comment by nighotatul** [comment]
@eerhardt - Please assign to mlnet-core team and we search on internet also.

**Comment by codemzs** [comment]
@nighotatul In addition to what you mentioned binning is needed because our feature vectors is of float type and have continuous values, hence for performance reasons at least we need to bin features to reduce the cardinality. You can read more on binning [here ](https://en.wikipedia.org/wiki/Data_binning) and please also checkout out following samples on binnding, [normalized binning transform](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/NormalizeBinning.cs), [supervised normalized binning transform](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/NormalizeSupervisedBinning.cs) and if you need more details you can browse through the source code as well, for example for fast tree decision tree you can see here how [bins ](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.FastTree/BinFile/BinFinder.cs)are  calculated.
