### ISSUE TITLE
Can't find label when file header start with #

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning#4339]
Using VS 2019 (16.2.5).

I selected the multi-class classification scenario and used the [iris-train.txt dataset](https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/MulticlassClassification_Iris/IrisClassification/Data/iris-train.txt). I had to change "#Label" column header to "Label" for it to Train properly.

![image](https://user-images.githubusercontent.com/10437687/66523316-82b5cf00-eaa4-11e9-8ccd-654341964ed9.png)

**Comment by LittleLittleCloud** [comment]
I believe it's because `dataloader` ignore the line start with `#` and treat it as comment, (I just take a quick glance at `dataloader` so I might be wrong, fix me as you wish), which is kind of wield for `ModelBuilder`, (because we don't have to keep record of parser information in data file). It might be better to consider using more complex annotation for comment/special information in data loader, as `#` is quite widely used.

**Comment by codemzs** [comment]
Text loader has an option to include/exclude header

**Comment by LittleLittleCloud** [comment]
Cool, thanks for the reply
