### ISSUE TITLE
Data file locked even after TextLoader goes out of context

### ISSUE THREAD

**Issue by kik3r** [dotnet/machinelearning#4361]
### System information
Microsoft Windows [Version 10.0.18363.418]
.NET framework 4.8
Microsoft.ML- 1.4.0-preview2
Microsoft.ML.AutoML - 0.16.0-preview2

### Issue

In the code attached, Trainset.csv is locked even after the MLTrain() method completes execution.
surprisingly, Testset.csv is not locked.

[Program.txt](https://github.com/dotnet/machinelearning/files/3753250/Program.txt)

**Comment by eerhardt** [comment]
@kik3r - I was not able to reproduce your issue using the Program.txt. I didn't have the `TrainSet.csv` and `TestSet.csv` files, so I used an iris data set instead.

Would it be possible to share a complete repro of the issue? (all test and training files)

**Comment by eerhardt** [comment]
@kik3r provided me a project that reproduced the issue. I traced the problem down to this section of code that is not disposing the cursor:

https://github.com/dotnet/machinelearning/blob/0b20a998d8ac752ac076859d23c32bb1956175d1/src/Microsoft.ML.AutoML/DatasetDimensions/DatasetDimensionsUtil.cs#L67-L79

Because the cursor is not being disposed, the underlying FileStream is not being disposed, and is being held open by a background thread trying to read from a BlockingQueue. This background thread never gets stopped, so the file never gets closed.
