### ISSUE TITLE
problems with retraining model

### ISSUE THREAD

**Issue by apilatau** [dotnet/machinelearning#4469]
### System information

- **Windows10**:
- **Microsoft.NetCore.App(2.1.0)/Microsoft.ML(1.4.0)**: 

### Issue 
it is observed
**System.ArgumentOutOfRangeException:** '_Features column 'Feature' not found by_  <mlContext.Model.CreatePredictionEngine> _call after retraining the model_
 
- **What did you do?**
We need to retrain a model with small increment of data in comparison with previously retrained dataset based on the example project **TaxiFarePrediction** https://github.com/dotnet/machinelearning-samples based on the steps, described in on the page https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/retrain-model-ml-net
We have undertaken the following steps to retrain the model with small increment (10 rows addition, as example) of data:
1) rewrite the function `BuildTrainEvaluateAndSaveModel` in order to save datapreparation pipeline and trained model
` var dataPrepTransformer = trainingPipeline.Fit(trainingDataView);
IDataView predictions = dataPrepTransformer.Transform(testDataView);
var sdcaEstimator = mlContext.Regression.Trainers.Sdca();
RegressionPredictionTransformer<LinearRegressionModelParameters> trainedModel = sdcaEstimator.Fit(predictions);
mlContext.Model.Save(dataPrepTransformer, trainingDataView.Schema, Data_PreparationModelPath);
 mlContext.Model.Save(trainedModel, predictions.Schema, ModelPath);
`
2) load pretrained model 
`var dataPrevPipeline = mlContext.Model.Load(Data_PreparationModelPath, out var dataPrepPipelineSchema);
ITransformer trainedModel = mlContext.Model.Load(ModelPath, out modelSchema);`

3) Extract pretrained model parameters
` LinearRegressionModelParameters originalModelParameters =
                ((ISingleFeaturePredictionTransformer<object>)trainedModel).Model as LinearRegressionModelParameters;`
4) and finally, retrain model just only with small obfuscated data. It doesn't matter what, but it matter the amount in comparison with the whole previous dataset 
```
TaxiTrip[] newTaxiTripsData = new TaxiTrip[10];
 for (var i = 0; i < 10; i++)
 {
      newTaxiTripsData[i] = new TaxiTrip()
      {
                    VendorId = "VTS",
                    RateCode = "1",
                    PassengerCount = 1,
                    TripTime = 1140,
                    TripDistance = 3.75f,
                    PaymentType = "CRD",
                    FareAmount = 0 // To predict. Actual/Observed = 15.5
                };
        }

IDataView newData = mlContext.Data.LoadFromEnumerable<TaxiTrip>(newTaxiTripsData);            
 // Preprocess Data
 IDataView transformedNewData = dataPrevPipeline.Transform(newData);
 // Retrain model
 RegressionPredictionTransformer<LinearRegressionModelParameters> retrainedModel =
 mlContext.Regression.Trainers.OnlineGradientDescent("Label", featureColumnName: "Features")
                .Fit(transformedNewData, originalModelParameters);
mlContext.Model.Save(retrainedModel, modelSchema, ModelPathAfterRetrain);
```

- **What happened?**
When we had a go at testing a single prediction, the call of creating prediction engine 

```
ITransformer trainedModel = mlContext.Model.Load(ModelPathAfterRetrain, out modelSchema);

var predEngine = mlContext.Model.CreatePredictionEngine<TaxiTrip, TaxiTripFarePrediction>(trainedModel); 
```
<---_this call_

throws a _System.ArgumentOutOfRangeException_ - Features column 'Feature' not found by_  <mlContext.Model.CreatePredictionEngine>

Could you ask what wrong I did with the retraining?
Thankful in advance,
Alex

- **guessworks**
1) I have a feeling that something wrong with my trained model files  `model_after_retrain.zip` and the same `model.zip` which was saved after datapreparation pipeline and has significant smaller size `data_preparation_pipeline.zip`
https://github.com/apilatau/retraining-example/tree/master/TaxiFarePrediction/MLModels
2) Maybe, increment / ingection of small amount of data in previously trained  model is impossible at all and we have to retain the model every time from scratch with sufficient data set ( I have investigated the count is about thousands rows, but not 10 

### Source code / logs
https://github.com/apilatau/retraining-example/blob/master/TaxiFarePrediction/TaxiFarePredictionConsoleApp/Program.cs
Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by harishsk** [comment]
In the function BuildTrainEvaluateAndSaveModel():

The first trainining pipeline consists of the data prep transformers and Sdca estimator. The data prep transformer is saved at the Data_PreparationModelPath and contains the necessary data transformations to convert the TaxiTrip data to something usable by the Sdca estimator. The pipeline used to create trainedModel however only has the Sdca estimator without the transformers used to transform the data. So trainedModel operates not on the original TaxiTrip data but on the data transformed with the dataPrepTransformer. 

In the function RetrainTheModel():
The above structure is used correctly by first loading the dataPrepPipeline and transforming the data first. It is important to note that the pipeline used to create the retrained model only consists of OnlineGradientDescent and not the pipeline for transforming the data. It accepts as input not the original TaxiTrip data, but the transformed data. 

In the function TestSinglePrediction():
The retrained model is loaded and used for prediction. As noted above, this model does not have the necessary data transformations. Therefore, the call to CreatePredictionEngine<TaxiTrip, TaxiTripFarePrediction> fails because the trainedModel does not have the necessary stages to convert the TaxiTrip structure to TaxiTripFarePrediction. 
However, you follow the same steps that are done in RetrainTheModel(), that is you load the dataPrepPipeline and transform the data first, or create a new pipeline by appending the retrained model to the data prep pipeline, you can call CreatePredictionEngine<TaxiTrip, TaxiTripFarePrediction> without error. That is, before you create the prediction engine, you change the lines to the following:

```
    var dataPrepPipeline = mlContext.Model.Load(Data_PreparationModelPath, out var dataPrepPipelineSchema);
    ITransformer trainedModel = dataPrepPipeline.Append(mlContext.Model.Load(ModelPathAfterRetrain, out modelSchema));
```

A similar issue exists in PlotRegressionChart as well.
