### ISSUE TITLE
Issue with Label Column (Prediction Label)  - ML 1.4

### ISSUE THREAD

**Issue by hahsm** [dotnet/machinelearning#4473]
Hi. When I try to train a dataset that consists a unique sequential number column as the Label (Predicted Label) column, the train model fails. But when I change the Label Column to non-unique column, the model train succeeds. Why is this happening. I am using AutoML feature of ML.Net to train the Model.

Thank you

**Comment by harishsk** [comment]
Can you please share some sample rows of your data and your code? If you could upload your project to github or attach a zip of the code, that would be even better.

**Comment by justinormont** [comment]
What are you looking to predict? I assume you're making a classification model (as opposed to regression)?

**For classification:**
[Classification](https://en.wikipedia.org/wiki/Multiclass_classification) is where you want to predict one of a small set of classes for your data (e.g. "cat", "dog", "fish"). If your Label column has unique values for the classes, you won't have a way to test the model since there will only be one example of each class in the full dataset. That one example will either be in the training or test split. Even if you had text examples, given there is only one example per class you're unlikely to get a useful model with only [one example per class](https://en.wikipedia.org/wiki/One-shot_learning), as we don't optimize for this case.

That said, I wouldn't expect it to throw; I'd expect it to return exactly 0% accuracy.

**For regression:**
[Regression](https://en.wikipedia.org/wiki/Regression_analysis) is where you predict the floating point value of the label. Having all label values be unique is normal, and should work correctly.

**Comment by harishsk** [comment]
@hahsm I am assuming your query has been answered. If not, please feel free to reopen the issue.
