### ISSUE TITLE
Best algorithm to use (ML.Net 1.4.0)

### ISSUE THREAD

**Issue by hahsm** [dotnet/machinelearning#4502]
Hi,
I have a dataset in the following format,

Item (feature) |  Model (feature) |  Brand (feature) | ItemId (PredictedLabel)
Iphone X         | X MAX                |  Apple               | 1
Samsung 10S | 10S                      | Samsung          | 2
Samsung Note 9 | 9                      | Samsung          | 3
Likewise.. 

Based on the Item, Model and Size given as test data, I wanted to predict the ItemId. How is this possible, and what algorithm should I use to achieve this. I tried using Multiclass classification, and since Label column contains unique sequential values, each is considered as a separate class, and even with few data, it takes a very long time to train, with 0% accuracy. I am using ML.Net 1.4.0. Would appreciate if a sample code is shared.

Thank you.

**Comment by codemzs** [comment]
Please consider looking at our [samples](https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification) that explain how to use multi-class trainers. Also look at [samples ](https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms)that show how to use transforms. 

There is no such thing as best algorithm because it really depends on your dataset and problem that you are trying to solve. I will recommend building a basic pipeline from the samples just to get something working and then playing with the hyperparamters/trainers. Also please consider using more examples and may use of our sample datasets used in the samples.

**Comment by justinormont** [comment]
For the unique label values, see reply here:
https://github.com/dotnet/machinelearning/issues/4473#issuecomment-553523952
