### ISSUE TITLE
Q: A calibrator is required for Bin Classification Evaluate

### ISSUE THREAD

**Issue by lefig** [dotnet/machinelearning#4630]
Hi,

Concerning Binary Classification features analysis I find that for evaluation of scores a calibrator is required, such as

Logger.Info("===== Evaluating Model's accuracy with Test data =====");
            var trainingPipeline = dataProcessPipeline.Append(algorithm)
                .Append(mlContext.BinaryClassification.Calibrators.Platt()); 

I can understand this being standard behaviour for uncalibrated learners but even with calibrated learners such as the following this is still needed (for the Probability column to be found):

var algorithm = mlContext.BinaryClassification.Trainers.AveragedPerceptron(labelColumnName: "Label",  featureColumnName: "Features");

Is this correct behaviour?

Many thanks

Fig

**Comment by yaeldekel** [comment]
Hi @lefig , thanks for your question.
The `AveragedPerceptron` algorithm does not return a calibrated model, it returns a model that only knows how to compute a `Score`. In order to make it calibrated you would need to add a calibrator like in your example. It is true that some of the binary classification trainers automatically return a calibrated model without the need to explicitly add one (such as `FastTree`), and in these cases you do not need to add a calibrator before calling the `Evaluate` API.

Another option for models that are not calibrated, is to use the `EvaluateNonCalibrated` API instead of `Evaluate`. This API does not require a `Probability` column, and returns only metrics that can be computed directly from the `Score` column.

**Comment by antoniovs1029** [comment]
Hi @lefig , it seems your question has been answered so I will close this issue. If you have anything else to add, please feel free to reopen it. Thanks!
