### ISSUE TITLE
NaN metric value handling in AutoML

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#4663]
AutoML API code is not handing `NaN` values for metrics. During the sweep, when a model returns a `NaN` value for the metric being optimized, AutoML crashes.

See background: https://github.com/dotnet/machinelearning/issues/4648#issuecomment-574886743

**Comment by harishsk** [comment]
@justinormont You suggested fixing two things in #4648 . The second one is being fixed in ML.NET. Does the first work item still need to be done as part of this bug fix? If so, can you please add some repro steps for this bug?

**Comment by justinormont** [comment]
@CBrauer has a repro in bug.zip from his original bug report: https://github.com/dotnet/machinelearning/issues/4648#issue-549108532

> Hello,
> 
> I just upgraded my project to the new pre-release versions of ML.NET and I got the following error message when I ran my program:
> 
> ![bug](https://user-images.githubusercontent.com/1317234/72281674-ccf0a400-35ef-11ea-898e-997cf19c71f0.png)
> 
> I have added a Zip file of my program and dataset.  I hope you guys can help me find out why I'm getting this error,
> 
> Charles
> 
> [bug.zip](https://github.com/dotnet/machinelearning/files/4055108/bug.zip)

In this example, he is optimizing towards the `F1` metric, which can currently be `NaN`. The AutoML code crashes when it receives the `NaN` within the metric its optimizing towards. 

Another way to reproduce is in a debugger and replacing the model's returned metric w/ `NaN`.

**Comment by harishsk** [comment]
@CBrauer The attached zip file did not contain the csv files for validation and test. I reduced the training file by 40% and created two new files for validation and test. With that, I have not been able to reproduce the issue you are seeing. 

Can you please update the zip file with the necessary files that reproduce the issue?

**Comment by najeeb-kazmi** [comment]
We don't need to split the file into train, validation, and test. AutoML does the split internally. I can reproduce the error with the data and code provided. It uses `1.5.0-preview` and `0.17.0-preview`, which do not have the fix for `F1` score returning `0` instead of `Nan` from #4674. The fix for `F1` is there in `preview2`. 

I'll look at how `NaN` metrics can be handled in AutoML. `F1` no longer returns `NaN`, but `LogLossReduction` can still return `NaN` https://github.com/dotnet/machinelearning/issues/4648#issuecomment-574886743. I'll look at whether `NaN` in `LogLossReduction` can be handled, or if AutoML should generally handle `NaN`s, or both.
