### ISSUE TITLE
Default seed is not propagated from MLContext

### ISSUE THREAD

**Issue by najeeb-kazmi** [dotnet/machinelearning#4752]
In theory, the seed set in `MLContext` is intended to provide the global seed for all components and operations requiring randomness, e.g. sampling, permutation, etc. In practice, this doesn't always hold true.

`TrainTestSplit`, `CrossValidationSplit`, and `CrossValidate` all have a user specified seed and call `EnsureGroupPreservationColumn`, which in turn uses `GenerateNumberTransform` and `HashingEstimator`.

When the seed is not specified by the user, it is not derived from `MLContext`. Instead, `GenerateNumberTransform` and `HashingEstimator` use their own defaults, so that if a user doesn't specify a seed to `TrainTestSplit`, `CrossValidationSplit`, or `CrossValidate`, they will always get a deterministic split regardless of the seed in `MLContext`.

https://github.com/dotnet/machinelearning/blob/24c827416d23a6a74f16f71ec9123ca15e0e12fd/src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs#L496-L505
https://github.com/dotnet/machinelearning/blob/24c827416d23a6a74f16f71ec9123ca15e0e12fd/src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs#L521-L525

cc: @harishsk @justinormont

**Comment by justinormont** [comment]
There are two uses of the term "seed": PRNG seeds, and hashing seeds. The seeds for hashing are a bit of a different beast than the rest. For hashing (e.g. NgramHashingTransformer) they are init values for hashing instead of the seed for PRNGs.

For the hashing components, I don't think they should listen to the _global_ seed.

When hashing a feature to a specific bin (e.g. categorial hash), I generally expect the hashing to be stable and the same input value will land in to the same feature slot between runs. 

For instance, if I featurize a dataset using the categorial hash, I would expect to be able to re-use the data. This occurs when partitioning a large dataset across a cluster and using stateless transforms like categorical hash, where each node learns on its local data, then we combine the output models. To combine the models, the feature slots needs to line up (otherwise we have to keep/run all N featurizers). Altering the seed of hashing, reduces the reusability of data that flows thru the hashing transforms. While we may want to otherwise alter the PRNG seed independently.

We should consider renaming `seed` in hashing components to `hashInit` to distinguish from PRNG seeds.

---

Use of seed in `NgramHashingTransformer`: _(passing the `seed` as the init value)_
https://github.com/dotnet/machinelearning/blob/4ec2f9c6dc08e8079338546b31f260d0715db45c/src/Microsoft.ML.Transforms/Text/NgramHashingTransformer.cs#L455-L461

Use of `seed` in hashing: _(becomes the init value)_
https://github.com/dotnet/machinelearning/blob/b861b5d64841cbe0f2c866ee7586872aac450a51/src/Microsoft.ML.Core/Utilities/Hashing.cs#L254-L269

Hashing methods have a default "seed" value of `314489979`:
https://github.com/dotnet/machinelearning/blob/4ec2f9c6dc08e8079338546b31f260d0715db45c/src/Microsoft.ML.Transforms/OneHotHashEncoding.cs#L251-L258

**Comment by najeeb-kazmi** [comment]
I'm not suggesting we change defaults of `HashingExtimator`. Rather, the seed we pass to `EnsureGroupPreservationColumn` should come from `MLContext`, when not specified in `TrainTestSplit`. etc.

Or do you think it should always be a deterministic split if no seed specified in `TrainTestSlit` etc, regardless of the seed in `MLContext`?

**Comment by justinormont** [comment]
> Or do you think it should always be a deterministic split if no seed specified in `TrainTestSlit` etc, regardless of the seed in `MLContext`? This is the current behavior.

`TrainTestSlit` etc should listen to `MLContext` seed if not given by the user for the specific component.

I think the precedence for PRNG seeds should be:
1. User seed specified for the component instance (or from parent component if hiding behind another)
2. User seed specified in `MLContext`
3. Default seed in component (unsure if we should remove these, might be a component-by-component discussion)
4. Random (and more random than current -- see https://github.com/dotnet/machinelearning/pull/4645#discussion_r365552609)

**Comment by harishsk** [comment]
Looks like there are additional comments that need to be addressed.

**Comment by sharwell** [comment]
One of the challenges of the RNG used in ML.NET is it extends `Random`, so it's hard to find locations where a seed fails to propagate. Note that the propagation is quite complex - rather than starting a new RNG with the _original_ MLContext seed, the new RNG "forks" from the current RNG by using the next number from the current RNG as the seed for the new RNG. If the goal of the seed investigation effort is deterministic execution if a seed is provided, I'm not confident propagation of the seed is sufficient to achieve this. Two additional notes:

1. I was not able to find a case where an RNG is created without a seed specified (or rather, I can't remember such a case; I investigated this about 2 months ago)
2. I was not able to find a case where the seed provided to the initial MLContext changed the test outcome. This is _very_ easy to test with `IterationData` - just pass the iteration value as the MLContext seed.

**Comment by codemzs** [comment]
Forking is done because Random is not thread safe. In any case the current mechanism should guarantee deterministic behavior because the seed generated from parent RNG should be same each time.
