### ISSUE TITLE
Implementing a custom `IEstimator` and `ITransformer`

### ISSUE THREAD

**Issue by leblancdavid** [dotnet/machinelearning#4911]
I am currently working on a custom algorithm to transform my data for my application. I would like to include this transform into my pipeline so I can save and load it along with the model. 

I started out by implementing the `IEstimator<ITransformer>` and `ITransformer` interfaces. The `Fit(...)` and `Transform(...)` methods were fairly easy to implement but I'm struggling with how these models can be saved. The `ModelSaveContext` in the `Save(...)` method contains only `internal` properties which I cannot access.

I realize I could technically implement a `CustomMappingEstimator` but it doesn't really appear to do anything during the `Fit` part of the training. My algorithm generates data (just a list of indexes to determine with features to use), which is then passed to the `ITransformer`.

Are there examples of how to do this?

**Comment by yaeldekel** [comment]
Hi @leblancdavid ,
It seems that you cannot implement `ITransformer` for the reason you mentioned (because all the properties/methods on `ModelSaveContext` are internal). There are also a few abstract base classes implementing `ITransformer`, but they all have private protected abstract methods, so you cannot implement them either. 

You can implement it in one of the projects that is "friends" with `Microsoft.ML.Core` (the most natural one would be `Microsoft.ML.Transforms`) - you can create your own branch for it. If your estimator/transformer are of interest to the community then you can also create a pull request, we welcome contributions :-).

I don't know many details about the estimator/transformer that you are trying to build, but from your description of "just a list of indexes to determine which features to use", it sounds similar to the feature selection transformers. Have you looked at what ML.NET currently has for [feature selection](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Transforms/FeatureSelectionCatalog.cs)?

**Comment by leblancdavid** [comment]
I realize this is probably a fairly large task (and I probably don't understand all that is going on under the hood) but it would be nice if those interfaces could be implemented on the outside.

I'm not sure how valuable my feature selector would be to anyone outside of my specific application. My input features are quite large (30,000+) so I am trying to reduce the number of dimensions. I have tried the `SelectFeaturesBasedOnMutualInformation` but I'm not sure I am getting the best results. I suppose I could try it again and possibly `SelectFeaturesBasedOnCount`. I believe the problem is probably around 10% of my features in my dataset show up consistently. So I typically select features to reduce the size, then apply PCA to further reduce.

I will experiment some more and let you know. Thank you!

**Comment by mstfbl** [comment]
Hi @leblancdavid , it seems like @yaeldekel has given some suggestions on how to continue, and as she's said, please feel free to open a PR with your custom feature selector, and we will review it promptly!

**Comment by worldbeater** [comment]
So basically due to `private protected` and `internal` keywords being preventively placed here and there, currently there is no way to implement a custom `IEstimator` or `ITransformer` (which can be based on e.g. state of the art papers) in order to conduct some preliminary studies, and to compare the performance of existing ML.NET algorithms with our own ML.NET algorithm, am I correct? Don't really understand why the issue is closed then, the problem exists and prevents our lab from using ML.NET.
