### ISSUE TITLE
Unexpected WordEmbedding behavior as feature vector to a multi-class classifier

### ISSUE THREAD

**Issue by Zeraphil** [dotnet/machinelearning#4954]
### System information

- **OS version/distro**:
Windows 10
- **.NET Version (eg., dotnet --info)**: 
3.1.1

### Issue

- **What did you do?**
Apply the WordEmbedding transformer to a multiclass prediction trainer.
- **What happened?**
Cross validation resulted errors and NaN scores in multiclass predictions. 
- **What did you expect?**
I expect to be able to use the word embedding feature vector, concatenate it with other features, and apply it to my classifier.

### Source code / logs

I'm trying to use either downloaded FastText word vectors or the built-in ones. My Data Processing pipeline looks like this:

` Append(mlContext.Transforms.Text.FeaturizeText("FeaturesA", options, "Transcript"))
 .Append(mlContext.Transforms.Text.TokenizeIntoWords("Tokens", "Transcript"))
 .Append(mlContext.Transforms.Text.ApplyWordEmbedding("WordEmbeddings", "OutputTokens", WordEmbeddingEstimator.PretrainedModelKind.GloVe50D))
 .Append(mlContext.Transforms.Text.ApplyWordEmbedding("WordEmbeddings", WORDVECTOR_PATH, "Tokens"))
.Append(mlContext.Transforms.NormalizeMinMax("FeaturesA", "FeaturesA"))
.Append(mlContext.Transforms.CopyColumns("FeaturesB", "WordEmbeddings"))
.Append(mlContext.Transforms.Concatenate("Features", "FeaturesA", "FeaturesB"))
.AppendCacheCheckpoint(mlContext);
 
var trainer = mlContext.MulticlassClassification.Trainers.SdcaMaximumEntropy(labelColumnName: "Label", featureColumnName: "Features")
.Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel", "PredictedLabel"));
var trainingPipeline = dataProcessPipeline.Append(trainer);'

I don't get a functioning model, the prediction scores are NaN. I have a couple of questions on this.
I understand that ApplyWordEmbedding returns an estimator, but I had it understood it outputs the average/min/max of all the token vectors, so word vector dimensions *3. 

1) Why isn't this usable as a feature vector into a classifier? If I apply another transform, like NormalizeMinMax, it suddenly works, but that's squashing the values in a way that doesn't make sense.

2) Why is the model size so small? I expected that, as part of the transform, the whole wordvector model would be included, but it seems like if the data doesn't contain the token, it's not included in the model. That doesn't make word embeddings that useful as part of the point of word vectors is to provide a language model. If I want to classify a sentence containing cat as "Animal" but my data doesn't contain dog, the model should still be able to featurize dog as part of the sentence, but it doesn't seem like the model would be able to do that. Apologies if I'm missing something very obvious, going through the WordEmbedding documentation has been a bit difficult for me.

3) How can I select just the average features? It's not clear from the docs either.

Thank you!

**Comment by Lynx1820** [comment]
Hi @Zeraphil , thank you for the feedback. 

1) Linear models often return NaN scores when there are NaN values in the input data. Have you tried using the ReplaceMissingValues transformer? Normalizing your text?

2) Yes, the word vector model is not included in the ml.net model because the purpose of this transformer is simply to featurize the words, and doesn't really need the model for additional retraining. I believe you should be able to featurize words outside of your data vocabulary, but I'll let @najeeb-kazmi confirm that. 

3) Have you tried FeatureSelection Transformers? @najeeb-kazmi , do you know of other transformers to use?

**Comment by Zeraphil** [comment]
Hi Karen,

Thank you for your response!

I guess I need to determine why apply the word embedding transformer would result in NaN values. I'm not sure what the behavior is for out of vocabulary tokens, if anything I'd like to understand the behavior a bit better.

As for 3, I have not yet, I'm still new to MLNet, I will look into them, thank you!

**Comment by justinormont** [comment]
For using the word embedding transform, I'd have `FeaturizeText` produce the tokens for the `ApplyWordEmbedding`, which will remove diacritics and lower case by default (increasing your accuracy by removing OOV), and also in your case it's faster since you're already running a `FeaturizeText` (no need to clean and tokenize 2x). See https://github.com/dotnet/machinelearning-samples/issues/702#issuecomment-544183298

> Why isn't this usable as a feature vector into a classifier? If I apply another transform, like NormalizeMinMax, it suddenly works, but that's squashing the values in a way that doesn't make sense.

You should be able to feed the output from the word embedding transform directly to a model. If it doesn't work, it is a bug.

>Cross validation resulted errors and NaN scores in multiclass predictions.
I wouldn't expect NaN predictions from your pipeline of word embeddings plus ngrams (neither should ever produce a NaN feature).

Q: How large is your dataset? What's the count of each class? Perhaps there's an issue with not having all classes represented in each CV fold (expected to work, but another possible bug location)?

To see which is causing the NaN predictions, can you try both options:
`.Append(mlContext.Transforms.Concatenate("Features", "FeaturesB"))`
and
`.Append(mlContext.Transforms.Concatenate("Features", "FeaturesA", ))`

This will tell us if the word embedding transform or the text featurizer transform is causing the NaN values.

> I'm not sure what the behavior is for out of vocabulary tokens, if anything I'd like to understand the behavior a bit better.

It returns the min/avg,max of the ngrams in the phrase, and any ngram which is OOV (out of vocabulary) is ignored (not included in the min/avg/max). If the entire set of words in the phrase is OOV, it returns a vector of zeros. It's possible that the fully-OOV case is not handled correctly.

**Comment by Zeraphil** [comment]
Hi, thank you. It's definitely the WordEmbedding transformer as the text Featurizer works no matter what.

>  It's possible that the fully-OOV case is not handled correctly.
I think this might be the case.

My dataset is about 100,000 elements, 8 labels, fairly balanced (~12 each).

**Comment by u-ashikov** [comment]
Hi guys, we have the same problem, when trying to apply word embeddings with the multi class classification trainer SdcaMaximumEntropy. Are there any related comments on this or is it an issue with the trainer or with the Word Embeddings Estimator?

**Comment by Lynx1820** [comment]
Hi @Zeraphil and @u-ashikov, 

If you still have this issue, could you provide your dataset/code? I can take a closer look.

**Comment by Lynx1820** [comment]
Closing this issue. Feel free to reopen if you have a follow up. Thank you.
