### ISSUE TITLE
Auto.ML.0.16.0 and System.Memory 4.0.1.0

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#5086]
Moving issue raised by @ericdransfeldt in Docs repo since it's a product question.

Hi,

I love the Microsoft.ML and AutoML platforms but am having an issue when I upgraded my AutoML version via NuGet. When I upgraded from Microsoft.ML.AutoML from version 0.15.0 to 0.16.0 I started getting an error when I ran my code. Nothing changed in my source code except to recompile. It seems like it can't find System.Memory 4.0.1.0.

Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified., Stack: at Microsoft.ML.Data.InternalSchemaDefinition.GetVectorAndItemType(String name, Type rawType, IEnumerable1 attributes, Boolean& isVector, Type& itemType) at Microsoft.ML.Data.InternalSchemaDefinition.GetVectorAndItemType(MemberInfo memberInfo, Boolean& isVector, Type& itemType) at Microsoft.ML.Data.SchemaDefinition.Create(Type userType, Direction direction) at Microsoft.ML.Data.DataViewConstructionUtils.CreateFromEnumerable[TRow](IHostEnvironment env, IEnumerable1 data, SchemaDefinition schemaDefinition)

I went back to the older version and it worked fine. No dependency issues.. Any ideas..?

Thanks for any help or ideas!

Cheers,
Eric

**Comment by harishsk** [comment]
@ericdransfeldt Would it be possible for you to provide a small repro of your issue?

**Comment by ericdransfeldt** [comment]
Hi Harish,

Thank you for the message. Yes I can provide a repro. It will take a bit of time though to pull out code and make a new project.

Cheers,
Eric

**Comment by harishsk** [comment]
@ericdransfeldt I am closing the issue for now. Please reactivate when you have a repro we can look at. Thanks.

**Comment by ericdransfeldt** [comment]
Ok, thanks Harish

    On Wednesday, May 13, 2020, 09:53:48 AM PDT, Harish Kulkarni <notifications@github.com> wrote:  
 
 


@ericdransfeldt I am closing the issue for now. Please reactivate when you have a repro we can look at. Thanks.

**Comment by ericdransfeldt** [comment]
Hi Harish,
Sorry it took so long but I have a repro for you. Where would you like me to send the files? The issue seems to only happen when I am trying to access Microsoft.ML that is in a separate assembly. I am loading the assembly in another program and then calling into the library. I have code to demonstrate this. I actually built a debug version of the Microsoft.ML platform to trace into the issue and it fails at Microsoft.ML.Data.InternalSchemaDefinition.GetVectorAndItemType.
Cheers,
Eric

**Comment by harishsk** [comment]
The exception you are getting seems to be that it is not able to load System.Memory. Do you have that package referenced in this project? 
Can you please share a small sample project where you are seeing this error?

**Comment by ericdransfeldt** [comment]
Hi Harish,
Thanks for the message. Yes, it is not able to load the System.Memory assembly. I don't have that version nor can I actually find it anywhere. If I could get the version that would probably be an easy fix but I can't seem to find it.
I do have a sample for you. It only seems to happen if I load a separate assembly/dll that contains Microsoft.ML and try and create a model. 
I'll forward the previous email that had more info about the repro.
Cheers,Eric


    On Monday, June 1, 2020, 09:37:25 AM PDT, Harish Kulkarni <notifications@github.com> wrote:  
 
 


The exception you are getting seems to be that it is not able to load System.Memory. Do you have that package referenced in this project?
Can you please share a small sample project where you are seeing this error?

**Comment by ericdransfeldt** [comment]
Hi Harish,
Thank you for your email. I have a repro for you. I put the code in the dropbox folder below. It seems to only happen when I load Microsoft.ML in a separate assembly, which is how I currently use it. 
You'll need to load the nuget package files for Microsoft.ML.AutoML and ML in the MLNETRepro solution. I figured there's no reason to send the files since you have them already.
You'll need to set where the MLNETRepro folder and the DTTFramework.dll is at in the ReproApp Program.cs file. I'll include the code to show you.

        private static object[] GetCreateModelParams(Action<int, string> StatusCallback)
        {
            CancellationToken token = new CancellationToken();
            bool useDirCache = true;            string folder = @"F:\tmp\MLNETRepro\";
            string trainingFile = folder + @"Training.txt";
            string testFile = folder + @"Test.txt";
            string modelFile = folder + @"Model.txt";
            string logFile = folder + @"Loggie.txt";            object[] modelParams = new object[] {
                     (Action<int, string>)StatusCallback, trainingFile, testFile, string.Empty, string.Empty, modelFile, string.Empty, string.Empty, 1000, 5, 0F,
                    0F, 0F, logFile, 3, 0, token, useDirCache
                    };            return modelParams;
        }
        static void Main(string[] args)
        {
            try
            {
                string dttFrameworkType = "DTT.Framework.LSTMSequenceClassifier";
                string DTTLibraryPath = @"F:\tmp\MLNETRepro\bin\x64\Debug\DTTFramework.dll";
        ….

For the MLNETRepro you'll need to compile as x64 and add the packages (PM > Install-Package Microsoft.ML.AutoML -Version 0.16.0)
If you run the ReproApp program it should come back with an exception in the Console Window:
Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified., Stack:    at Microsoft.ML.Data.InternalSchemaDefinition.GetVectorAndItemType(String name, Type rawType, IEnumerable`1 attributes, Boolean& isVector, Type& itemType)
   at Microsoft.ML.Data.InternalSchemaDefinition.GetVectorAndItemType(MemberInfo memberInfo, Boolean& isVector, Type& itemType)
   at Microsoft.ML.Data.SchemaDefinition.Create(Type userType, Direction direction)
   at Microsoft.ML.Data.DataViewConstructionUtils.CreateFromEnumerable[TRow](IHostEnvironment env, IEnumerable`1 data, SchemaDefinition schemaDefinition)
   at DTT.Framework.LSTMSequenceClassifier.AutoTrainShort(TrainingParams trainingParams, BackgroundWorker worker, DoWorkEventArgs e) in F:\tmp\MLNETRepro\LSTMSequenceClassifier.cs:line 368


Microsoft


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Microsoft

Shared with Dropbox
 |

 |

 |



Thank you for your help!
Cheers,Eric

    On Monday, June 1, 2020, 09:37:25 AM PDT, Harish Kulkarni <notifications@github.com> wrote:  
 
 


The exception you are getting seems to be that it is not able to load System.Memory. Do you have that package referenced in this project?
Can you please share a small sample project where you are seeing this error?

**Comment by harishsk** [comment]
> Hi Harish, Thanks for the message. Yes, it is not able to load the System.Memory assembly. I don't have that version nor can I actually find it anywhere. If I could get the version that would probably be an easy fix but I can't seem to find it. 

You can find [System.Memory on nuget](https://www.nuget.org/packages/System.Memory/)
Can you please try it and let me know?

**Comment by ericdransfeldt** [comment]
Hi Harish,

That version isn’t on nuget. :( at least when I tried to get it. 

Cheers,
Eric

**Comment by harishsk** [comment]
You said earlier that you had shared the project on DropBox. Can you please share a link?
Or create a github repo for the project and share that link?

**Comment by ericdransfeldt** [comment]
Hi Harish,

The Dropbox link is the Microsoft link at the bottom of the page.

Cheers,
Eric

**Comment by harishsk** [comment]
The link seems to have been stripped out. I don't see any link at the Microsoft or "Shared with Dropbox" text above.

**Comment by ericdransfeldt** [comment]
I'll try it again. There are two files. Here's the link: https://www.dropbox.com/sh/7b3ihvbtz02v5mt/AABuuCQL5aKJKjFGBsFJv--ma?dl=0
Please let me know if it gets stripped out.
Cheers,Eric

    On Monday, June 1, 2020, 01:25:11 PM PDT, Harish Kulkarni <notifications@github.com> wrote:  
 
 


The link seems to have been stripped out. I don't see any link at the Microsoft or "Shared with Dropbox" text above.

**Comment by harishsk** [comment]
That link works. 

Can I ask why you have them as separate solutions? 

It would be a lot simpler if you kept both in the same solution and used a project reference. 
Can I ask why you are doing it through reflection as opposed to a project reference?

**Comment by ericdransfeldt** [comment]
Hi Harish,
We need to have separate projects to mimic the error. 
Cheers,Eric

    On Monday, June 1, 2020, 01:40:16 PM PDT, Harish Kulkarni <notifications@github.com> wrote:  
 
 


That link works.

Can I ask why you have them as separate solutions?

It would be a lot simpler if you kept both in the same solution and used a project reference.
Can I ask why you are doing it through reflection as opposed to a project reference?

**Comment by harishsk** [comment]
The way you are doing it right now, you are loading only the single assembly for DTTFramework. The current directory is still your executable's current directory and the dependencies for DTTFramework aren't fully known by your ReproApp. Therefore the app tries to resolve the dependencies in its current path and is unable to find System.Memory.

I added a reference to System.Memory v4.5.1 package from nuget to ReproApp and I don't see that error anymore.

Another way to fix this error is to take a project dependency on the MLNETRepro app. (I would recommend this path if it works for you because then you don't have to use reflection in your ReproApp code)

I think either of your solutions ought to work for you.

**Comment by ericdransfeldt** [comment]
Hi Harish,
Thank you for looking at this. Unfortunately I can't do a project dependency because its a third party app. I'm just extending their framework. I'm still having the same issues with the real code because I can't use .netstandard in the other 3rd party framework but I'll figure it out. 
Thank you for your help!
Cheers,Eric

    On Monday, June 1, 2020, 05:41:37 PM PDT, Harish Kulkarni <notifications@github.com> wrote:  
 
 


The way you are doing it right now, you are loading only the single assembly for DTTFramework. The current directory is still your executable's current directory and the dependencies for DTTFramework aren't fully known by your ReproApp. Therefore the app tries to resolve the dependencies in its current path and is unable to find System.Memory.

I added a reference to System.Memory v4.5.1 package from nuget to ReproApp and I don't see that error anymore.

Another way to fix this error is to take a project dependency on the MLNETRepro app. (I would recommend this path if it works for you because then you don't have to use reflection in your ReproApp code)

I think either of your solutions ought to work for you.
