### ISSUE TITLE
Update ML.NET trained Model in ASP.NET Core without restarting the app

### ISSUE THREAD

**Issue by adriansd27** [dotnet/machinelearning#5088]
### System information
Windows 10
- **OS version/distro**: Education
- **.NET Version (eg., dotnet --info)**: .NET Core 3.1

### Issue
Unable to update a ML.NET trained model in ASP.NET Core without restarting the web app
- **What did you do?**

Like the title says, I'm trying to retrain an existing ML.NET model in an ASP.NET Core web app. The setup: I have an existing model.zip file on the local disk. In Startup.cs I'm injecting the prediction engine pool service

`services.AddPredictionEnginePool<ImageData, ImagePrediction>().FromFile(
        "ImageClassificationModel", _modelPath, true);`

by loading the existing model from the disk. The _modelPath variable indicates the path to the zip file, and the true parameter indicates that the Prediction Engine Pool should watch the model for changes. According to https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/serve-model-web-api-ml-net,

> The PredictionEnginePool service provides a mechanism to reload an updated model without taking your application down.

I've also created a service that takes the path to some image folders and trains a new model, then saves it to the same location _modelPath indicates. That service is exposed through an API Endpoint.

- **What happened?**

The problem: When accessing the train endpoint, the app works fine. It retrains the model and saves it to the indicated path. I can do this several times. However, if I use the model to predict an image's label, I'm no longer able to retrain the model. If I try to call the train endpoint again, I'm getting an error that says the model file is already in use.

> System.IO.IOException: 'The process cannot access the file '\MLModel\model.zip' because it is being used by another process.'

The only way to update the model so far would be to completely restart the web app and call the train endpoint first thing.

- **What did you expect?**

The expected result would be able to retrain the model without restarting the web app.

**Comment by harishsk** [comment]
@adriansd27 Is it possible for you provide a small repro of your bug?

**Comment by adriansd27** [comment]
Hi @harishsk ,

Repro steps:
1. Get a model.zip trained and ready to use, set it at a certain path on your disk.
2. Register Prediction Engine Pool
`            services.AddPredictionEnginePool<ImageData, ImagePrediction>().FromFile(
                "ImageClassificationModel", _modelPath, true);`
3. Inject Prediction Engine Pool
`        public PredictionService(PredictionEnginePool<ImageData, ImagePrediction> predictionEnginePool)
        {
            _predictionEnginePool = predictionEnginePool;
        }
`
4. Predict some image label
`                var imagePrediction = _predictionEnginePool.Predict("ImageClassificationModel", imageData);
`
5. Create a new model and try to save it over the existing one: 
`_mlContext.Model.Save(model, trainingData.Schema, modelPath);`

**Comment by adriansd27** [comment]
Of course things would have been much easier if we could have loaded the model from a database and save it to a database instead of writing it to a zip file.

**Comment by harishsk** [comment]
@adriansd27 I ran a web server with a prediction end point and then regenerated and overwrote the model it was using.

I did see the `System.IO.IOException` exception that you mention above, but that is expected behavior. That exception comes the file watcher which will reload the model as soon as it is saved. You see the exception because the file watcher is trying to reload the model while the model is still being written. But as soon as the model save is complete the file watcher kicks in again and reload the model. I am able to do both model overwriting and serving predictions alternately several times without any failure (apart from the exception above that gets handled).

Since I am not able to get a good repro, perhaps there is something I am missing in your scenario and I would greatly appreciate some code that reproduces your issue. 

Can you also please share if you testing against ML.NET v1.5.0-preview2 build? And if not, can you please try against that release?

**Comment by harishsk** [comment]
@adriansd27 I have not been able to reproduce the issue. Please try it on the latest release and if you still have issues, please reopen the issue.
