### ISSUE TITLE
The future of ML.NET

### ISSUE THREAD

**Issue by nsulikowski** [dotnet/machinelearning#5089]
Back in 3/26/2020 I was surveyed by members of the ML.NET team, who were gathering feedback about uses of ML.NET. 
I'm wondering broadly what the future of ML.NET will look like? Will you continue to invest in making it a stand alone product for machine learning, extending the breath and depth of the library? Or perhaps it'll end up being more of a hosting environment for models and statistical studies built in other languages like python/R ?
I personally would love to have ML.NET eventually be a one stop shop, with everything I need. But I wonder what the team is thinking? 
Thanks!

**Comment by harishsk** [comment]
ML.NET is an important project to empower .NET developers to leverage the latest advances in machine learning. We regularly seek community input on the features they would like to see. We are enhancing the breadth and depth of the library (e.g. new features related to time series slated for the next release) and hosting environment for models created in other tools through our enhanced support for ONNX models in recent releases. We chose ONNX format because it is an open standard that cover DNN and traditional ML, in addition of a rich ecosystem of frameworks support. We are also working on making these capabilities more accessible with enhancements to Model Builder in Visual Studio. 

If there are specific features you would like to see in ML.NET, we would love to hear more from you. As an open source project, we also love to work with community members contributing code.
