### ISSUE TITLE
Method to check if a modelName already exists in the PredictionEnginePool

### ISSUE THREAD

**Issue by iluveu28** [dotnet/machinelearning#5132]
This is related to an issue I brought up in Stack Overflow - https://stackoverflow.com/questions/61695078/ml-net-how-to-detect-a-model-is-missing-from-the-predictionenginepool/61773814#61773814

In the Web API, I need someway to PredictionEnginePool.GetModel by model name. I'd like to also do AddPredictionEnginePool outside of the Startup.cs. In my service layer, I check if a model doesnt exists then I will add it on the fly coz the new model had just been created post startup.

Thanks you very much in advance

**Comment by mstfbl** [comment]
Hey @iluveu28,

Can you share your code and repro so that we can check how exactly you are loading your model with `predictionEnginePool.GetModel(modelName: "ModelA")`? Perhaps we can help you on exactly why your model is not loading.

Also, in the Stack Overflow issue you've made, I see a suggestion has been to add a function to see if the model has been correctly loaded or not by `PredictionEnginePool`. I think this is a great suggestion!

**Comment by wangyems** [comment]
Closing this issue for now. Please feel free to reopen it when you provide the example so that we can prioritize it.
