### ISSUE TITLE
Loading ML Model from a Stream

### ISSUE THREAD

**Issue by MahdiKarimipour** [dotnet/machinelearning#5199]
Trying to load a ML model from a stream (having the model as an embedded resource in the project), I get the below exception at mlContext.Model.Load() line. 

Same code snippet works if I load the model using the absolute filepath for the model.

Package Version: 1.5

`"System.ArgumentException: Illegal characters in path. (Parameter 'path')\r\n   at System.IO.Path.GetFullPath(String path)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at System.IO.File.OpenRead(String path)\r\n   at Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)\r\n   at PassionFruit.ML.Engines.SentimentPrediction.CreatePredictionEngine()`

                // Create new MLContext
                MLContext mlContext = new MLContext();
                string modelName = "PassionFruit.ML.MLModel.zip";
                var assembly = Assembly.GetExecutingAssembly();

                using (var stream = assembly.GetManifestResourceStream(modelName))
                using (StreamReader reader = new StreamReader(stream))
                {
                    var modelStream = reader.ReadToEnd();
                    ITransformer mlModel = mlContext.Model.Load(modelStream, out DataViewSchema inputSchema);
                    var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
                    return predEngine;
                }
```

**Comment by mstfbl** [comment]
Hi @MahdiKarimipour ,

I see that the main issue here is in obtaining the full path to your model, indicated by this function on top of the call stack:

`System.IO.Path.GetFullPath(String path)`

This is indicating that the path to the model being provided by `assembly.GetManifestResourceStream` contains illegal characters.

I advise you obtain the full path to your model through `Path.GetFullPath` ([api link](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath?view=netcore-3.1)), **confirm** that this path you get doesn't contain any illegal characters, and **then** input it to `mlContext.Model.Load(modelName, out DataViewSchema inputSchema)` as @Lynx1820 suggested.

As I don't think this is an ML.NET-related problem, I'm closing this issue. Feel free to reopen if you're obtaining any ML.NET errors, and share detailed error outputs and the full path you're obtaining for the model, so that we can diagnose your issue. Thanks!
