### ISSUE TITLE
CrossValidation Macros stops working in 1.5.0

### ISSUE THREAD

**Issue by ganik** [dotnet/machinelearning#5221]
ML.NET 1.5.0

Have NimbusML (built with ML.NET 1.5.0, here is [PR](https://dev.azure.com/aifx/public/_build/results?buildId=2988&view=results) that does this )
Run the tests in [test.cv](https://github.com/microsoft/NimbusML/blob/master/src/python/nimbusml/tests/model_selection/test_cv.py) 
test_default_label2  fails with error:
Error: *** System.InvalidOperationException: 'Column 'GroupId' not found' StackTrace:    at Microsoft.ML.EntryPoints.TrainerEntryPointsUtils.FindColumn(IExceptionContext ectx, DataViewSchema schema, Optional`1 value)
at Microsoft.ML.EntryPoints.TrainerEntryPointsUtils.Train[TArg,TOut](IHost host, TArg input, Func`1 createTrainer, Func`1 getLabel, Func`1 getWeight, Func`1 getGroup, Func`1 getName, Func`1 getCustom, ICalibratorTrainerFactory calibrator, Int32 maxCalibrationExamples)
at Microsoft.ML.Trainers.LightGbm.LightGbm.TrainRanking(IHostEnvironment env, Options input)

This is a regression from ML.NET 1.5.0.preview2

I did some debugging, it appears that once macros is expanded ColumnSelector Transform drops GroupId. ColumnSelector appears to be added by Macros expansion.

**Comment by antoniovs1029** [comment]
This issue was introduced in https://github.com/dotnet/machinelearning/pull/4828 which was included in the latest 1.5.0 release. Particularly the problem is in the `return stratificationColumn` here:
https://github.com/dotnet/machinelearning/blob/c6647482482abe4df13ae4712a6e71d84a635b83/src/Microsoft.ML.EntryPoints/TrainTestSplit.cs#L108-L117

The problem is that that method (`CreateStratificationColumn`) used to always create a new column using the `HashJoiningTransform`, and return the name of the new column. Then that new column was dropped in here in the `"Models.CrossValidatorDatasetSplitter"` entrypoint:
https://github.com/dotnet/machinelearning/blob/840ddcddc2b3aa849c9ad96a5119013e4a5cf019/src/Microsoft.ML.EntryPoints/CVSplit.cs#L71

With the changes of #4828, there's now a new path in `CreateStratificationColumn `which doesn't create a new column, and return the name of a previously existing column (in the context of this issue, that column is `GroupId`). Then in the `"Models.CrossValidatorDatasetSplitter"` entrypoint, the `GroupId `column gets dropped, which then is a problem when trying to train the LightGBM model, because it requires that column.
