### ISSUE TITLE
AutoML.Net: CrossValSummaryRunner can't handle all-infinity metrics value.

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning#5339]
CrossValSummaryRunner picks up the best model and score from cross validation in the following logic:
- get results from all validation runs
- if all run succeed, get the index of model with best score as return model, if all run's score is NaN or Infinity, uses the first model
- if all run succeed, get the score which is closest to the average score as return training score, if average score is NaN, use the first score (**BUG**)

The possible place that causes the bug is sometimes the average score can be Infinity, in which case the following function will return -1 and causes an index out of error exception

https://github.com/dotnet/machinelearning/blob/37af3f9db86414f4ec5b16a8734c90b498946caa/src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs#L84

### Related issue
(The label column for this user's dataset is all empty, which is the root cause for this error) 
- https://github.com/dotnet/machinelearning-modelbuilder/issues/929

**Comment by antoniovs1029** [comment]
Hi, @LittleLittleCloud 

So I'm not sure what's the expected behavior we should have. Do you want us to throw a more understandable exception message? Or is there actually something you think needs to be fixed?

> The label column for this user's dataset is all empty, which is the root cause for this error

In this case, it makes complete sense that AutoML.NET throws an error.

> The possible place that causes the bug is sometimes the average score can be Infinity, in which case the following function will return -1 and causes an index out of error exception

Is it possible to get an average score of infinity in a case different from having an empty label column?

I do see that we return index "0" if the average was NaN:
https://github.com/dotnet/machinelearning/blob/37af3f9db86414f4ec5b16a8734c90b498946caa/src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs#L162-L165

I wouldn't know why that's the case, though. Do you think we should return "0" also if the average is Infinity?

**Comment by LittleLittleCloud** [comment]
Hi @antoniovs1029 

For start, yes, I think we should return "0" if average is Infinity.

> In this case, it makes complete sense that AutoML.NET throws an error.
I think it's better not throw an error if the error is not from AutoML.Net. In this case, column all empty is not a good reason for throwing an error because from AutoML.Net side, train can still continue, it's just all the result will be NaN or infinity and doesn't have real meaning.

> Is it possible to get an average score of infinity in a case different from having an empty label column
another example is empty feature column, there must be other cases when an average score of infinity or NaN is get. @justinormont  can you provide more examples?

**Comment by LittleLittleCloud** [comment]
@justinormont Thanks for pointing that out. @antoniovs1029 so the only thing that needs to be changed is `GetIndexClosestToAverage()`. Could you get a quick fix for that? I can also take it if your bandwidth is full

**Comment by antoniovs1029** [comment]
@LittleLittleCloud If you're able to do this, I'd appreciate it 😄 since I have some other things on my plate right now.
