### ISSUE TITLE
How to re-train onnx model in ml.net

### ISSUE THREAD

**Issue by ladodc** [dotnet/machinelearning#5340]
### System information

- **OS version/distro**: Win10

- **.NET Version (eg., dotnet --info)**: .Net Core 3.1

### Issue

Hi I am trying to re-train model saved in onnx format. I can inference this model with onnxruntime in .net but retraining without success. What I am doing wrong? Is this in .net possible? Here is my model:[logres_scikit_pipeline.zip](https://github.com/dotnet/machinelearning/files/5051258/logres_scikit_pipeline.zip)

### Source code
`
var MODEL_PATH = @"..\..\..\Model\logres_scikit_pipeline.onnx";
                
                var pipeline = mlContext.Transforms.ApplyOnnxModel(modelFile: MODEL_PATH, inputColumnNames: inputColumnNames,
                    outputColumnNames: new[] { "output_probability", "output_label" });

                var model = pipeline.Fit(newData);
              
                using (var stream = File.Create(MODEL_PATH))
                {
                    mlContext.Model.ConvertToOnnx(model, newData, stream);
                }
`

> On ConvertToOnnx, I got following Exception: The targeted pipeline can not be fully converted into a well-defined ONNX model. Please check if all steps in that pipeline are convertible to ONNX and all necessary variables are not dropped (via command line arguments).

**Comment by antoniovs1029** [comment]
Hi, @ladodc . Retraining a pretrained onnx model isn't possible on ML.NET so I will tag this as a feature request so we can think about implementing this on the future. Still, I don't think it will be a simple feature to implement, since once you have a pretrained onnx model (such as the one you have), it's not possible to know how was it trained or how to retrain it.

Also, please notice that ML.NET only supports re-train for the following trainers:
https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/retrain-model-ml-net

And also notice that ML.NET's OnnxTransformer isn't onnx exportable. This means that you can't export to onnx a ML.NET model that includes a "ApplyOnnxModel()" in the pipeline.

**Comment by ladodc** [comment]
Hi Antonio, 

thanks for your response. It would be nice to have such a feature in the future.

Best Regards Lado

**Comment by luisquintanilla** [comment]
Thanks for the feature request. Closing this issue since an answer was provided and it's not currently widely possible using ONNX. ONNX is intended to be used for inference at this time with limited training support. If / when ONNX makes this available we can reevaluate adding it to ML.NET.
