### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/machinelearning#536]
Hello folks!

Trying to make ML.Net to work on mono-wasm but I just figured out the hard way that it only works on x64:

![image](https://user-images.githubusercontent.com/4714040/42738687-1104bf6e-885e-11e8-813b-e55a91976ccc.png)

Is there any chance to get the native part built to wasm?

Thanks!

**Comment by MrCSharp22** [comment]
I believe you are talking about Blazor WASM apps. In which case, i think that supporting WASM is of low priority because i don't expect a Blazor app to train or call the model directly to predict stuff.
If you have a Blazor app then it is better to have another WebApi (for example) to back it by doing Model training on the server and making predictions too.

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: For v1.0 we plan to support only x64 (and maybe x86). So I'm moving this issue to backlog.

**Comment by galvesribeiro** [comment]
@MrCSharp22 just like you have Xamarin that can use ML with CoreML for example on the mobile devices, client-side apps like Blazor could leverage that as well without requiring a server. For more info on CoreML+Xamarin, have a look at this: https://docs.microsoft.com/en-us/xamarin/ios/platform/introduction-to-ios11/coreml

@ivanbasov I understood there wasn't a big investment of time on that but is the native part of ML.Net reasonable dependency-free that can easily built targeting other platforms?

**Comment by codemzs** [comment]
We don't plan to support mono anytime soon.

**Comment by John0King** [comment]
@codemzs   this time is's not mono, it the .net 5 , when will the Android,IOS, and WASM be support?
