### ISSUE TITLE
Local GPU training fails with Image Classification scenario using Model Builder

### ISSUE THREAD

**Issue by frogcrush** [dotnet/machinelearning#5419]
### System information

- **OS version/distro**: Windows 10 2004
- **.NET Version (eg., dotnet --info)**: 5.0.100-rc.1.20452.10

### Issue

- **What did you do?**
Tried using ML.NET Model Builder with my GTX 1070 to run an image classification scenario.

- **What happened?**
VRAM spikes to 99% usage, then exceptions are printed in the logs and the training fails.

- **What did you expect?**
Training to succeed.

### Source code / logs
[log.txt](https://github.com/dotnet/machinelearning/files/5337885/log.txt)

**Comment by frogcrush** [comment]
This occurred both when using a small dataset (~10 images of each classification) and a large dataset (2000 of each)

**Comment by michaelgsharp** [comment]
looking through the log file you sent, I see this error several times.
`Failed to get convolution algorithm. This is probably because cuDNN failed to initialize`
Can you make sure that cuDNN is installed and setup correctly? It appears that is the reason for the crash. Let me know what happens after you check on that.

**Comment by mstfbl** [comment]
Closing this issue as no input was received from author. Please feel free to reopen this issue if any additional information is shared. Thanks.

**Comment by gkomix88** [comment]
Hi, got "This is probably because cuDNN failed to initialize" issue.

I installed CUDA 10.0 and cudnn 7.6.4, followed the instruction on this link https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder.

I also checked the path is only to 
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp

Any configuration I need to take note in order to run the image classification with GPU?

Thanks in advance.
