### ISSUE TITLE
Suddenly unable to load DLL 'CpuMathNative' on F#

### ISSUE THREAD

**Issue by halcwb** [dotnet/machinelearning#5480]
### System information

.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    5b6f5e5005

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.401\

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]

 - Microsoft.ML 1.5.2
 - Microsoft.ML.FastTree 1.5.2
 - Microsoft.ML.Mkl.Components 1.5.2
 - Newtonsoft.Json 12.0.3
 - System.Threading.Channels 4.7.1
 - System.Memory 4.5.4
 - System.CodeDom 4.7.0
 - System.Reflection.Emit.Lightweight 4.7.0
 - Microsoft.ML.CpuMath 1.5.2
 - Microsoft.ML.DataView 1.5.2
 - Microsoft.ML.Mkl.Redist 1.5.2
 - System.Collections.Immutable 1.7.1
 - System.Reflection.Emit.ILGeneration 4.7.0
 - System.Threading.Tasks.Extensions 4.5.4
 - System.Runtime.CompilerServices.Unsafe 4.7.1
 - System.Buffers 4.5.1
 - System.Numerics.Vectors 4.5.0

### Issue

- **What did you do?**
I tried to run a trainer `context.BinaryClassification.Trainers.SdcaLogisticRegression`. 
- **What happened?**
With the exact same code, on the exact same machine without any changes, first it ran without problems, then, suddenly I get:

> Unable to load DLL 'CpuMathNative' or one of its dependencies

I am absolutely sure that before I was able to use that trainer. 
I am absolutely sure that I did this using netstanderd2.0
I also tried setting to netcoreapp3.1 and net72, with the same error.

I DID NOT EVEN RESTART BUT THIS HAPPENED WHILE WORKING!!

This is weird???

- **What did you expect?**

To be able to continue to run the same code on the same machine.

### Source code / logs

**Note** The below code DID RUN 

```fsharp
open Microsoft.ML
open Microsoft.ML.Data

let printDataMetrics (trainData : Data seq) (testData : Data seq) =
    printfn "*       Metrics for train and test data      " 
    printfn "*-----------------------------------------------------------"
    printfn "*       Model trained with %i records" (trainData |> Seq.length)
    printfn "*       Containing %i deaths" (trainData |> Seq.filter (fun d -> d.Death) |> Seq.length)
    printfn "*       Model tested with %i records" (testData |> Seq.length)
    printfn "*       Containing %i deaths" (testData |> Seq.filter (fun d -> d.Death) |> Seq.length)
    printfn ""
    

let printCalibratedMetrics (metrics : CalibratedBinaryClassificationMetrics) =
    printfn "*       Metrics for binary classification model      " 
    printfn "*-----------------------------------------------------------"
    printfn "*       Accuracy: %.3f" metrics.Accuracy
    printfn "*       Area Under Roc Curve: %.3f" metrics.AreaUnderRocCurve
    printfn "*       Area Under PrecisionRecall Curve: %.3f" metrics.AreaUnderPrecisionRecallCurve
    printfn "*       F1 Score: %.3f" metrics.F1Score
    printfn "*       LogLoss: %.3f" metrics.LogLoss
    printfn "*       LogLoss Reduction: %.3f" metrics.LogLossReduction
    printfn "*       Positive Precision: %.3f" metrics.PositivePrecision
    printfn "*       Positive Recall: %.3f" metrics.PositiveRecall
    printfn "*       Negative Precision: %.3f" metrics.NegativePrecision
    printfn "*       Negative Recall: %.3f" metrics.NegativeRecall

let printNonCalibratedMetrics (metrics : BinaryClassificationMetrics) =
    
    printfn "*       Metrics for binary classification model      " 
    printfn "*-----------------------------------------------------------"
    printfn "*       Accuracy: %.3f" metrics.Accuracy
    printfn "*       Area Under Roc Curve: %.3f" metrics.AreaUnderRocCurve
    printfn "*       Area Under PrecisionRecall Curve: %.3f" metrics.AreaUnderPrecisionRecallCurve
    printfn "*       F1 Score: %.3f" metrics.F1Score
    printfn "*       Positive Precision: %.3f" metrics.PositivePrecision
    printfn "*       Positive Recall: %.3f" metrics.PositiveRecall
    printfn "*       Negative Precision: %.3f" metrics.NegativePrecision
    printfn "*       Negative Recall: %.3f" metrics.NegativeRecall

// Calculate the model using the training data,
// and test data for the metrics. Include the features
// (Data column names) that has to be included in the model.
let calculate trainData testData features =
    let context = MLContext()

    let trainView = context.Data.LoadFromEnumerable trainData
    let testView = context.Data.LoadFromEnumerable testData
    
    let pipeline =
        let features = features |> Seq.toArray
        EstimatorChain()
            .Append(context.Transforms.Concatenate("Features", features))
            .Append(context.BinaryClassification.Trainers.SdcaLogisticRegression("Death", "Features"))

    let trained = pipeline.Fit(trainView)

    let predicted = trained.Transform(testView)

    let metrics = 
        //context.BinaryClassification.EvaluateNonCalibrated(data=predicted, labelColumnName="Death", scoreColumnName="Score")
        context.BinaryClassification.Evaluate(data=predicted, labelColumnName="Death", scoreColumnName="Score")


    printDataMetrics trainData testData
    metrics
    |> printCalibratedMetrics

```

**Comment by halcwb** [comment]
I quick and dirty fix is to manually copy the CpuMathNative to the .nuget packages lib folder for microsoft.ml.cpumath.

**Comment by antoniovs1029** [comment]
Hi.

Can you please provide a .zip file containing your project that reproduces this error?. In particular, you mention that the code snippet you provided ran correctly, but that's odd since CpuMathNative is used when training a Sdca model. So I'm afraid I don't know what could be causing the problem.

If the code snippet you provided ran successfully, where did you actually found the error?

Thanks.

**Comment by halcwb** [comment]
@antoniovs1029 Thanks for looking into this. I cannot reproduce the problem, i.e. the problem occurred and than didn't go away. But the really strange thing is that it ran in the first place. 

As I understand now, CpuMathNative has to be copied over to the build folder? I am actually using ML in a F# script file loading dependencies using `paket generate-load-scripts`. So the runtime CpuMathNative isn't copied over to the folder where microsoft.ml.cpumath is called. 

Could that be the problem?

**Comment by antoniovs1029** [comment]
CpuMathNative DLL does need to be present while training a SDCA model, as the following calls need the dll:
https://github.com/dotnet/machinelearning/blob/c255ac7c45af7a19a6e5ab1e26fdbe44874f241a/src/Microsoft.ML.StandardTrainers/Standard/SdcaBinary.cs#L873-L876

So it's also weird to me that it worked at first, and then it didn't. For instance, those calls are nested in a conditional depending on `l1ThresholdZero` which in turn depends on the value you're using for L1Regularization. The calls are also nested on some other if statements which, after a very quick look into the code, seem to be affected by "random" things such as race conditions, or the results of math operations that might not be subject to numerical stability variations. So it might be perhaps because of these that it didn't hit this problem at first, out of luck, or maybe you were using a different (smaller) dataset when you didn't hit this issue? It's still very odd, but I guess it could happen.

> I am actually using ML in a F# script file loading dependencies using paket generate-load-scripts. So the runtime CpuMathNative isn't copied over to the folder where microsoft.ml.cpumath is called.

Oh, I see. I'm not familiar with the F# ecosystem, or the `paket generate-load-scripts` tool you mention. In C# simply adding the Microsoft.ML.CpuMath nuget is expected to automatically copy the DLL to the correct place.

After quickly looking [into the paket tool](https://fsprojects.github.io/Paket/paket-generate-load-scripts.html), it's unclear to me if it should automatically detect that it should also copy the DLL or not? @halcwb are you able to modify anything on the tool so that it copies the DLL correctly? Is manually copying it yourself an acceptable solution?

//cc: @eerhardt who might know something about handling our DLL dependencies on this F# tool.

**Comment by eerhardt** [comment]
A few thoughts:

1. When using `netcoreapp3.1` or higher, ML.NET will not try to use CpuMathNative. Instead, it will use the C# Hardware Intrinsics APIs without the native CpuMathNative assembly.
2. Is it possible the CpuMathNative.dll was deleted from your nuget cache?

It's good to hear that you are no longer experiencing this issue.

**Comment by halcwb** [comment]
@eerhardt, @antoniovs1029. Thanks for looking into this. 

@eerhardt : The CpuMathNative.dll is in the nuget cache, only it resides in a 'runtime' folder. When using F# you have a load script that references from the lib folder. I think that CpuMathNative has to be in the same lib folder. Also, when compiling the CpuMathNative.dll is copied over to the compile folder (bin/Debug or Release or whatever), this doesn't happen when just referencing in the FSI.
