### ISSUE TITLE
LocalizeRootCauses not returning results for some points, even with "IsAnomaly":true and high deltas in the localization input

### ISSUE THREAD

**Issue by nnoradie** [dotnet/machinelearning#5592]
### System information

- **OS version/distro**:
- **.NET Version (eg., dotnet --info)**: 
![image](https://user-images.githubusercontent.com/69877427/104793862-102ca800-5759-11eb-95bb-ea0baac51236.png)

### Issue

- **What did you do?**
    - Call LocalizeRootCauses on various anomaly points

- **What happened?**
    - There were time series points that were found to be an anomaly, but no root causes were returned in the results

- **What did you expect?**
    - At least one root cause to be returned

### Source code / logs
zip contains csv with the localization input and output serialized to json. 
[localization_input.zip](https://github.com/dotnet/machinelearning/files/5823641/localization_input.zip)

For all cases, rootCauseThreshold=0.55, beta=0.

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by suxi-ms** [comment]
This is because the anomaly point is not in the point list provided by you data, in this case, the algorithm won't calculate the root cause. To get your result, you can add the anomly point in your localization input's points. This is also explained in the code. refer [here ](https://github.com/dotnet/machinelearning/blob/927a61a354649a90d623a7f0676157523bbd49bc/src/Microsoft.ML.TimeSeries/RootCauseLocalizationType.cs#L42)for more details.

**Comment by nnoradie** [comment]
Hi @suxi-ms, but we do include the anomaly point in each of our points lists that we send to the API. It's included here in the json I atached to the issue
![image](https://user-images.githubusercontent.com/69877427/105213164-38bef400-5b03-11eb-8c54-80afe5d8d4b5.png)
![image](https://user-images.githubusercontent.com/69877427/105213250-54c29580-5b03-11eb-8d9d-57d427c57a56.png)

**Comment by suxi-ms** [comment]
For the first input, 
the first two points has different changed direction compared with the aggragted anomaly point, so they are not picked as root cause contributor.
For the second input,
the first point doesn't change having a 0 delta, so it is not picked as the contributor as the aggregated point's expected value is larger than the actual value.

**Comment by nnoradie** [comment]
Thank you for meeting with me and explaining this @suxi-ms , i'll go ahead and close the issue
