### ISSUE TITLE
v1.5.4 model training failing

### ISSUE THREAD

**Issue by vivek-kumar-gupt** [dotnet/machinelearning#5593]
### System information

- **OS version/distro**: Windows 10 pro x64
- **.NET Version (eg., dotnet --info)**: .net framework 4.6/4.7

### Issue

- Tried training a model for image classification based on example "Image Classification Model Training" from "machinelearning-samples" repository
- Process execution failed with unhandled exception while training model 
- Expected that the example should have worked (tried with release v1.5.4)

### Source code / logs

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'TF_StringEncodedSize' in DLL 'tensorflow'.
   at Tensorflow.c_api.TF_StringEncodedSize(UInt64 len)
   at Microsoft.ML.Vision.ImageClassificationTrainer.EncodeByteAsString(VBuffer`1 buffer)
   at Microsoft.ML.Vision.ImageClassificationTrainer.ImageProcessor.ProcessImage(VBuffer`1& imageBuffer)

**Comment by vivek-kumar-gupt** [comment]
My bad. I was referencing latest Scisharp redist, which is v2.4.0, while tensorflow 0.2 is referencing v2.3.0. After downgrading redist to 2.3.0, it is working fine

**Comment by justinormont** [comment]
Interestingly, I just hit the same issue. Thanks @vivek-kumar-gupt for the solution. 

Also, on at least MacOS, adding the `SciSharp.Tensorflow.Redist` NuGet is required to get TensorFlow running. Otherwise it gets the error: `System.DllNotFoundException: Unable to load shared library 'tensorflow' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libtensorflow, 1): image not found`.

Should we have `Microsoft.ML.TensorFlow` depend on `SciSharp.Tensorflow.Redist@2.3.0`? As a complication, there are also GPU NuGets, which may require exactly one being installed.

**Comment by justinormont** [comment]
Ahh, I see we removed the dependency a while back. Ref: https://github.com/dotnet/machinelearning/issues/4449#issuecomment-552019010

Perhaps we could have a more user friendly error message instructing the user to install one of the three Nugets (and the correct version to install)?
