### ISSUE TITLE
Use .NET Core Hardware Intrinsics to optimize the code?

### ISSUE THREAD

**Issue by helloguo** [dotnet/machinelearning#56]
It's great to see a C# machine learning framework!

It seems some linear algebra algorithms are implemented by calling into native cpp code. I assume this is due to the rich SIMD instructions in cpp. Since .NET Core 2.1 has the preview feature of Hardware Intrinsics, using hardware intrinsics is another option to use SIMD instructions.

**Comment by helloguo** [comment]
cc\ @asthana86

**Comment by helloguo** [comment]
Relate to https://github.com/dotnet/machinelearning/issues/97

**Comment by danmosemsft** [comment]
This is done for x86/x64 with some remaining issues here https://github.com/dotnet/machinelearning/issues/823
Perhaps you would like to tackle any of those, @helloguo ?

When ARM intrinsics are offered by .NET, we could add implementations for those.

I believe this issue is done, otherwise. Thanks for suggesting it to us.

**Comment by danmosemsft** [comment]
And please try it!
