### ISSUE TITLE
Calculated Feature

### ISSUE THREAD

**Issue by gironymo** [dotnet/machinelearning#595]
Hello,

is there a way to add a calculated feature?
I get the data in a CSV-File which is loaded with a TextLoader. I'm not able to affect the data in the file. For My model I would use a calculated feature (e. g. NewFeature = Feature1 + Feature2) or any other calculations like manual binning (e. g. if Feature1 < 10 then NewFeature = 1 else if Feature1 >= 10 and Feature1 < 20 then NewFeature = 2 else NewFeature = 3).

In the Azure Machine Learning Studio are some tasks which can be used for e. g. SQL Transformation, R-Scripts ...

**Comment by WladdGorshenin** [comment]
Hi, I'm also curious how can I convert a date field to a set of new fields like: year, month, day_of_month, day_of_week, etc?

**Comment by abhiongithub** [comment]
for dynamic fields using .NET Dictionaries  Dictionary<"YourNewField",Value>

**Comment by Zruty0** [comment]
Hi @gironymo ,

Your and @WladdGorshenin 's cases are perfect examples of why we want to have https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Api/MapTransform.cs available through the user API.

When it is done, you will be able to add your own transformations to the pipeline, and mix&match them with the standard ones provided by ML.NET.

Right now, even though `MapTransform` is available as a public class, you will have to rewrite your entire experiment to use low-level API (and not `LearningPipeline`) in order to use it. 

Once we resolve #371 and #581, we will reconcile the two.

**Comment by WladdGorshenin** [comment]
Hi @abhiongithub could you please elaborate a bit more?

**Comment by Zruty0** [comment]
@WladdGorshenin , the comment from @abhiongithub  seems to me more like a feature request. 

We definitely do not support dictionaries as sources of data right now. Nor do we have plans to do this in the near future, unless there is a compelling argument that outweighs the perf and data consistency implications of this potential feature.

**Comment by WladdGorshenin** [comment]
@Zruty0 is there any workaround?

**Comment by Zruty0** [comment]
@WladdGorshenin I assume you are referring to this: 
>  how can I convert a date field to a set of new fields like: year, month, day_of_month, day_of_week, etc?

My best recommendation at the moment would be to perform this pre-processing prior to giving this object to ML.NET.

Actually, now that we're merging #616 , you should be able to get away with something like this:
```c#
        public class MyDataRow
        {
            private DateTime _dateTime;

            public float Day { get { return _dateTime.Day; } set { throw new NotImplementedException(); } }
            public float DayOfWeek { get { return (float)_dateTime.DayOfWeek; } set { throw new NotImplementedException(); } }
            // etc
        }
```

**Comment by Zruty0** [comment]
I think this should be closed. Feel free to reopen to add more comments.
