### ISSUE TITLE
 MS ML.NET doesn't work with latest GPU!

### ISSUE THREAD

**Issue by MiroslavKabat** [dotnet/machinelearning#6000]
I was using station with `Geforce RTX 2080 Ti` (Cuda Compute Capability 7.5) for development and everything was fine and works pretty well. 
Now we are publishing our solution on station with `RTX A6000` Cuda Compute Capability 8.6) and MS Model Builder, MS ML.NET and direct programming in python (tensorflow) is super slow or stuck without any error message with same configuration like in dev station. 
(for example loading onnx model takes 6 minutes instead of 2 seconds and prediction never start instead of calculate task is several milliseconds)

Tensorflow in python with cuda 11.2 & cudnn 8.1 works fine.
Tensorflow in python with cuda 10.1 & cudnn 7.6.4 (which is nessesary for MS ML.NET!) is slow or stuck in TF & MS ML.NET.

I am not only one with those issues [nvidia - dev forum](https://forums.developer.nvidia.com/t/slow-startup-and-model-loading-time/173398)

I just wanna ensure if MS ML.NET supports latest GPUs or how can I solve those issues? 
Thank you for answer.

```
Configuration:
Windows 10 Pro - 21H1

ML.NET 1.6 | 1.5.5 | 1.7-Preview
SciSharp.TensorFlow.Redist-Windows-GPU 2.3.1
Python 3.8.10, pip 21.3.1, tensorflow 2.3.1 or 2.7.0

cuda_10.1.105_418.96_win10
cudnn-10.1-windows10-x64-v7.6.4.38

or 

cuda_11.2.2_461.33_win10
cudnn-11.2-windows-x64-v8.1.1.33
```

**Comment by Daniel-Walther** [comment]
I can absolutely agree with that!
On my Surface with an 'old' GeForce GTX 1050 I got good and fast results.
On my Power-PC with a new GeForce RTX 3060 the exact same code (and same data) is extremely slow AND THE RESULTS OF IMAGE CLASSIFICATION ARE WRONG!

On both machines the configuration is the same:
Windows 11
Visual Studio 2019 
Microsoft.ML 1.7.0
Microsoft.ML.Vision 1.7.0
SciSharp.Tensorflow.***-GPU 2.3.1
CUDA 10.1
cudnn 8.1

Since Microsoft.ML 1.7 runs only with SciSharp.Tensorflow.***-GPU 2.3.1 which runs only with CUDA 10.1 I'm looking forward for the next build of Microsoft.ML which is hopefully runs with a new SciShart version (and so with a new CUDA version).

**Comment by michaelgsharp** [comment]
Since we have this being tracked in the other issue that @Daniel-Walther created, I'm going to go ahead and close this issue so we can keep all the info in one place.

I'm hoping the upgrade to the latest version of Tensorflow.net is painless so that its a quick fix to get in.
