### ISSUE TITLE
New PFI API, inconstancies in return types for Binary vs Regression and MultiClass 

### ISSUE THREAD

**Issue by aforoughi1** [dotnet/machinelearning#6027]
**System Information (please complete the following information):**
 - OS & Version: Windows 11
 - ML.NET Version: 1.7
 - .NET Version:  NET 5.0

**Describe the bug**
I tried to write a generic method to Calculate PFI  using the New PFI API which was released  as part of Ml.Net 1.7.
Firstly, The online documentation is not matching the release.
See https://docs.microsoft.com/enus/dotnet/api/microsoft.ml.permutationfeatureimportanceextensions
Secondly, the return types for Regression and Multiclass is Dictionary but Binary is an Array
 ImmutableDictionary<string,RegressionMetricsStatistics>
 ImmutableDictionary<string,MulticlassClassificationMetricsStatistics>
 Immutable.ImmutableArray<BinaryClassificationMetricsStatistics> 

Is this a bug ?

**Comment by aforoughi1** [comment]
typo error, It is 
Immutable.ImmutableArray<BinaryClassificationMetricsStatistics>

**Comment by aforoughi1** [comment]
Apologies, It is not the return type issue but the compiler reports that  'BinaryClassificationCatalog' does not contain a definition  for PermutationFeatureImportance.

**Comment by michaelgsharp** [comment]
Can you double check? All the extension for PFI are in the same file, so if you have them for the others you should have them for BinaryClassificationCatalog as well. Make sure you are using version 1.7.

**Comment by aforoughi1** [comment]
yes, I am using 1.7.0
please see the attached test sample
[Test6027.zip](https://github.com/dotnet/machinelearning/files/7846079/Test6027.zip)

**Comment by michaelgsharp** [comment]
Ah, the method name isn't just `PermutationFeatureImportance`, its `PermutationFeatureImportanceNonCalibrated`. That was done because the original `PermutationFeatureImportance` is specifically evaluating "non calibrated" metrics, so we renamed the new PFI API to correctly show that and to leave room to add one that is for "calibrated" metrics. If you change the method you are calling to be `PermutationFeatureImportanceNonCalibrated` it will work correctly.

Closing this issue for now since this resolves the issue, but feel free to reopen it if you have further issues.

**Comment by aforoughi1** [comment]
I changed the sample to 
var pfiDict = context.BinaryClassification.PermutationFeatureImportanceNonCalibrated(model, predictions);
however, I get
System.ArgumentNullException: 'The model provided does not have a compatible predictor Arg_ParamName_Name'

**Comment by JakeRadMSFT** [comment]
@michaelgsharp I'm also hitting this issue

**Comment by JakeRadMSFT** [comment]
[TaxiModel_Notebook5.txt](https://github.com/dotnet/machinelearning/files/8039013/TaxiModel_Notebook5.txt)

(Save as IPYNB)
