### ISSUE TITLE
Model builder complains about version to use

### ISSUE THREAD

**Issue by raffaeler** [dotnet/machinelearning#6152]
**System Information (please complete the following information):**
 - OS & Version: Windows 10
 - ML.NET Version: ML.NET v1.7.1
 - .NET Version: .NET 6.0
 - Model Builder version: 16.13.1.2210302

**Describe the bug**
![image](https://user-images.githubusercontent.com/5183152/162583473-cba321c1-96fe-41c5-af70-1e5e020ed335.png)

**To Reproduce**
1. Start from a Console app
2. Add the model builder item
3. Scenario: Value Prediction
4. Follow the wizard
5. At the end of training the weird message appears

**Expected behavior**
Model builder should suggest to downgrade the the version of the library

**Comment by michaelgsharp** [comment]
@JakeRadMSFT @LittleLittleCloud This is for you guys.

**Comment by michaelgsharp** [comment]
I'll mark this as "Future" for now, but feel free to change this as needed.

**Comment by luisquintanilla** [comment]
There have been several releases since this issue was opened. 

@raffaeler 
I would recommend [upgrading to the latest version](https://learn.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-model-builder?tabs=visual-studio-2022#upgrade-model-builder). If you still run into this issue, please let us know. 

Closing for now.
