### ISSUE TITLE
Retrieve positive contributors and negative contributors from CalculateFeatureContribution

### ISSUE THREAD

**Issue by AbhayGaur** [dotnet/machinelearning#6163]
For the explainability section of ml.net, I am using CalculateFeatureContribution to calculate the feature contribution of each individual feature and then represent it on a UI.

Problem that I have right now is, even after using the number of positive contributors = 10 and number of negative contributors = 10, I still have to traverse through all the feature vector, which is highly sparse and large, to identify which actual features were the top contributing. 

Is there any optimal way to do this computation or the most optimal way is to traverse through all the features and then use the given information in O(n) where n=number of total features.

**Comment by michaelgsharp** [comment]
@AbhayGaur off the top of my head I am not sure if there is any other way. Let me take a look and see what I can find out.

@luisquintanilla @JakeRadMSFT are either of you familiar with this?

**Comment by AbhayGaur** [comment]
@michaelgsharp anything that you were able to find, thanks for the help!

**Comment by LittleLittleCloud** [comment]
@AbhayGaur looks like you are using five `FeaturizeText` in your processing pipeline, so it's likely that the encoded feature would be a sparse matrix by itself because `FeaturizeText` uses n-gram underlying (correct me if it's not the case @michaelgsharp). So I would not be too surprised to see most of the values in the feature contribution array are also zero.

As for the optimal way to retrieve the feature with highest/lowest contribution, in sparse matrix cases, it would be more efficient for `CalculateFeatureContribution` estimator to return just a feature contribution array whose value is not 0, plus a feature index array to indicate the index of those features. But that way would bring unnecessary extra cost for non-sparse situation, and I wonder if it's the right way to go.

**Comment by michaelgsharp** [comment]
Thanks for your comments @LittleLittleCloud. Closing this as it appears the question has been answered, but feel free to open a new issue if you have further questions.
