### ISSUE TITLE
ARM architecture support for scoring

### ISSUE THREAD

**Issue by andrasfuchs** [dotnet/machinelearning#6214]
**Is your feature request related to a problem? Please describe.**
Microsoft.ML currently supports 'x64' and 'x86' processor architectures.

**Describe the solution you'd like**
I would like to see support for ARM architectures, at least for scoring.

**Additional context**
This feature was requested before (#1662, #1790) in 2018. @codemzs closed that issue, because ARM support was not on their short term roadmap back then.

Could you give us an update on this? Can we anticipate ML.NET ARM support in the future?

**Comment by luisquintanilla** [comment]
Hi @andrasfuchs 

Are you running into issues with ARM? If so, could you please provide more details. This feature has been available since last year. 

https://devblogs.microsoft.com/dotnet/ml-net-june-updates-model-builder/#ml-net-on-arm

**Comment by andrasfuchs** [comment]
@luisquintanilla Hmm, strange, I tried to run my ML.NET code on my Raspberry Pi 4, and I got the error I mentioned above in the description of the issue.

I don't have my prototype by me now, so I can give you more details only in a few weeks, sorry!

**Comment by michaelgsharp** [comment]
@andrasfuchs this is because we still have a check for this. To bypass it set the msbuild property `EnableMLUnsupportedPlatformTargetCheck` to false. We haven't quite figured out the best way to handle this, as just removing it causes other issues. It would be easy though to change the check so it doesn't get flagged for arm/arm64 targets.

I'm going to close this issue for now, but set that property and it will be bypassed and I'll get the check to not flag on arm/arm64,

**Comment by andrasfuchs** [comment]
@michaelgsharp Thank you!

Just to make sure I understand it correctly: since you added/will add arm and arm64 to the supported platform check condition, the next ML.NET version should work on Raspberry without a custom build with the msbuild property change you mentioned above, right?

But if I don't want to wait until then, I can still build it now with that property set to false, can't I?

**Comment by michaelgsharp** [comment]
Thats correct. The next release shouldn't need you to set that parameter, but for now you can workaround the issue by setting that parameter as part of your build.
