### ISSUE TITLE
Strange error in AutoML

### ISSUE THREAD

**Issue by CBrauer** [dotnet/machinelearning#6570]
**My System Information is:**
-Microsoft Visual Studio Professional 2022
-Version 17.5.0 Preview 6.0
-VisualStudio.17.Preview/17.5.0-pre.6.0+33402.96
-NET 7.0

**Describe the bug**
The production code was running fine with ML.NET version 1.7.1.

Here is a screen shot of the error:

![AutoML Bug](https://user-images.githubusercontent.com/1317234/219145269-4981a058-7c4a-47a0-a399-82c95e145995.PNG)

I have put a complete, reproducible solution with data on my GitHub account:
https://github.com/CBrauer/Error-in-AutoML

This is a complete reproducible solution that demonstrate the error.
Please let me know if you see the same error message.

Charles

**Comment by LittleLittleCloud** [comment]
It's because `PositiveRecall` metric is somehow not implemented in current Binary Classification Experiment

https://github.com/dotnet/machinelearning/blob/fe2a4428c1116ba6af1d033bd1c61816aad8593b/src/Microsoft.ML.AutoML/API/BinaryClassificationExperiment.cs#L384

I'll push a PR to fix that later. In the meantime you are also very welcome to submit a fix if you want to. Happy coding!
