### ISSUE TITLE
Split TextClassification API

### ISSUE THREAD

**Issue by maheshlokhande** [dotnet/machinelearning#6671]
TextClassification API was introduced in ML.NET 2.0 release. As per documentation it internally uses BERT to generate embeddings and deep learning for classification. Is there a way to train BERT model with our own data and generate embeddings and then eventually use some deep learning technique to do classification (both in ML.NET). It will enable developers to try the combination that works best for their use case.

**Comment by maheshlokhande** [comment]
Let me know if my request needs to be elaborated further for more clarity. Happy to do that. Thanks.

**Comment by michaelgsharp** [comment]
Currently that is not available, in part because every model has its specific formats it needs and so changing that up will probably result in bad behavior (crashes/incorrect results/etc). That being said, we do want to allow users to be able to bring their own TorchSharp models and we are working towards that. No ETA at this point in time though.
