### ISSUE TITLE
Generative Adversarial Network

### ISSUE THREAD

**Issue by tianweimol** [dotnet/machinelearning#6955]
how can i use GAN(Generative Adversarial Network) by ml.net
thanks for your answer

**Comment by michaelgsharp** [comment]
@luisquintanilla thoughts here? @tianweimol can you share more information on your scenario?

**Comment by tianweimol** [comment]
> @luisquintanilla thoughts here? @tianweimol can you share more information on your scenario?

saddly,i have  give up ,and use python to program.

**Comment by luisquintanilla** [comment]
> > @luisquintanilla thoughts here? @tianweimol can you share more information on your scenario?
> 
> saddly,i have give up ,and use python to program.

Sorry to hear that. This is not something that we plan on making available in ML.NET at this time but if you wanted to build one with .NET, we encourage you to give [TorchSharp](https://github.com/dotnet/torchsharp) a try if you want to build your own from scratch. Otherwise you might be able to leverage [pretrained versions with ONNX](https://khalidabuhakmeh.com/image-style-transfer-with-csharp-onnx-and-imagesharp) for example with tasks like Transfer Learning.
