### ISSUE TITLE
Best way to convert Datatable to Dataframe

### ISSUE THREAD

**Issue by chuongmep** [dotnet/machinelearning#7036]
**Is your feature request related to a problem? Please describe.**
Hi, 
Do we have any way to fast convert from `System.Data.Datatable` to `Microsoft.Data.Analysis.DataFrame` ?

I tried with my solution but it still too slow

**Describe the solution you'd like**

```csharp
public static Microsoft.Data.Analysis.DataFrame ToDataFrame(this DataTable dataTable)
    {
        Microsoft.Data.Analysis.DataFrame dataFrame = new Microsoft.Data.Analysis.DataFrame();

        foreach (DataColumn column in dataTable.Columns)
        {
            // get values from column cast as string
            string[] values = dataTable.AsEnumerable().Select(r => r.Field<object>(column.ColumnName)?.ToString()).ToArray();
            DataFrameColumn dataFrameColumn = DataFrameColumn.Create(column.ColumnName, values);
            dataFrame.Columns.Add(dataFrameColumn);
        }
        return dataFrame;
    }
```

**Describe alternatives you've considered**

- I want keep format column type and quick convert between them.

**Additional context**

**Comment by asmirnov82** [comment]
Hi @chuongmep, if you are reading your data from the database you can use `DataFrame.LoadFrom(DbDataAdapter adapter)` method,  in other case you may try to use `DataFrame.LoadFrom(IEnumerable<IList<object>> vals, IList<(string, Type)> columnInfos)`. These methods are also quite slow, because they add data row by row, but there is a chance that it is still faster as there isn't any values conversion to strings

**Comment by chuongmep** [comment]
Thank you for your help !
