### ISSUE TITLE
Feature Selection

### ISSUE THREAD

**Issue by lefig** [dotnet/machinelearning#749]
Hi all,

Feature selection is an important part of any ML workflow. This is required to exclude too highly correlated labels from model fitting.  So rather than a process of trial and error I was hoping to select the best training model/evaluator based on running an initial feature selection action.

Judging from the API documentation this may well be possible. For instance, we have the

RankerEvaluator Class  

Has anyone used this or any other aspect of the framework to help identify over fitting labels or best model to run?

In python I would manually do some correlation analysis and perhaps try something like TPOT to make a recommendation but would far prefer to stay in the world of C# and this excellent tool.

Best regards

Fig

**Comment by CESARDELATORRE** [comment]
Since version 0.8 we have some possible approaches for "Model Explainability" and "Feature Selection":
https://blogs.msdn.microsoft.com/dotnet/2018/12/04/announcing-ml-net-0-8-machine-learning-for-net/#model-explainability

See additional info on v0.9 that we'll release pretty soon and talk about it at the .NET Blog focusing on "Feature Contribution Calculation and other model explainability improvements" in ML.NET 0.9.
