### ISSUE TITLE
SchemaShape's metadata to also be SchemaShape

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#755]
Currently, the 'metadata shape' associated with the column is a list of strings.

It is already somewhat problematic, because it doesn't have the associated types. 

We should instead make it a `SchemaShape` on its own.

**Comment by TomFinley** [comment]
Thanks @Zruty0. At least the key-to-value transform I think needs this, since it cannot infer the type of its output, without knowing the type of the keyvalues.

**Comment by TomFinley** [comment]
Starting now. It's not going too badly.

Nonetheless I have one thing that's confusing me. I have this note here.

https://github.com/dotnet/machinelearning/blob/5654d7265e54264db869bbc7fb0e3c1264091c21/src/Microsoft.ML.Core/Data/IEstimator.cs#L75-L77

That intuitively makes sense. If this object represents *requirements*, then I'd, I suppose, want my input's metadata to form a superset. (And also, in the revised code, probably be compatible with the `SchemaShape.Column` of whatever metadata they are on, maybe.)

However, then we have this test.

https://github.com/dotnet/machinelearning/blob/5654d7265e54264db869bbc7fb0e3c1264091c21/src/Microsoft.ML.Core/Data/IEstimator.cs#L90-L92

We take the *input* metadata, and then do a set subtraction from *this* metadata, which will by non-empty if the input has any columns this does not, but this seems to be the opposite of what the comment had suggested. In an upcoming PR for this issue, I have effectively reversed this logic so that it is consistent with the comment, which at least at this moment looks more sensible to me.
