### ISSUE TITLE
Provide an example of LightgbmRanker?

### ISSUE THREAD

**Issue by sharpwood** [dotnet/machinelearning#776]
@codemzs

**Comment by Zruty0** [comment]
LightGBM should appear in the same way as other learners we have (SDCA, FastTree etc.)
Write xmldoc for it in the source code.

**Comment by justinormont** [comment]
When making an example... [ranking](https://en.wikipedia.org/wiki/Learning_to_rank) has a few differences vs. Regression/Classification tasks:
* Sorted/grouped dataset (all examples from the same group need to be next to each other)
* `GroupId` is required
* Label is one of { 0, 1, 2, 3, 4 }

There is a benchmark which includes LightGBMRanking:
https://github.com/dotnet/machinelearning/blob/17ee205e585beb62777475af6d59cba816675eeb/test/Microsoft.ML.Benchmarks/Numeric/Ranking.cs#L51-L67

It is written in the command-line language instead of C#. It would be nice to have a C# API ranking example.

**Comment by sfilipi** [comment]
A test for LightGBM ranker is here: https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Tests/TrainerEstimators/TreeEstimators.cs#L116

Should convert it to an example.
