### ISSUE TITLE
Example for NormalizeTransformLogNormalColumn

### ISSUE THREAD

**Issue by cosmincatalin** [dotnet/machinelearning#806]
I can see that there is this class `NormalizeTransformLogNormalColumn`, which seems like it should do exactly what I need, apply a log transform to a column. I have looked and tried everything to get it working with an existing pipeline, but failed miserably. Can anyone help me with an example of how to use it? Here is my pipeline:

```
var pipeline = new LearningPipeline();
pipeline.Add(new TextLoader(DataPath).CreateFrom<SearchData>(useHeader: true, separator: ','));
pipeline.Add(new NormalizeTransformLogNormalColumn()); // This does not work
```

**Comment by Zruty0** [comment]
Unfortunately, the name is misleading. `NormalizeTransformLogNormalColumn` is a settings object that allows log-normal normalization of input column: that is, transform it in such a way that the `log` of the column has `mean=0, variance=1`. 

This means that this is not what you really want (just apply `log` to your column).

We are planning to add a 'custom delegate transformation' to ML.NET, and after we do this, you should be able to just say something like

```c#
pipeline.Add(new CustomColumnTransform("MyColumnName", "MyOutputColumnName", (ref float input, ref float output) => output = Math.Log(input)));
```

or even
```c#
pipeline.Add(new CustomColumnTransform((ref float MyColumnName, ref float MyOutputColumnName) => MyOutputColumnName = Math.Log(MyInputColumnName)));
```

For now, unfortunately, all these custom operations need to be done prior to loading data. Or you could load the file yourself, do it in-memory and then use `CollectionDataSource` instead of `TextLoader`.

**Comment by cosmincatalin** [comment]
Thank you for the thorough explanation, @Zruty0. For the sake of completeness, can you provide also an example how `NormalizeTransformLogNormalColumn` is used as part of a pipeline?
