### ISSUE TITLE
Help needed with Multi-label string classification

### ISSUE THREAD

**Issue by xclud** [dotnet/machinelearning#807]
### Issue
I am new to ML (and i don't know if i chose a correct subject for the issue) and I need some help classifying some text into several emotion labels. My model has 6 emotions (anger, disgust, fear, happiness, sadness, and surprise) and i want to label many sentences/strings by these emotions to train the model. Later i will need check some string against the model to predict the emotions within the text. The data looks like this:

```
"Sentence #1" : Sad (10%), Fear (90%), Disgust (0%), Anger (0%), ...
"Sentense #2: : Happy (60%), Surprised (40%), Disgust (0%), Anger (0%), ...
```

I don't know which learner to start with and how to build my input class (class as in a `public class InData`). The "Features" and "Label" things look magics to me.

I will be happy to contribute a sample after i get my sample working.

**Comment by GalOshri** [comment]
Multi-label classification, where each sentence has multiple emotions, is not yet easy to do with ML.NET. One simplification that might be useful for getting started is to consider only the top emotion for each sentence. So your dataset might be:
```
Sentence 1, Fear
Sentence 2, Happy
...
```
This problem is similar to the sentiment tutorial [here](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis), where instead of a binary sentiment we have a multi-class emotion. The [Iris tutorial](https://www.microsoft.com/net/learn/machine-learning-and-ai/get-started-with-ml-dotnet-tutorial) shows how to work with multi-class problems.

In terms of the learner, it is worth trying out `OneVersusAll` (as shown [here](https://github.com/dotnet/machinelearning/blob/66de9a4fb60dc0587c6f760157b6dee167004b73/test/Microsoft.ML.Tests/Scenarios/PipelineApi/Metacomponents.cs#L31)) with [`AveragedPerceptronBinaryClassifier`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.averagedperceptronbinaryclassifier?view=ml-dotnet), as that learner often performs well for text classification problems.

**Comment by codemzs** [comment]
Gal seems to have answered.
