### ISSUE TITLE
Setting column weights in KmeansPlusPlus

### ISSUE THREAD

**Issue by SuperDaveWhite** [dotnet/machinelearning#884]
I find no clue as to how column weights can be adjusted for KmeansPlusPlus or any other type of ML. Gitter board shows no answer after several days. Is there an example? I did download the source code for ML.net and found nothing in the KMeans constructors. I assume ML.net will be doing this on the import or is it something not implemented so far? What is the road map to making this usable for where  KmeansPlusPlus needs to be tuned?

In Accord.net it's WeightColumn = (new double[] { .95, 0.05, .05, .95 }) . There is some WeightColumn to as a string, but no documentation how it would be used.

public Microsoft.ML.Runtime.EntryPoints.Optional<string> WeightColumn { get; set; }

**Comment by Ivanidzo4ka** [comment]
This is how you initialize it in code"
```
pipeline.Add(new KMeansPlusPlusClusterer() { K = k , WeightColumn = "YourWeightColumn"});
```
We run training on some dataset. This dataset presumably has some columns and some rows.
Rows is your examples and Columns created through data transformation or just by loading pure data.

I would assume you want to have weights for each example. In this case, all you need to do is provide additional column in this dataset, and specify it name in trainer as string.

**Comment by SuperDaveWhite** [comment]
Maybe this implementation is different that all others I have seen, but each column in a data set has one weight for each column samples. 

WeightColumn = (new double[] { .95, 0.05, .05, .95 }) // Open High Low Close

Are you saying we add a column for every row that is linked to a column elsewhere in that same row of the data set? If I follow then each 4 column row would be 8 columns if each data row would/could have a different weighting?

Open | High | Low | Close | Weight_Open | Weight_High | Weight_Low | Weight_Close

Still not sure how you would map them, maybe in order?

            var pipeline = new LearningPipeline()
            {
                // The TextLoader loads a dataset. The schema of the dataset is specified by passing a class 
                        containing
                // all the column names and their types.
                new TextLoader(DataPath).CreateFrom<OhlcData>(useHeader: false, separator: ','),
                // ColumnConcatenator concatenates all columns into Features column
                new ColumnConcatenator("Features",
                    "Open",
                    "High",
                    "Low",
                    "Close"),
                // KMeansPlusPlusClusterer is an algorithm that will be used to build clusters.
                new KMeansPlusPlusClusterer()
                    { 
                     K = 25,
                     OptTol = (float) .0000005, //Tolerance...
                     InitAlgorithm = (KMeansPlusPlusTrainerInitAlgorithm) 
                         KMeansPlusPlusTrainer.InitAlgorithm.KMeansPlusPlus,
                     WeightColumn = "Weight_Open", // How would each one map ?????????
                     MaxIterations = 5000,
                     AccelMemBudgetMb = 4 * 1024,
                     NumThreads = 8
                    }
                };
           var model = pipeline.Train<OhlcData, ClusterPrediction>();


I think what I need is a trivial example of how to do this with more than one column of data with each column weighted. I don't need each row granularity. Is there another way for global weighting of each column?

Regards,

**Comment by Ivanidzo4ka** [comment]
I guess it's problem with terminology.
We assume weights suppose to be for each example. To change importance of certain examples.

And if I correctly understand you, you just want to play with importance of each column (if that column has just a float value).

Theoretically you just need transform which would accept row of your dataset and delegate and you can do something like: (row) => { row.A *=0.95; row.B*=0.05, row.C*=.05; row.D*=0.95;  return row;}
Which we don't have.

But if you want to achieve this behavior, you can remove TextReader and replace it with custom data reader which would populate your data into certain class, and you can apply your coefficients during reading, and after that just feed your data to pipeline through CollectionDataSource class
see:
https://github.com/dotnet/machinelearning/blob/52aff025df29cc02c00999c5ca4a0833a658d142/test/Microsoft.ML.Tests/CollectionDataSourceTests.cs#L135

**Comment by SuperDaveWhite** [comment]
I have used 4 different packages for Kmeans. Each one allowed inline weighting of column data. Do you think it will cause some confusion as I have had, understanding that ML.net is quite different? Also it seems in Kmeans, it takes one of the simplest machine learning algo's and makes it quickly complex for tuning? I am no expert but one of the things I was looking for was a very .net experience and less python linux approach to chaining the pipeline. 

I would suggest that it operate as the other packages that I have used do. 

My view could be all wrong and I could have just used the 4 out of 100 that do it this way, if so please let me know.

**Comment by Ivanidzo4ka** [comment]
I can give you my point of view, but I can't speak for whole team.
http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html
https://www.tensorflow.org/api_docs/python/tf/contrib/factorization/KMeans
https://spark.apache.org/docs/1.5.0/api/java/org/apache/spark/mllib/clustering/KMeans.html

I don't see weights support at all in them, especially in your column meaning of weights.
And since we are framework and not standalone package for kmeans, we would prefer to generalize learners behavior.

Weights for examples make sense for me. Instead of repeating same example 10000 times in your dataset, you just put 10000 for corresponding example and it get boost in terms of significantcy. 
So we want to support this weight column across pretty much all learners.

You column based weights also in some way make sense, but having two weights in learner would be extremely confusing.

Main reason why I don't like this column based weights is because for me it looks like more about data preparation, one more step where you apply your coefficients to columns. Unless you want this coefficients  only during training and not during testing(scoring), but I'm not sure you want this case.

That been said, I agree we need a easier way to apply coefficients to data. AFAIK in current pipeline API it's not possible. We have some examples how it can be done in our non-public API https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Tests/Scenarios/Api/Extensibility.cs and we currently working on new API to make it possible.

**Comment by Zruty0** [comment]
As @Ivanidzo4ka pointed out, we prefer to have generalized solutions as opposed to per-learner ones.

The suggested workaround looks fine to me: apply a element-wise multiplication on your feature column prior to training. 

Finally, we have a [CustomMapping](https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Extensibility.cs) operation in the API, that allows you to perform arbitrary operations as part of the data pipeline, so the code Ivan posted above is possible. 

I would like to close this issue. Please feel free to reopen if it's not yet answered.
