### ISSUE TITLE
Use the actual argument name, in addition to the short name in error messages. 

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#966]
For TrainerEstimators, assigning a "bad" value to the arguments will result in an error like:

"Message: System.ArgumentOutOfRangeException : Illegal input value
Parameter name: p"

Where p is the ShortName of the respective argument. 
In addition to the short name, the error messages should also include the full argument name, because short names are not API user-facing.

**Comment by Ivanidzo4ka** [comment]
Sorry, but I'm having problem with deciphering your description. Any chance you can post code snippet of 

>  assigning a "bad" value to the arguments

**Comment by TomFinley** [comment]
Could we please clarify where this is happening? We should never be using the short name *anywhere*, since all value parsing should be using the C# `nameof` syntax, and so cannot be using the short name. If the error message contains the shortname, this is an error! (So I agree with your issue @sfilipi but would go one step further, it is essential that it *not* use the short name in the error message! An API user would have absolutely no idea what it is talking about.)
